### ISSUE TITLE
August 11 - Learning Data Science Concepts through the Lens of Space Exploration

### ISSUE THREAD

**Issue by drguthals** [microsoft/ReactorPlanning#107]
# Event Information
| Category | Details |
|-----------|---------|
| Reactor Topic | Data Science and Machine Learning |
| Monthly Topic (if applicable) | N/A |
| Weekly Topic (if applicable) | N/A |
| Stream Topic | Vinnie will walk through the new NASA Learning Paths on MS Learn |
| Stream Date | August 11, 2020 | 
| Stream Time | 9:15am PT | 
| Stream Duration | 60 minutes | 
| Title | To Infinity and Beyond! Using Data Science Concepts for Space Exploration |
| Description | Data science is a field that influences all aspects of our scientific community, including space exploration. In partnership with NASA, Microsoft Intern Vincent Angellotti has developed new content for analyzing space rocks and determining the likelihood of a successful rocket launch into space. Join this session to explore this data and to perhaps develop your own space exploration study using Visual Studio Code and a bit of Python. This session recommends a basic understanding of Visual Studio Code and Python programming. |
| Speaker | @angevin17  |
| Moderator | @sguthals  |
| SharePoint ID | 7882 |  

Additional Resources:  
<Additional resources that can be linked from social media for promotion or added to the description of VOD>

# Event Checklist

## 10 Weeks Prior
- [x] Reactor Content Team (RCT) or Speaker opens a new issue for an upcoming stream filling in the Event Information table. Both RCT and Speaker are marked as assignees.
- [x] RCT and Speaker discuss details of the event in the comments of this issue. RCT adds a _confirmed-event_ label and _global-twitch-event_ tag to the issue and adds event to the __Global Live Streams__ project. Issue will appear in the __Upcoming Streams__ column
- [x] Speaker adds a _ready-for-marketing-edit_ label so the RCT can review title and description

## 8 Weeks Prior
- [x] RCT does a review of title and description and removes the _ready-for-marketing-edit_ label 
- [x] RCT moves the issue to the __Ready for SharePoint__ column
- [x] RCT informs the Reactor Marketing Team of the new event information
- [ ] RCT provides speaker with assets (e.g. slides, overlays) and the survey data for the event
- [x] RCT moves the issue to the __MONTH Streams Prep__ column (according to the month it will be streamed in)

## 2 Weeks Prior *(Done in /microsoft/Reactors)*
- [ ] Speaker opens a PR with the new content for the stream on the [customer-facing Reactor repository](https://github.com/microsoft/Reactors) and adds the _content-development_ and _global-twitch-event_ tag to the PR. 
- [ ] Speaker adds to the same PR a modification to the [Streaming README](https://github.com/microsoft/Reactors/tree/main/Online) to include their stream information.
- [ ] Speaker adds the RCT assigned to the issue as the reviewer when it is ready for review/merge
- [ ] RCT reviews, approves, and merges the changes

## 1 Week Prior
- [ ] Speaker and Moderator test setup for streaming (instructions coming soon)
- [ ] RCT checks in with the speaker and moves the issue to the __Ready to Stream__ column

## During and After Stream
- [ ] Speaker and Moderator run the stream
- [x] RCT submits recording to be uploaded to the Reactor YouTube and to be made available on LearnTV
- [x] RCT moves issue to the __Stream Complete__ column

**Comment by drguthals** [comment]
@KimberlyBolton1 -> Here is a one-off event that we will be running in August, needs your attention 😄

**Comment by mebaumb** [comment]
FYI @sguthals & @angevin17 , Sharepoint won't let us schedule at 15 mins, it has to be on the hour or half hour, so i have put this stream in from 9a - 10:30 LMK if I should update that.

**Comment by drguthals** [comment]
Ah.... @mebaumb -> Will that be confusing though? There is just something on Ch9 the ends at 9am and starts at 10am. 

If we can double check with Ch9 on whether we can have 15 minute start times too - and then also if we cant if we are OK to start right at 9am.

**Comment by mebaumb** [comment]
It might be a little confusing, yes. Let me know what works for you guys!

**Comment by KimberlyBolton1** [comment]
@sguthals Here's the edit, let me know your thoughts:

To Infinity and Beyond! Using Data Science Concepts for Space Exploration
Data science is a field that influences all aspects of our scientific community, including space exploration. In partnership with NASA, Microsoft Intern Vincent Angellotti has developed new content for analyzing space rocks and determining the likelihood of a successful rocket launch into space. Join this session to explore this data and to perhaps develop your own space exploration study using Visual Studio Code and a bit of Python. This session recommends a basic understanding of Visual Studio Code and Python programming.

**Comment by drguthals** [comment]
@KimberlyBolton1 - Looks great to me! 🚢

**Comment by KimberlyBolton1** [comment]
@mebaumb abstract final and moved to Ready for Sharepoint.

**Comment by mebaumb** [comment]
This has been published to SharePoint/Meetup (7/15)

**Comment by drguthals** [comment]
@mebaumb - should I add the "confirmed event" label?

**Comment by mebaumb** [comment]
> @mebaumb - should I add the "confirmed event" label?

Sorry @sguthals! I have added all the right labels! I don't know why I forgot to do that!

**Comment by drguthals** [comment]
No worries! I just got paranoid 😆

**Comment by mebaumb** [comment]
Totally understandable! I just confirmed it's published in Sharepoint and good to go on that end! :)

**Comment by KimberlyBolton1** [comment]
Session recorded and uploaded to YouTube: https://www.youtube.com/watch?v=xmz51LmjI8U&t=1s. Closing issue.
