### ISSUE TITLE
July 22 - How Automated Machine Learning Reduces Time to Insights

### ISSUE THREAD

**Issue by drguthals** [microsoft/ReactorPlanning#11]
# Event Information
| Category | Details |
|-----------|---------|
| Reactor Topic | Data Science/Machine Learning |
| Monthly Topic (if applicable) | Connecting with Our World Through Data |
| Weekly Topic (if applicable) | Machine Learning |
| Stream Topic | <2-5 words describing the topic> |
| Stream Date | July 22, 2020 | 
| Stream Time | 9am PT | 
| Stream Duration | 60 Min | 
| Title | How Automated Machine Learning Reduces Time to Insights |
| Description | Determining meaningful answers from large, complex datasets is a difficult and lengthy problem, even with the support of validated machine learning algorithms. In this session, you will learn about the functionality of Azure’s automated machine learning (ML) service. The Azure Auto ML service not only helps you build ML models efficiently using one algorithm, but then compares dozens of algorithm setups, scores them, and helps you gain insights from multiple perspectives. Ultimately, it allows data scientists, analysts, and developers to build ML models with high-scale efficiency and productivity, all while sustaining model quality.  |
| Speaker | Amy Boyd |
| Moderator | <Name or GitHub alias> |
| Event ID | 7803 |

Additional Resources:  
<Additional resources that can be linked from social media for promotion or added to the description of VOD>

# Event Checklist

## 10 Weeks Prior
- [X] Reactor Content Team (RCT) or Speaker opens a new issue for an upcoming stream filling in the Event Information table. Both RCT and Speaker are marked as assignees.
- [X] RCT and Speaker discuss details of the event in the comments of this issue. RCT adds a _confirmed-event_ label and _global-twitch-event_ tag to the issue and adds event to the __Global Live Streams__ project. Issue will appear in the __Upcoming Streams__ column
- [X] Speaker adds a _ready-for-marketing-edit_ label so the RCT can review title and description

## 8 Weeks Prior
- [X] RCT does a review of title and description and removes the _ready-for-marketing-edit_ label 
- [X] RCT moves the issue to the __Ready for SharePoint__ column
- [X] RCT informs the Reactor Marketing Team of the new event information
- [ ] RCT provides speaker with assets (e.g. slides, overlays) and the survey data for the event
- [X] RCT moves the issue to the __MONTH Streams Prep__ column (according to the month it will be streamed in)

## 2 Weeks Prior *(Done in /microsoft/Reactors)*
- [ ] Speaker opens a PR with the new content for the stream on the [customer-facing Reactor repository](https://github.com/microsoft/Reactors) and adds the _content-development_ and _global-twitch-event_ tag to the PR. 
- [ ] Speaker adds to the same PR a modification to the [Streaming README](https://github.com/microsoft/Reactors/tree/main/Online) to include their stream information.
- [ ] Speaker adds the RCT assigned to the issue as the reviewer when it is ready for review/merge
- [ ] RCT reviews, approves, and merges the changes

## 1 Week Prior
- [ ] Speaker and Moderator test setup for streaming (instructions coming soon)
- [ ] RCT checks in with the speaker and moves the issue to the __Ready to Stream__ column

## During and After Stream
- [ ] Speaker and Moderator run the stream
- [x] RCT submits recording to be uploaded to the Reactor YouTube and to be made available on LearnTV
- [x] RCT moves issue to the __Stream Complete__ column

**Comment by amynic** [comment]
Hi everyone - looking forward to this session. Do let me know if you need me to start committing assets to this repo etc. I noticed above "RCT provides speaker with assets (e.g. slides, overlays) and the survey data for the event" - please do send over any assets I should be using for this stream - Thanks :)

**Comment by drguthals** [comment]
👋 @amynic

We're just about 2 weeks away from your stream!

I wanted to make sure of a couple of things:
- [ ] I owe you the survey link for Reactor Surveys, I'm tracking that down and will get it to you. 
- [ ] Do you have any content that you want the audience to have access to before, during, or after your stream? If so:
  - [ ] When do you expect it to be ready?
  - [ ] Where does it live? (If you need a place for it to live, you can add it to the [Online folder on the Reactors repo](https://github.com/microsoft/Reactors/tree/main/online-event-resources) by just opening a PR and adding it in there. If it's useful to add your own subfolder, please feel free to do that.) 
  - [ ] Whether you are hosting it on your own repo or in the Reactors repo, could you please add a link to it from the [README in the Online folder on the Reactors repo](https://github.com/microsoft/Reactors/blob/main/online-event-resources/july-event-resources.md)
  - [ ] You can add me (@sguthals) as a reviewer on any PRs to the Reactors repo
- [ ] Do you have a moderator for your stream? 

Please let me know if you have any questions or concerns! And let me know how I can help you be successful! ❤️

**Comment by amynic** [comment]
Hi @sguthals apologies for the delay - very much looking forward to the stream and have all content prepped and ready to go :) I do have some useful links and next steps for attendees I was going to add a Readme to the Online Reactor folder - however I am getting a 404 for these pages: https://github.com/microsoft/Reactors/tree/main/Online

I will work on getting a moderator for my stream asap. 

To confirm I will run scenes from OBS on my machine? Is there specific artwork to use? Will I be sent a streamkey etc?

Thanks for your help

**Comment by drguthals** [comment]
👋 @amynic - sorry about that! did a bit of refactoring last night:
https://github.com/microsoft/Reactors/tree/main/online-event-resources

You should reach out to @clarkio for a stream key. We don't yet have OBS overlays for the Reactor, but you can use the ones from the [Microsoft Developer channel](https://microsoft.sharepoint.com/:u:/t/LiveCoders/EfgMe5CX4WdJgjmEgxBmuUIBFOes5PsHjCgwkw5yaF3JTg?e=VpjsTW)

Let me know if you need anything else! 😄

**Comment by amynic** [comment]
Ah no problem @sguthals  😊👍 thanks for sending the updated URL will get on this this evening to share content

@clarkio - I am streaming on behalf of the reactor Wednesday 22nd July - please could you send a stream key
@clarkio - I believe I last streamed quite early on in this program - please could you re-share the Microsoft Developer overlays in case there has been updates

**Comment by drguthals** [comment]
Hi @amynic!

Just letting you know that your Survey Code is: 7803 and the link is: https://aka.ms/Reactor/Survey

Let me know if you need anything else!

**Comment by amynic** [comment]
Hi Sarah

Thanks for the link below – so do I advertise the link and code below at the start and end of the stream? Is it like a conference session feedback type survey?

@Brian Clark<mailto:Brian.Clark@microsoft.com> – could you provide a microsoft developer stream key for my session at 9:00PST tomorrow (Wednesday)? Also could you provide me access to edit the title of the stream just before the show?

Thanks,

Amy Boyd - Cloud Advocate, Scalable Content Team | Developer Relations |Cloud & AI |Microsoft

**Comment by drguthals** [comment]
@amynic - Yes! You can use this template if you'd like: https://slidedecks.blob.core.windows.net/reactorslides/Twitch%20Stream%20Template.potx

And then, yes, if you could display the survey link+code at the beginning and end, and we recommend pasting it into the chat towards the end

**Comment by amynic** [comment]
@Amy Boyd<mailto:Amy.Boyd@microsoft.com> you should receive your key shortly and I've added 'amykateboyd' as a moderator and editor. Please confirm you received the stream key (Twitch can sometimes fail to send it) and can open up the stream manager url: https://dashboard.twitch.tv/u/microsoftdeveloper/stream-manager

Regards,
Brian

________________________________
From: Amy Boyd <Amy.Boyd@microsoft.com>
Sent: Tuesday, July 21, 2020 1:36 PM
To: Sarah Guthals <sarah.guthals@microsoft.com>; Brian Clark <Brian.Clark@microsoft.com>
Cc: microsoft/ReactorPlanning <reply@reply.github.com>
Subject: RE: [microsoft/ReactorPlanning] July 22 - How Automated Machine Learning Reduces Time to Insights (#11)


Hi Sarah



Thanks for the link below – so do I advertise the link and code below at the start and end of the stream? Is it like a conference session feedback type survey?



@Brian Clark<mailto:Brian.Clark@microsoft.com> – could you provide a microsoft developer stream key for my session at 9:00PST tomorrow (Wednesday)? Also could you provide me access to edit the title of the stream just before the show?



Thanks,



Amy Boyd - Cloud Advocate, Scalable Content Team | Developer Relations |Cloud & AI |Microsoft

**Comment by amynic** [comment]
Hi Brian,

Thanks so much – yes I can confirm Twitch has sent me the key and I have access to the stream manager – wish me luck 😁⭐

Thanks,

Amy Boyd - Cloud Advocate, Scalable Content Team | Developer Relations |Cloud & AI |Microsoft

**Comment by drguthals** [comment]
You've got this!
--

*Sarah Guthals, PhD*
sarah@guthals.com
guthals.com/sarah

**Comment by KimberlyBolton1** [comment]
Session uploaded to YouTube: https://youtu.be/UgRaGp3uPqk 
Closing issue.
