### ISSUE TITLE
Sep 8 - Rust Programming: Moving Beyond “Hello World”

### ISSUE THREAD

**Issue by meaghanlewis** [microsoft/ReactorPlanning#110]
# Event Information
| Category | Details |
|-----------|---------|
| Reactor Topic | Coding, Languages, Frameworks |
| Monthly Topic (if applicable) | Skill Up September |
| Weekly Topic (if applicable) | Rust |
| Stream Date | Sep 8, 2020 | 
| Stream Time | 9AM PT | 
| Stream Duration | 90 minutes | 
| Title | Rust Programming: Moving Beyond “Hello World” |
| Description | Rust is a memory-safe, fast, general-purpose programming language that is also fun to write. Join Principal Cloud Advocate Ryan Levick as he dives into Rust coding by building a simple command-line app using Visual Studio Code. To follow along with the session, install Visual Studio Code (https://code.visualstudio.com/Download), Rust (https://www.rust-lang.org/tools/install), and the Rust Analyzer (https://marketplace.visualstudio.com/items?itemName=matklad.rust-analyzer). |
| Speaker |  @rylev  |
| Moderator | @meaghanlewis |
| SharePoint ID | 7942 |  

Additional Resources:  
<Additional resources that can be linked from social media for promotion or added to the description of VOD>

# Event Checklist

## 10 Weeks Prior
- [X] Reactor Content Team (RCT) or Speaker opens a new issue for an upcoming stream filling in the Event Information table. Both RCT and Speaker are marked as assignees.
- [X] RCT and Speaker discuss details of the event in the comments of this issue. RCT adds a _confirmed-event_ label and _global-twitch-event_ tag to the issue and adds event to the __Global Live Streams__ project. Issue will appear in the __Upcoming Streams__ column
- [X] Speaker adds a _ready-for-marketing-edit_ label so the RCT can review title and description

## 8 Weeks Prior
- [X] RCT does a review of title and description and removes the _ready-for-marketing-edit_ label 
- [x] RCT moves the issue to the __Ready for SharePoint__ column
- [x] RCT informs the Reactor Marketing Team of the new event information
- [x] RCT provides speaker with assets (e.g. slides, overlays) and the survey data for the event
- [x] RCT moves the issue to the __MONTH Streams Prep__ column (according to the month it will be streamed in)

## 2 Weeks Prior *(Done in /microsoft/Reactors)*
- [ ] Speaker opens a PR with the new content for the stream on the [customer-facing Reactor repository](https://github.com/microsoft/Reactors) and adds the _content-development_ and _global-twitch-event_ tag to the PR. 
- [ ] Speaker adds to the same PR a modification to the [Streaming README](https://github.com/microsoft/Reactors/tree/main/Online) to include their stream information.
- [ ] Speaker adds the RCT assigned to the issue as the reviewer when it is ready for review/merge
- [ ] RCT reviews, approves, and merges the changes

## 1 Week Prior
- [ ] Speaker and Moderator test setup for streaming (instructions coming soon)
- [ ] RCT checks in with the speaker and moves the issue to the __Ready to Stream__ column

## During and After Stream
- [ ] Speaker and Moderator run the stream
- [ ] RCT submits recording to be uploaded to the Reactor YouTube and to be made available on LearnTV
- [ ] RCT moves issue to the __Stream Complete__ column

**Comment by meaghanlewis** [comment]
Hi @mebaumb heads up that I just added this issue for the additional stream on 9/8 at 9am PT.

 @KimberlyBolton1 can you please have a pass at the title/description.

**Comment by KimberlyBolton1** [comment]
@rylev  Edited abstract below. In addition to reviewing it for accuracy, is there any other info you could add to provide more detail on what your session will cover? Also, what prereq knowledge do you recommend your audience have? 

Rust Programming: Moving Beyond “Hello World”
Rust is a memory-safe, fast, general-purpose programming language that is also fun to write. Join Principal Cloud Advocate Ryan Levick as he dives into Rust coding by building a simple command-line app using Visual Studio Code. 
To follow along with the session, install Visual Studio Code (https://code.visualstudio.com/Download), Rust (https://www.rust-lang.org/tools/install), and the "rustup" Visual Studio Code extension (https://rustup.rs).

**Comment by rylev** [comment]
@KimberlyBolton1 The extension people should download is [rust-analyzer](https://marketplace.visualstudio.com/items?itemName=matklad.rust-analyzer), not rustup. 

Other than that, it looks good.

**Comment by KimberlyBolton1** [comment]
@mebaumb
Abstract final (did not receive additional content). Moved to Ready for Sharepoint.

**Comment by meaghanlewis** [comment]
👋  @mebaumb just making sure this is on your radar.

**Comment by mebaumb** [comment]
Thanks for the reminder Meaghan! This has been published on Dynamics!

**Comment by mebaumb** [comment]
This has been published on Youtube. Closing
