### ISSUE TITLE
Nov 17 - 18: Explore Logistic Regression

### ISSUE THREAD

**Issue by mebaumb** [microsoft/ReactorPlanning#116]
# Event Information
| Category | Details |
|-----------|---------|
| Reactor Topic | Data Science and Machine Learning |
| Workshop Duration | 60 min| 
| Title | Explore Logistic Regression |
| Description | Logistic regression takes inputs and predicts whether something is true or false. It is usually used for classification of objects by shared qualities or characteristics. In this workshop, we'll look at the loan eligibility process for customers that want to buy a home. After analyzing details provided by customers, we can use logistic regression to determine whether or not they are eligible. To follow along you'll need to have Visual Studio Code installed with the Python extension. |
| Content | https://github.com/microsoft/Reactors/tree/main/workshop-resources/data-science-and-machine-learning/Data_Science_1/loan-project |

# Workshop(s) details
| Date |  Local Start Time |  Location |  Speaker | SharePoint ID | Platform |
|------|-------------------|-----------|----------|---------------|----------|
| 11/17 | 6:30 pm | Bangalore | Avinash Mishra | 11875 |----------|
| 11/17 | 4 pm PT | US, Canada, Sydney | Michael Galanyk | 11876 |----------|
| 11/18 | 7:30 pm | Sao Paulo | Fabricio Murai Ferreira | 11877 |----------|
| 11/18 | 7:30 pm | Shanghai | Ryan Chung | 11878 |----------|
| 11/18 | 12:00 pm GMT+1 | London, Stockholm, Abu Dhabi, Tel Aviv | Brian Sletten | 11879 |----------|

# Event Checklist

## 10 Weeks Prior
- [x] Reactor Content Team (RCT) opens a new issue for an upcoming local workshop filling in the Event Information and Workshop details tables. RCT member who owns content (content owner) this week will be the assignee.
- [x] RCT and content owner discuss details of the event in the comments of this issue. RCT adds a _confirmed-event_ label and _local-digital-event_ tag to the issue and adds event to the __Local Digital Events__ project. Issue will appear in the __Upcoming Streams__ column
- [x] RCT adds a _ready-for-marketing-edit_ label so the RCT can review title and description

## 8 Weeks Prior
- [x] RCT does a review of title and description and removes the _ready-for-marketing-edit_ label 
- [x] RCT moves the issue to the __Ready for SharePoint__ column
- [x] RCT informs the Reactor Marketing Team of the new event information
- [x] RCT confirms the speaker
- [x] RCT provides speaker with assets (e.g. slides, overlays) and the survey data for the event
- [x] RCT moves the issue to the __Content Preparation In Progress__ column

## 5 weeks Prior
- [ ] Content owner opens a PR with the new content for the workshop on the [customer-facing Reactor repository](https://github.com/microsoft/Reactors/tree/main/online-event-resources) and adds the _content-development_ and _local-digital-event_ tag to the PR. 
- [ ] RCT reviews, approves, and merges the changes
- [ ] RCT shares content with the vendor/instructor
- [ ] RCT provides vendor/instructor with assets (e.g. slides, overlays) and the survey data for the event
- [ ] RCT ensures that instructors have received an invite to the workshops and that PM team works with instructors to get setup in the platform (e.g. Teams, Teams Live Event)

## 1 Week Prior
- [ ] Connect vendor/instructor with the PM(s) for the locations where this event has been marketed
- [ ] Check-in with vendor/instructor that they are prepared for the workshop
- [ ] RCT moves the issue to the __Ready to Stream__ column

## During and After Stream
- [ ] Instructor (and optional moderator) run the stream
- [ ] _(Optional)_RCT submits recording to be uploaded to the Reactor YouTube and to be made available on LearnTV
- [ ] RCT moves issue to the __Stream Complete__ column

**Comment by mebaumb** [comment]
I don't have any edits for this one! Do we want to run it by anyone else? Or should we publish?

**Comment by meaghanlewis** [comment]
Just made a quick update. I think it's ready to publish as-is!

**Comment by mebaumb** [comment]
This event has been published! I will update it again when we have speakers!

**Comment by mebaumb** [comment]
Speakers added to Dynamics and Published!

**Comment by meaghanlewis** [comment]
Here's an overview of what this workshop will cover and suggested agenda to follow with links and resources.

## Content to teach
This workshop will take Reactor community members through the [Data Science 1 loan project](https://aka.ms/DSLoanProject)

**SHARE THIS LINK WITH REACTOR ATTENDEES: https://aka.ms/DSLoanProject**

## Agenda
1. [Explain the purpose of the workshop](https://github.com/microsoft/Reactors/blob/main/workshop-resources/data-science-and-machine-learning/Data_Science_1/loan-project/1-loan-activity.md) 5-10 min
   - Explain the problem that we're trying to solve in the workshop
   - Highlight the variables in the data and what they mean
   - Show the [test and train data sets](https://github.com/microsoft/Reactors/tree/main/workshop-resources/data-science-and-machine-learning/Data_Science_1/loan-project/Data)
   - Explain how they can follow along during the workshop
      - **Visual Studio Code** is needed
      - Python extension is needed
      - Familiarity with Python recommended
      - Encourage attendees to download the data and .ipynb file needed
2. [Walk through the notebook](https://github.com/microsoft/Reactors/blob/main/workshop-resources/data-science-and-machine-learning/Data_Science_1/loan-project/loan-notebook.ipynb) 45 min
    - Make sure everyone can get their Jupyter Notebook running in VS Code
    - Go through each section explaining what's happening
    - Encourage questions and answer them as they come in
3. **Next steps** 2 min
    - Encourage attendees to reference this notebook and go through it on their own time as needed
4. **Closing** 5 min
    - Q&A
    - **Ask attendees to take the survey: https://aka.ms/Reactor/Survey**
      - Note: The event code is listed in this issue description and/or your Reactor contact can share that with the community members during the workshop
    - Share Resources
      - Encourage attendees to view other DS and ML workshop materials here: https://github.com/microsoft/Reactors/tree/main/workshop-resources/data-science-and-machine-learning
    - Check if the Reactor contact has other information to share

**Comment by mebaumb** [comment]
Workshops have been run and attendance data tracked.
