### ISSUE TITLE
October 20 - Tips, Tricks, and Tools for Keeping up With All Things Azure

### ISSUE THREAD

**Issue by meaghanlewis** [microsoft/ReactorPlanning#117]
# Event Information
| Category | Details |
|-----------|---------|
| Reactor Topic | Cloud Development |
| Stream Topic | Learn about different Azure services |
| Stream Date | October 20, 2020 | 
| Stream Time | 4pm PT | 
| Stream Duration | 60 minutes | 
| Title |  Tips, Tricks, and Tools for Keeping up With All Things Azure |
| Description | With over 200 services available in the Azure Marketplace, and new ones being released all the time, it's easy to feel overwhelmed when trying to keep up. Join Azure MVP, Gwyneth Peña as she dives into tips and tricks on how you can keep up to date with new services that interest you, without feeling like you're falling behind or losing out. If you want to follow along, make sure you have an Azure account. If you don't have an account yet, head to http://azure.microsoft.com/free to sign up.|
| Speaker | Gwyneth Pena (@madebygps) and Meaghan Lewis (@meaghanlewis) |
| Moderator | none |
| SharePoint ID | 8004 |  

Additional Resources:  
<Additional resources that can be linked from social media for promotion or added to the description of VOD>

# Event Checklist

## 10 Weeks Prior
- [x] Reactor Content Team (RCT) or Speaker opens a new issue for an upcoming stream filling in the Event Information table. Both RCT and Speaker are marked as assignees.
- [x] RCT and Speaker discuss details of the event in the comments of this issue. RCT adds a _confirmed-event_ label and _global-twitch-event_ tag to the issue and adds event to the __Global Live Streams__ project. Issue will appear in the __Upcoming Streams__ column
- [x] Speaker adds a _ready-for-marketing-edit_ label so the RCT can review title and description

## 8 Weeks Prior
- [x] RCT does a review of title and description and removes the _ready-for-marketing-edit_ label 
- [x] RCT moves the issue to the __Ready for SharePoint__ column
- [ ] RCT informs the Reactor Marketing Team of the new event information
- [ ] RCT provides speaker with assets (e.g. slides, overlays) and the survey data for the event
- [ ] RCT moves the issue to the __MONTH Streams Prep__ column (according to the month it will be streamed in)

## 2 Weeks Prior *(Done in /microsoft/Reactors)*
- [ ] Speaker opens a PR with the new content for the stream on the [customer-facing Reactor repository](https://github.com/microsoft/Reactors) and adds the _content-development_ and _global-twitch-event_ tag to the PR. 
- [ ] Speaker adds to the same PR a modification to the [online-event-resources directory](https://github.com/microsoft/Reactors/blob/main/online-event-resources/) to include their stream information.
- [ ] Speaker adds the RCT assigned to the issue as the reviewer when it is ready for review/merge
- [ ] RCT reviews, approves, and merges the changes

## 1 Week Prior
- [ ] Speaker and Moderator test setup for streaming (instructions coming soon)
- [ ] RCT checks in with the speaker and moves the issue to the __Ready to Stream__ column

## During and After Stream
- [ ] Speaker and Moderator run the stream
- [ ] RCT submits recording to be uploaded to the Reactor YouTube and to be made available on LearnTV
- [ ] RCT moves issue to the __Stream Complete__ column

**Comment by meaghanlewis** [comment]
👋   @madebygps, just created this issue to plan out details for the Azure stream on: https://www.twitch.tv/microsoftdeveloper. Could you add in a description of what you think will be covered in this stream in the comment above?

Don't worry about the checklists. My team and I will make sure you have everything you need to get setup.

**Comment by madebygps** [comment]
Please let me know if this needs more detail.

### Description

There are over 200 services in Azure, with new ones coming out frequently. It's easy to feel overwhelmed when trying to keep up. Join Azure MVP, Gwyneth Peña as she dives into how you can keep up to date with new services that interest you, without feeling like you're falling behind or losing out.

**Comment by meaghanlewis** [comment]
Thanks @madebygps! I think that description looks great. Maybe one sentence to add at the end:

If you want to follow along, make sure you have an Azure account. If you don't have an account yet, head to http://azure.microsoft.com/free to sign up.

**Comment by mebaumb** [comment]
@meaghanlewis  & @madebygps  what do you think about this demandgen  edit?

Tips, Tricks and Tools for Keeping up With All Things Azure

With over 200 services available in the Azure Marketplace, and new ones being released all the time, it's easy to feel overwhelmed when trying to keep up. Join Azure MVP, Gwyneth Peña as she dives into tips and tricks on how you can keep up to date with new services that interest you, without feeling like you're falling behind or losing out. If you want to follow along, make sure you have an Azure account. If you don't have an account yet, head to http://azure.microsoft.com/free to sign up.

**Comment by meaghanlewis** [comment]
@mebaumb that works for me!

**Comment by madebygps** [comment]
@mebaumb Looks good to me.

**Comment by meaghanlewis** [comment]
Hi @mebaumb we're going to need to cancel this stream due to Gwyneth's request. Hopefully we'll able to do this sometime in November, but for now, could you go ahead and make sure this gets cancelled? Thank you.

**Comment by mebaumb** [comment]
Stream is cancelled in Dynamics.
