### ISSUE TITLE
Oct 5 - Quantum docs hackathon kick-off

### ISSUE THREAD

**Issue by meaghanlewis** [microsoft/ReactorPlanning#118]
# Event Information
| Category | Details |
|-----------|---------|
| Reactor Topic |  Emerging Technologies  |
| Event Date | October 8, 2020 | 
| Event Time | 11am PT | 
| Duration | 90 minutes | 
| Title | Quantum docs hackathon kick-off |
| Description | October is the month for Hacktoberfest! In honor of Hacktoberfest, the Quantum Computing team at Microsoft will be having a month-long virtual hackathon focusing on API documentation improvements. Join the kickoff call, to learn all about where contributions are needed and how to get involved. Hear from maintainers of the projects directly who will provide guidance and walk through a contribution. **Agenda:**  - Welcome -How to contribute -Hear from project maintainers - Q& A **Note:** This kick-off will be recorded and available for viewing after the event ends. |
| Speakers | Kitty Yeung, Chris Granade, Ryan Shaffer, Sarah Marshall, Vincent can Wingerden |
| Moderator | Meaghan Lewis |
| Teams Live link | https://aka.ms/quantum-docs-hack-kickoff |
| SharePoint ID | 11845 |  

Additional Resources:  
<Additional resources that can be linked from social media for promotion or added to the description of VOD>

# Event Checklist

## 10 Weeks Prior
- [x] Reactor Content Team (RCT) or Speaker opens a new issue for an upcoming stream filling in the Event Information table. Both RCT and Speaker are marked as assignees.
- [x] RCT and Speaker discuss details of the event in the comments of this issue. RCT adds a _confirmed-event_ label and _global-twitch-event_ tag to the issue and adds event to the __Global Live Streams__ project. Issue will appear in the __Upcoming Streams__ column
- [x] Speaker adds a _ready-for-marketing-edit_ label so the RCT can review title and description

## 8 Weeks Prior
- [x] RCT does a review of title and description and removes the _ready-for-marketing-edit_ label 
- [x] RCT moves the issue to the __Ready for SharePoint__ column
- [x] RCT informs the Reactor Marketing Team of the new event information
- [ ] RCT provides speaker with assets (e.g. slides, overlays) and the survey data for the event
- [ ] RCT moves the issue to the __MONTH Streams Prep__ column (according to the month it will be streamed in)

## 2 Weeks Prior *(Done in /microsoft/Reactors)*
- [ ] Speaker opens a PR with the new content for the stream on the [customer-facing Reactor repository](https://github.com/microsoft/Reactors) and adds the _content-development_ and _global-twitch-event_ tag to the PR. 
- [ ] Speaker adds to the same PR a modification to the [online-event-resources directory](https://github.com/microsoft/Reactors/blob/main/online-event-resources/) to include their stream information.
- [ ] Speaker adds the RCT assigned to the issue as the reviewer when it is ready for review/merge
- [ ] RCT reviews, approves, and merges the changes

## 1 Week Prior
- [ ] Speaker and Moderator test setup for streaming (instructions coming soon)
- [ ] RCT checks in with the speaker and moves the issue to the __Ready to Stream__ column

## During and After Stream
- [ ] Speaker and Moderator run the stream
- [ ] RCT submits recording to be uploaded to the Reactor YouTube and to be made available on LearnTV
- [ ] RCT moves issue to the __Stream Complete__ column

**Comment by meaghanlewis** [comment]
@mebaumb using this issue to track this kick-off event. I've already created the TLE linked here and invited the speakers, but would like to have this promoted as a global event to: US, Can, Brazil, and European locations.

Let me know if you have any questions!

**Comment by mebaumb** [comment]
This has been published on Dynamics/Meetup!
