### ISSUE TITLE
Nov 4 - 5: Introduction to blockchain on Azure

### ISSUE THREAD

**Issue by meaghanlewis** [microsoft/ReactorPlanning#119]
# Event Information
| Category | Details |
|-----------|---------|
| Reactor Topic | Emerging Technologies |
| Workshop Topic | Blockchain |
| Workshop Duration | 45 min | 
| Title | Introduction to blockchain on Azure |
| Description | What is this session about? This is the first session in a three-part series on bockchain. We'll explore the technology fundamentals and how it enables trust in participants working together who don't know one another. We'll walk through the 'Introduction to Blockchain' module on Microsoft Learn: https://aka.ms/IntroBlockchain-8 followed by some time for Q&A and an informal chat. To follow along you'll need a free Microsoft account. Who is it aimed at? This is a beginner's session for anyone interested in learning more about blockchain technology. Some experience of software development would be useful, but not essential. Why should you join? Discover the fundamentals of blockchain and learn the tools to help you decide if it's the right solution for a project. About the Speaker Meaghan Lewis has been working in the tech industry for over a decade. She is currently a Technical Program Manager at Microsoft and focuses on creating and delivering learning experiences centered around emerging technologies such blockchain and quantum computing. Meaghan enjoys tinkering on personal projects and collaborating with other enthusiasts to explore new things. She is a California native who currently lives in the San Francisco Bay Area with her husband and two dogs.
| Content | https://aka.ms/IntroBlockchain-8 |

# Workshop(s) details
| Date |  Local Start Time |  Location |  Speaker | SharePoint ID | Platform |
|------|-------------------|-----------|----------|---------------|----------|
| 11/4 | 5pm PT | US, CAN, Sydney | @meaghanlewis | 11849 | Teams Live |
| 11/5 | 8:30am PT | London, Stockholm, Tel Aviv, Abu Dhabi, Bangalore | @meaghanlewis | 11850 | Teams Live |

# Event Checklist

## 10 Weeks Prior
- [x] Reactor Content Team (RCT) opens a new issue for an upcoming local workshop filling in the Event Information and Workshop details tables. RCT member who owns content (content owner) this week will be the assignee.
- [x] RCT and content owner discuss details of the event in the comments of this issue. RCT adds a _confirmed-event_ label and _local-digital-event_ tag to the issue and adds event to the __Local Digital Events__ project. Issue will appear in the __Upcoming Streams__ column
- [x] RCT adds a _ready-for-marketing-edit_ label so the RCT can review title and description

## 8 Weeks Prior
- [x] RCT does a review of title and description and removes the _ready-for-marketing-edit_ label 
- [x] RCT moves the issue to the __Ready for SharePoint__ column
- [x] RCT informs the Reactor Marketing Team of the new event information
- [x] RCT confirms the speaker
- [x] RCT provides speaker with assets (e.g. slides, overlays) and the survey data for the event
- [x] RCT moves the issue to the __Content Preparation In Progress__ column

## 5 weeks Prior
- [ ] Content owner opens a PR with the new content for the workshop on the [customer-facing Reactor repository](https://github.com/microsoft/Reactors/tree/main/online-event-resources) and adds the _content-development_ and _local-digital-event_ tag to the PR. 
- [ ] RCT reviews, approves, and merges the changes
- [ ] RCT shares content with the vendor/instructor
- [ ] RCT provides vendor/instructor with assets (e.g. slides, overlays) and the survey data for the event
- [ ] RCT ensures that instructors have received an invite to the workshops and that PM team works with instructors to get setup in the platform (e.g. Teams, Teams Live Event)

## 1 Week Prior
- [ ] Connect vendor/instructor with the PM(s) for the locations where this event has been marketed
- [ ] Check-in with vendor/instructor that they are prepared for the workshop
- [ ] RCT moves the issue to the __Ready to Stream__ column

## During and After Stream
- [ ] Instructor (and optional moderator) run the stream
- [ ] _(Optional)_RCT submits recording to be uploaded to the Reactor YouTube and to be made available on LearnTV
- [ ] RCT moves issue to the __Stream Complete__ column

**Comment by mebaumb** [comment]
What do you think about this @meaghanlewis ?

Join this workshop with Meaghan Lewis for an introduction to blockchain. We'll explore the technology to build a greater understanding and demonstrate how it enables trust between participants. Meaghan will also teach you how to assess when to use blockchain and decide if it's the right solution for your project. We will walk through the Introduction to blockchain module on Microsoft Learn [Link to module]. To follow along you'll need a free Microsoft account.

**Comment by meaghanlewis** [comment]
Looks good to me! ✅

**Comment by mebaumb** [comment]
Awesome, is this one good to publish? or are you still working on details? 

Also, I see that the London time is listed in PT is that accurate?

**Comment by meaghanlewis** [comment]
Yep, it's ready. Thank you!

**Comment by mebaumb** [comment]
Events published in Dynamics on 9/25

**Comment by meaghanlewis** [comment]
Here's my pass at a revision to the session details:

**What is this session about?**
This is the first session in a three-part series on bockchain. We'll explore the technology fundamentals, and how it enables trust in participants working together who don't know one another. We'll walk through the Introduction to blockchain module on Microsoft Learn: https://aka.ms/IntroBlockchain-8 followed by some Q&A. To follow along you'll need a free Microsoft account.

**Who should attend?**
This is a beginner's session for anyone wanthing to learn about blockchain technology.

**Why attend?**
To learn the fundamentals of blockchain technology and how to decide if it's the right soultion for a project.

**About the speaker**
Meaghan Lewis has been working in the tech industry for over a decade. She is currently a Technical Program Manager at Microsoft and focuses on creating and delivering learning experiences centered around emerging technologies like blockchain and quantum computing. Meaghan enjoys tinkering on personal projects and collaborating with other enthusiasts to explore new things. She is a California native who currently lives in the San Francisco Bay Area with her husband and two dogs.

**Comment by james-woollard** [comment]
I made a few tweaks below, but overall I think was working really well now :) 

What is this session about?
This is the first session in a three-part series on bockchain. We'll explore the technology fundamentals and how it enables trust in participants working together who don't know one another. We'll walk through the 'Introduction to Blockchain' module on Microsoft Learn: https://aka.ms/IntroBlockchain-8 followed by some time for Q&A and an informal chat. To follow along you'll need a free Microsoft account.

Who is it aimed at?
This is a beginner's session for anyone interested in learning more about blockchain technology. Some experience of software development would be useful, but not essential. 

Why should you join?
Discover the fundamentals of blockchain and learn the tools to help you decide if it's the right solution for a project.

About the Speaker
Meaghan Lewis has been working in the tech industry for over a decade. She is currently a Technical Program Manager at Microsoft and focuses on creating and delivering learning experiences centered around emerging technologies such blockchain and quantum computing. Meaghan enjoys tinkering on personal projects and collaborating with other enthusiasts to explore new things. She is a California native who currently lives in the San Francisco Bay Area with her husband and two dogs.

**Comment by meaghanlewis** [comment]
@mebaumb if there are no other edits you'd like to make, can we update the description of this for Dynamics and the Meetup pages? Thank you!

**Comment by mebaumb** [comment]
This has been updated!

**Comment by mebaumb** [comment]
Video was pre-recorded and shared out with team.
