### ISSUE TITLE
Nov 18 - 19: Join Meaghan Lewis for a Blockchain AMA

### ISSUE THREAD

**Issue by meaghanlewis** [microsoft/ReactorPlanning#121]
# Event Information
| Category | Details |
|-----------|---------|
| Reactor Topic | Emerging Technologies |
| Workshop Topic |  Blockchain |
| Workshop Duration | 55 min| 
| Title | Join Meaghan Lewis for a Blockchain AMA |
| Description | Join Blockchain enthusiast, Meaghan Lewis for an AMA (Ask Me Anything) on blockchain technology. Anything and everything blockchain related will be fair game! If you're a blockchain newbie who has basic questions of how to get started or a seasoned developer that has more complex questions you're welcome to join! We may talk about some real world examples, like how Microsoft Xbox uses blockchain solutions to what is happening with Ethereum 2.0. We'll start the AMA out with some pre-submitted questions and then take other questions live as they come in. We'd recommend watching the two previous sessions, Introduction to blockchain on Azure and Create Your Own Blockchain Network before attending this session, however, it's not mandatory. If you're a complete newbie and looking to get started with blockchain Microsoft's Introduction to Blockchain Learn Path is a great place to start! |
| Content with tracking Link| https://aka.ms/intro-to-blockchain-8 |

# Workshop(s) details
| Date |  Local Start Time |  Location |  Speaker | SharePoint ID | Platform |
|------|-------------------|-----------|----------|---------------|----------|
| 11/18 | 5pm PT | US/CAN/SYDNEY | @meaghanlewis | 11882 | | 
| 11/19 | 8:30am PT | London, Stockholm, Abu Dhabi, Tel Aviv, Bangalore | @meaghanlewis  | 11883 | |

# Event Checklist

## 10 Weeks Prior
- [x] Reactor Content Team (RCT) opens a new issue for an upcoming local workshop filling in the Event Information and Workshop details tables. RCT member who owns content (content owner) this week will be the assignee.
- [x] RCT and content owner discuss details of the event in the comments of this issue. RCT adds a _confirmed-event_ label and _local-digital-event_ tag to the issue and adds event to the __Local Digital Events__ project. Issue will appear in the __Upcoming Streams__ column
- [x] RCT adds a _ready-for-marketing-edit_ label so the RCT can review title and description

## 8 Weeks Prior
- [x] RCT does a review of title and description and removes the _ready-for-marketing-edit_ label 
- [x] RCT moves the issue to the __Ready for SharePoint__ column
- [x] RCT informs the Reactor Marketing Team of the new event information
- [x] RCT confirms the speaker
- [x] RCT provides speaker with assets (e.g. slides, overlays) and the survey data for the event
- [x] RCT moves the issue to the __Content Preparation In Progress__ column

## 5 weeks Prior
- [ ] Content owner opens a PR with the new content for the workshop on the [customer-facing Reactor repository](https://github.com/microsoft/Reactors/tree/main/online-event-resources) and adds the _content-development_ and _local-digital-event_ tag to the PR. 
- [ ] RCT reviews, approves, and merges the changes
- [ ] RCT shares content with the vendor/instructor
- [ ] RCT provides vendor/instructor with assets (e.g. slides, overlays) and the survey data for the event
- [ ] RCT ensures that instructors have received an invite to the workshops and that PM team works with instructors to get setup in the platform (e.g. Teams, Teams Live Event)

## 1 Week Prior
- [ ] Connect vendor/instructor with the PM(s) for the locations where this event has been marketed
- [ ] Check-in with vendor/instructor that they are prepared for the workshop
- [ ] RCT moves the issue to the __Ready to Stream__ column

## During and After Stream
- [ ] Instructor (and optional moderator) run the stream
- [ ] _(Optional)_RCT submits recording to be uploaded to the Reactor YouTube and to be made available on LearnTV
- [ ] RCT moves issue to the __Stream Complete__ column

**Comment by meaghanlewis** [comment]
I will need to find a co-speaker before these worksops can be finalized.

**Comment by mebaumb** [comment]
Hey wanted to get an update on this event, @meaghanlewis !

**Comment by meaghanlewis** [comment]
@mebaumb I was going to ping you about this one! It has taken longer since I'm trying to find someone who would be available on both days. I haven't had much luck for now so what I'd like to do is turn this into a blockchain AMA (ask me anything). I'll update the title and description a bit later today.

**Comment by meaghanlewis** [comment]
And by later today, I meant 3 minutes later 😄 . Here's my first pass:

**An AMA on all things blockchain**

Join Meaghan Lewis for an AMA (ask me anything )on blockchain technology. Anything blockchain related willl be fair game! From how Microsoft Xbox uses blockchain solutions to what is happening with Ethereum 2.0. We'll start out with some presubmitted questions and then take other questions live as they come in.

**Comment by mebaumb** [comment]
@meaghanlewis - What about this:
Join Blockchain expert, Meaghan Lewis for an AMA (Ask Me Anything) on blockchain technology. Anything and everything blockchain related will be fair game! If you're a blockchain newbie who has basic questions of how to get started or a seasoned developer that has some questions you're welcome to join! We may talk about some real world examples, like how Microsoft Xbox uses blockchain solutions to what is happening with Ethereum 2.0. We'll start the AMA out with some pre-submitted questions from previous workshops in this series and then take other questions live as they come in.

- do you want to offer the opportunity to have them pre-submit questions? Since there is no experience required, is there a Blockchain 101 video or learn path we want to point them to, so a newbie has a little context or are we good with nothing? we could say "If you're new to blockchain and want to take a look before the session - here are some great additional resources to get started." or something like that.

**Comment by meaghanlewis** [comment]
@mebaumb I love your edit! It's more fun and informative than mine.

>do you want to offer the opportunity to have them pre-submit questions?

What I was thinking here was to collect questions from the 2 previous week's that might have been left unanswered or were liked the most. The pre-req here then would be catching up from the previous 2 sessions and watching the recordings and/or going through the Learn modules. The best Learn module for newbies is [The Introduction to Blockchain](https://docs.microsoft.com/learn/modules/intro-to-blockchain/)

**Comment by mebaumb** [comment]
I made one little tweak and added the pre-reqs - are you ready to publish on Dynamics meet up? 

Join Blockchain expert, Meaghan Lewis for an AMA (Ask Me Anything) on blockchain technology. Anything and everything blockchain related will be fair game! If you're a blockchain newbie who has basic questions of how to get started or a seasoned developer that has more complex questions you're welcome to join! We may talk about some real world examples, like how Microsoft Xbox uses blockchain solutions to what is happening with Ethereum 2.0. We'll start the AMA out with some pre-submitted questions and then take other questions live as they come in. 

We'd recommend watching the two previous sessions, Introduction to blockchain on Azure and Create Your Own Blockchain Network before attending this session, however, it's not mandatory. If you're a complete newbie and looking to get started with blockchain [Microsoft's Introduction to Blockchain Learn Path](https://docs.microsoft.com/learn/modules/intro-to-blockchain/) is a great place to start!

**Comment by meaghanlewis** [comment]
Love it. Ready to publish!

**Comment by mebaumb** [comment]
This was published!

**Comment by meaghanlewis** [comment]
@mebaumb is it okay if we don't use the work expert actually? So maybe the title is: **Join Meaghan Lewis for a Blockchain AMA**

And the first sentence starts with: "Join Blockchain enthusiast..."

I'm sorry for not calling that out _before_ you published.

**Comment by mebaumb** [comment]
No prob at all! Fixed it both here and in Dynamics! :)

**Comment by meaghanlewis** [comment]
**What is this session about?**
Join blockchain enthusiast, Meaghan Lewis for an AMA (Ask Me Anything) on blockchain technology in this last session of a three-part series. We may talk about some real world examples, like how Microsoft Xbox uses blockchain solutions to what is happening with Ethereum 2.0. We'll start the AMA out with some pre-submitted questions and then take other questions live as they come in. 

We'd recommend watching the two previous sessions, Introduction to blockchain on Azure and Create Your Own Blockchain Network before attending this session, however, it's not mandatory. If you're a complete newbie and looking to get started with blockchain Microsoft's [Get started with blockchain development learning path](https://docs.microsoft.com/learn/paths/ethereum-blockchain-development/) is a great place to start!

**Who should attend?**
 This session is for anyone who is interested in blockchain. Whether you're a blockchain newbie who has basic questions of how to get started or a seasoned developer that has more complex questions you're welcome to join! 

**Why attend?**
To answer all your burning questions around blockchain. Anything and everything blockchain related will be fair game! 

**About the speaker**
Meaghan Lewis has been working in the tech industry for over a decade. She is currently a Technical Program Manager at Microsoft and focuses on creating and delivering learning experiences centered around emerging technologies like blockchain and quantum computing. Meaghan enjoys tinkering on personal projects and collaborating with other enthusiasts to explore new things. She is a California native who currently lives in the San Francisco Bay Area with her husband and two dogs.

**Comment by james-woollard** [comment]
**What is this session about?**
Join blockchain enthusiast, Meaghan Lewis for an AMA (Ask Me Anything) on blockchain technology in this final session of a three-part series. We cover some real world examples, from how Microsoft Xbox uses blockchain solutions to what is happening with Ethereum 2.0. We'll start the AMA out with some pre-submitted questions and then take other questions live that you may wish to ask. 

We recommend watching the two previous sessions, Introduction to blockchain on Azure and Create Your Own Blockchain Network before attending this session, however, it's not mandatory. If you're a complete newbie and looking to get started with blockchain, [Get started with blockchain development learning path](https://docs.microsoft.com/learn/paths/ethereum-blockchain-development/) is a great place to begin!

**Who is it aimed at?** 
This session is for anyone who is interested in blockchain. Whether you're a blockchain newbie who has basic questions onhow to get started or are a seasoned developer that has more complex questions. Everyone is welcome to join!

**Why should you join?** 
To answer all your burning questions around blockchain. Anything and everything blockchain related will be up for discussion! 

About the speaker
Meaghan Lewis has been working in the tech industry for over a decade. She is currently a Technical Program Manager at Microsoft and focuses on creating and delivering learning experiences centered around emerging technologies such blockchain and quantum computing. Meaghan enjoys tinkering on personal projects and collaborating with other enthusiasts to explore new things. She is a California native who currently lives in the San Francisco Bay Area with her husband and two dogs.

**Comment by meaghanlewis** [comment]
@mebaumb same with this one! I think it's ready to be updated in Dynamics/Meetups

**Comment by mebaumb** [comment]
This has been updated! 10/8
