### ISSUE TITLE
Nov 24 - 25: Explore Linear Regression and Classification

### ISSUE THREAD

**Issue by meaghanlewis** [microsoft/ReactorPlanning#122]
# Event Information
| Category | Details |
|-----------|---------|
| Reactor Topic |  Data Science and Machine Learning | 
| Workshop Duration | 60 min | 
| Title | Explore Linear Regression and Classification  |
| Description | In this workshop, we'll use Jupyter Notebooks to explore linear regression and classification in mammals. A fundamental component of mastering data science concepts is by learning how to apply them in different scenarios and of course, lots of practice. We will get some more practice by using the Python extension in Visual Studio Code to explore, visualize, and classify a variety of mammals based on their characteristics. For this workshop, it is recommended that you have a basic understanding of data science principles and would recommend a basic understanding of Python, but it's not required. |
| Content | https://github.com/microsoft/Reactors/blob/main/workshop-resources/data-science-and-machine-learning/Data_Science_2/bioscience-project/ |

# Workshop(s) details
| Date |  Local Start Time |  Location |  Speaker | SharePoint ID | Platform |
|------|-------------------|-----------|----------|---------------|----------|
| 11/24 | 8:30 pm | Bangalore | Michael Galanyk | 11916 |----------|
| 11/24 | 4:00 PM | US, Canada, Sydney | Michael Galanyk | 11917 |----------|
| 11/25 | 7:30 PM | Sao Paulo | Fabricio Murai Ferreira | 11918 |----------|
| 11/25 | 7:30 PM | Shanghai | Ryan Chung | 11919 |----------|
| 11/25 | 12:00 PM | London, Stockholm, Abu Dhabi, Tel Aviv | Brian Sletten | 11920 |----------|

# Event Checklist

## 10 Weeks Prior
- [x] Reactor Content Team (RCT) opens a new issue for an upcoming local workshop filling in the Event Information and Workshop details tables. RCT member who owns content (content owner) this week will be the assignee.
- [x] RCT and content owner discuss details of the event in the comments of this issue. RCT adds a _confirmed-event_ label and _local-digital-event_ tag to the issue and adds event to the __Local Digital Events__ project. Issue will appear in the __Upcoming Streams__ column
- [x] RCT adds a _ready-for-marketing-edit_ label so the RCT can review title and description

## 8 Weeks Prior
- [x] RCT does a review of title and description and removes the _ready-for-marketing-edit_ label 
- [x] RCT moves the issue to the __Ready for SharePoint__ column
- [x] RCT informs the Reactor Marketing Team of the new event information
- [x] RCT confirms the speaker
- [ ] RCT provides speaker with assets (e.g. slides, overlays) and the survey data for the event
- [ ] RCT moves the issue to the __Content Preparation In Progress__ column

## 5 weeks Prior
- [ ] Content owner opens a PR with the new content for the workshop on the [customer-facing Reactor repository](https://github.com/microsoft/Reactors/tree/main/online-event-resources) and adds the _content-development_ and _local-digital-event_ tag to the PR. 
- [ ] RCT reviews, approves, and merges the changes
- [ ] RCT shares content with the vendor/instructor
- [ ] RCT provides vendor/instructor with assets (e.g. slides, overlays) and the survey data for the event
- [ ] RCT ensures that instructors have received an invite to the workshops and that PM team works with instructors to get setup in the platform (e.g. Teams, Teams Live Event)

## 1 Week Prior
- [ ] Connect vendor/instructor with the PM(s) for the locations where this event has been marketed
- [ ] Check-in with vendor/instructor that they are prepared for the workshop
- [ ] RCT moves the issue to the __Ready to Stream__ column

## During and After Stream
- [ ] Instructor (and optional moderator) run the stream
- [ ] _(Optional)_RCT submits recording to be uploaded to the Reactor YouTube and to be made available on LearnTV
- [ ] RCT moves issue to the __Stream Complete__ column

**Comment by mebaumb** [comment]
This is the week of thanksgiving. Did we want to have workshops?

**Comment by meaghanlewis** [comment]
I was thinking that we could have workshops since only the US celebrates Thanksgiving and most of the locations are outside of the US.

**Comment by mebaumb** [comment]
So the 11/24 one will be just marketed to Sydney and Toronto, correct?

**Comment by meaghanlewis** [comment]
I think it's okay to market to the US as well since it's still a couple days before the holiday.

**Comment by mebaumb** [comment]
Editing Pass: 
In this workshop, we'll use Jupyter Notebooks to explore linear regression and classification with 

> _biology statistic for mammals_ - Not sure what this means?

. A fundamental component of mastering data science concepts is by learning how to apply them in different scenarios and of course, lots of practice. While we will practice using Python with data science and machine learning in a life-sciences context, the skills you learn will be applicable across many disciplines and industry verticals.

To follow along....[Meaghan, can you help with what they need to know?]

**Comment by mebaumb** [comment]
@meaghanlewis - just a friendly bump about the abstract for this session. Stephie would like this published by 10/9 if possible! :)

**Comment by meaghanlewis** [comment]
@mebaumb thanks for the reminder! Here's another pass at an abstract. Hopefully this is clearer than the last one.

In this workshop, we'll use Jupyter Notebooks to explore linear regression and classification in mammals. A fundamental component of mastering data science concepts is by learning how to apply them in different scenarios and of course, lots of practice. We will get some more practice by using the Python extension in Visual Studio Code to explore, visualize, and classify a variety of mammals based on their characteristics. For this workshop, it is recommended that you have a basic understanding of data science principles.

**Comment by mebaumb** [comment]
@meaghanlewis -

I think it's great, much clearer! Do they need to know python at all? 

If you're happy with this, I can get this published today :)

**Comment by meaghanlewis** [comment]
Maybe some familiarity with Python, but it's not required. Thank you!

**Comment by mebaumb** [comment]
Speakers updated in Dynamics and published on Meetup

**Comment by meaghanlewis** [comment]
Here's an overview of what this workshop will cover and suggested agenda to follow with links and resources.

## Content to teach
This workshop will take Reactor community members through the [Data Science 2 bioscience project](https://aka.ms/DSBioscienceProject)

**SHARE THIS LINK WITH REACTOR ATTENDEES: https://aka.ms/DSBioscienceProject**

## Agenda
1. **Intro** 5-10 min
   - Explain the problem that we're trying to solve in the workshop
   - Show the [data sets](https://github.com/microsoft/Reactors/tree/main/workshop-resources/data-science-and-machine-learning/Data_Science_2/bioscience-project/Data) and what information is in each csv file
   - Explain how they can follow along during the workshop
      - **Visual Studio Code** is needed
      - Python extension is needed
      - Familiarity with Python recommended
      - Encourage attendees to download the data and .ipynb file needed
2. **[Walk through the notebook](https://github.com/microsoft/Reactors/blob/main/workshop-resources/data-science-and-machine-learning/Data_Science_2/bioscience-project/DS2-Student.ipynb)** 45 min
    - Make sure everyone can get their Jupyter Notebook running in VS Code
      - Note: You can use either the instructor or the student notebook. The instructor notebook has more notes and guidance
    - Go through each section explaining what's happening
    - Encourage questions and answer them as they come in
3. **Next steps** 2 min
    - Encourage attendees to reference this notebook and go through it on their own time as needed
4. **Closing** 5 min
    - Q&A
    - **Ask attendees to take the survey: https://aka.ms/Reactor/Survey**
      - Note: The event code is listed in this issue description and/or your Reactor contact can share that with the community members during the workshop
    - Share Resources
      - Encourage attendees to view other DS and ML workshop materials here: https://github.com/microsoft/Reactors/tree/main/workshop-resources/data-science-and-machine-learning
    - Check if the Reactor contact has other information to share

**Comment by mebaumb** [comment]
Workshops have been run and attendance data tracked. Closing issue
