### ISSUE TITLE
Nov 11 - Setting up GitHub actions for deploying to Kubernetes

### ISSUE THREAD

**Issue by mebaumb** [microsoft/ReactorPlanning#126]
# Event Information
| Category | Details |
|-----------|---------|
| Reactor Topic | Cloud Development |
| Monthly Topic (if applicable) | n/a |
| Weekly Topic (if applicable) | n/a |
| Stream Topic | Microservices on Kubernetes |
| Stream Date | Nov 11, 2020 | 
| Stream Time | 9:00 AM PST | 
| Stream Duration | 60 Mins  | 
| Title | Setting up GitHub actions for deploying to Kubernetes |
| Description | Join Aaron Schlesinger in this live stream and learn how to build GitHub actions to take your code, package it up, and deploy it to Kubernetes automatically. We'll show everything from Dockerfiles to Helm charts to Kubernetes terminal dashboards. Come hang out in chat, and as always, AMA! |
| Speaker | @arschles  |
| Moderator | <Name or GitHub alias> |
| SharePoint ID | 11924 |  

Additional Resources:  
<Additional resources that can be linked from social media for promotion or added to the description of VOD>

# Event Checklist

## 10 Weeks Prior
- [x] Reactor Content Team (RCT) or Speaker opens a new issue for an upcoming stream filling in the Event Information table. Both RCT and Speaker are marked as assignees.
- [x] RCT and Speaker discuss details of the event in the comments of this issue. RCT adds a _confirmed-event_ label and _global-twitch-event_ tag to the issue and adds event to the __Global Live Streams__ project. Issue will appear in the __Upcoming Streams__ column
- [x] Speaker adds a _ready-for-marketing-edit_ label so the RCT can review title and description

## 8 Weeks Prior
- [x] RCT does a review of title and description and removes the _ready-for-marketing-edit_ label 
- [x] RCT moves the issue to the __Ready for SharePoint__ column
- [x] RCT informs the Reactor Marketing Team of the new event information
- [ ] RCT provides speaker with assets (e.g. slides, overlays) and the survey data for the event
- [ ] RCT moves the issue to the __MONTH Streams Prep__ column (according to the month it will be streamed in)

## 2 Weeks Prior *(Done in /microsoft/Reactors)*
- [ ] Speaker opens a PR with the new content for the stream on the [customer-facing Reactor repository](https://github.com/microsoft/Reactors) and adds the _content-development_ and _global-twitch-event_ tag to the PR. 
- [ ] Speaker adds to the same PR a modification to the [online-event-resources directory](https://github.com/microsoft/Reactors/blob/main/online-event-resources/) to include their stream information.
- [ ] Speaker adds the RCT assigned to the issue as the reviewer when it is ready for review/merge
- [ ] RCT reviews, approves, and merges the changes

## 1 Week Prior
- [ ] Speaker and Moderator test setup for streaming (instructions coming soon)
- [ ] RCT checks in with the speaker and moves the issue to the __Ready to Stream__ column

## During and After Stream
- [ ] Speaker and Moderator run the stream
- [ ] RCT submits recording to be uploaded to the Reactor YouTube and to be made available on LearnTV
- [ ] RCT moves issue to the __Stream Complete__ column

**Comment by arschles** [comment]
Reactor Topic: Cloud Development
Stream Topic: Microservices on Kubernetes
Title: Setting up GitHub actions for deploying to Kubernetes
Description: Come learn how to build GitHub actions to take your code, package it up, and deploy it to Kubernetes automatically. Questions, comments, and AMA in the chat

**Comment by mebaumb** [comment]
Sounds great to me! I will get this published and send you the calendar invite.
