### ISSUE TITLE
Dec 2 - Build a decentralized app

### ISSUE THREAD

**Issue by meaghanlewis** [microsoft/ReactorPlanning#127]
# Event Information
| Category | Details |
|-----------|---------|
| Reactor Topic |  Emerging Technologies |
| Stream Topic | blockchain decentralized app |
| Stream Date | Dec 2, 2020 | 
| Stream Time | 9am | 
| Stream Duration | 60 min | 
| Title | Build a decentralized app |
| Description | Decentralized applications, or Dapps for short, are what really brings smart contracts to life. Creating these UI applications is what allows people to interact with and execute transactions with contracts. Dapps are used in everything from games to supply chain management to financial transactions. The possibilities of Dapps you can build are endless. This stream is for anyone who wants to learn more about creating apps with blockchain. Join this stream to see how to use Drizzle to build a Dapp from scratch. To best follow along, we recommend that you have a fundamental understanding about blockchain technology and the Ethereum platform. |
| Speaker | @meaghanlewis |
| Moderator | <Name or GitHub alias> |
| SharePoint ID | 11921 |  

Additional Resources:  
<Additional resources that can be linked from social media for promotion or added to the description of VOD>

# Event Checklist

## 10 Weeks Prior
- [x] Reactor Content Team (RCT) or Speaker opens a new issue for an upcoming stream filling in the Event Information table. Both RCT and Speaker are marked as assignees.
- [x] RCT and Speaker discuss details of the event in the comments of this issue. RCT adds a _confirmed-event_ label and _global-twitch-event_ tag to the issue and adds event to the __Global Live Streams__ project. Issue will appear in the __Upcoming Streams__ column
- [x] Speaker adds a _ready-for-marketing-edit_ label so the RCT can review title and description

## 8 Weeks Prior
- [x] RCT does a review of title and description and removes the _ready-for-marketing-edit_ label 
- [x] RCT moves the issue to the __Ready for SharePoint__ column
- [x] RCT informs the Reactor Marketing Team of the new event information
- [x] RCT provides speaker with assets (e.g. slides, overlays) and the survey data for the event
- [x] RCT moves the issue to the __MONTH Streams Prep__ column (according to the month it will be streamed in)

## 2 Weeks Prior *(Done in /microsoft/Reactors)*
- [ ] Speaker opens a PR with the new content for the stream on the [customer-facing Reactor repository](https://github.com/microsoft/Reactors) and adds the _content-development_ and _global-twitch-event_ tag to the PR. 
- [ ] Speaker adds to the same PR a modification to the [online-event-resources directory](https://github.com/microsoft/Reactors/blob/main/online-event-resources/) to include their stream information.
- [ ] Speaker adds the RCT assigned to the issue as the reviewer when it is ready for review/merge
- [ ] RCT reviews, approves, and merges the changes

## 1 Week Prior
- [ ] Speaker and Moderator test setup for streaming (instructions coming soon)
- [ ] RCT checks in with the speaker and moves the issue to the __Ready to Stream__ column

## During and After Stream
- [ ] Speaker and Moderator run the stream
- [ ] RCT submits recording to be uploaded to the Reactor YouTube and to be made available on LearnTV
- [ ] RCT moves issue to the __Stream Complete__ column

**Comment by mebaumb** [comment]
@meaghanlewis  - what do you think of this?

Decentralized applications, or Dapps for short, are what really brings smart contracts to life. Creating these UI applications is what allows people to interact with and execute transactions with contracts. Dapps are used in everything from games to supply chain management to financial transactions. The possibilities of Dapps you can build are endless. This stream is for anyone who wants to learn more about creating apps with blockchain. Join this stream to see how to use [Drizzle](https://www.trufflesuite.com/drizzle) to build a Dapp from scratch.

To best follow along, we recommend that you have a fundamental understanding about blockchain technology and the Ethereum platform.

**Comment by meaghanlewis** [comment]
@mebaumb I added edits inline to your comment above. thanks!

**Comment by mebaumb** [comment]
Looks great to me! Do you want me to publish? 

Also is there any links that you want to share? Like to github or anything?

**Comment by meaghanlewis** [comment]
@mebaumb this looks good! no links to add at this time.

**Comment by mebaumb** [comment]
@meaghanlewis  - great! I will get it published! :)

**Comment by mebaumb** [comment]
This event has run, stream data has been recorded.

**Comment by ghost** [comment]
Hi, where can I find the code you copy-pasted during the video for the Shipment.sol and ShipComponent.js files? Thank you!

**Comment by meaghanlewis** [comment]
@bumbdy you can find that code here: https://github.com/microsoft/Reactors/blob/main/workshop-resources/emerging-tech/Blockchain_2/creating_decentralized_apps/create-a-dapp-for-shipping.md
