### ISSUE TITLE
Dec 9 - Explore Ethereum networks

### ISSUE THREAD

**Issue by meaghanlewis** [microsoft/ReactorPlanning#128]
# Event Information
| Category | Details |
|-----------|---------|
| Reactor Topic | Emerging Technologies |
| Stream Topic | Ethereum blockchain networks |
| Stream Date | Dec 9 , 2020 | 
| Stream Time | 9am | 
| Stream Duration | 60 min | 
| Title | Explore Ethereum Networks |
| Description | Let's explore the different networks Ethereum provides. Learn what tools you can use to connect to and interact with networks, and discuss the process of deploying to them. Then, we'll deploy a blockchain app to a local and test network. Join this stream with Senior Program Manager, Meaghan Lewis, to understand how to take your blockchain projects from development to production. It is recommended that you have a fundamental understanding about blockchain technology and the Ethereum platform to best follow along. |
| Speaker | @meaghanlewis |
| Moderator | <Name or GitHub alias> |
| SharePoint ID | 11922 |  

Additional Resources:  
<Additional resources that can be linked from social media for promotion or added to the description of VOD>

# Event Checklist

## 10 Weeks Prior
- [x] Reactor Content Team (RCT) or Speaker opens a new issue for an upcoming stream filling in the Event Information table. Both RCT and Speaker are marked as assignees.
- [x] RCT and Speaker discuss details of the event in the comments of this issue. RCT adds a _confirmed-event_ label and _global-twitch-event_ tag to the issue and adds event to the __Global Live Streams__ project. Issue will appear in the __Upcoming Streams__ column
- [ ] Speaker adds a _ready-for-marketing-edit_ label so the RCT can review title and description

## 8 Weeks Prior
- [ ] RCT does a review of title and description and removes the _ready-for-marketing-edit_ label 
- [ ] RCT moves the issue to the __Ready for SharePoint__ column
- [ ] RCT informs the Reactor Marketing Team of the new event information
- [ ] RCT provides speaker with assets (e.g. slides, overlays) and the survey data for the event
- [ ] RCT moves the issue to the __MONTH Streams Prep__ column (according to the month it will be streamed in)

## 2 Weeks Prior *(Done in /microsoft/Reactors)*
- [ ] Speaker opens a PR with the new content for the stream on the [customer-facing Reactor repository](https://github.com/microsoft/Reactors) and adds the _content-development_ and _global-twitch-event_ tag to the PR. 
- [ ] Speaker adds to the same PR a modification to the [online-event-resources directory](https://github.com/microsoft/Reactors/blob/main/online-event-resources/) to include their stream information.
- [ ] Speaker adds the RCT assigned to the issue as the reviewer when it is ready for review/merge
- [ ] RCT reviews, approves, and merges the changes

## 1 Week Prior
- [ ] Speaker and Moderator test setup for streaming (instructions coming soon)
- [ ] RCT checks in with the speaker and moves the issue to the __Ready to Stream__ column

## During and After Stream
- [ ] Speaker and Moderator run the stream
- [ ] RCT submits recording to be uploaded to the Reactor YouTube and to be made available on LearnTV
- [ ] RCT moves issue to the __Stream Complete__ column

**Comment by mebaumb** [comment]
@meaghanlewis  - is this one ready for a marketing edit too?

**Comment by meaghanlewis** [comment]
@mebaumb yes it is!

**Comment by mebaumb** [comment]
This looks great to me - I capitalized your title, but that was the only edit i have. Do you want me to publish? do you have any GitHub Links you want to share? 

Let's explore the different networks Ethereum provides. Learn what tools you can use to connect to and interact with networks, and discuss the process of deploying to them. Then, we'll deploy a blockchain app to a local and test network. Join this stream with Senior Program Manager, Meaghan Lewis, to understand how to take your blockchain projects from development to production. It is recommended that you have a fundamental understanding about blockchain technology and the Ethereum platform to best follow along.

**Comment by meaghanlewis** [comment]
@mebaumb all good to publish. thanks!

**Comment by mebaumb** [comment]
@meaghanlewis - what do you think about this edit?

What is the session about?
The Ethereum blockchain protocol has multiple independent networks available for participants. Networks are different Ethereum environments you can access for development, testing, or production use cases. We'll explore multiple public networks, including the different testnets that are available as well as the mainnet. Then, we'll select a testnet and walk through the process to deploy a blockchain app and get some test Ether. Join this stream with Senior Program Manager, Meaghan Lewis, to understand how to take your blockchain projects from development to test to production. 

Who is it aimed at?
It is recommended that you have a fundamental understanding about blockchain technology and the Ethereum platform to best follow along.

Why should you attend?
If you use Ethereum and want to learn more about effectively interacting with networks or some new tools to leverage that connection, this stream is for you.

**Comment by meaghanlewis** [comment]
@mebaumb thanks for the edit! I made a few changes inline. If that all reads okay, feel free to go ahead and update.
