### ISSUE TITLE
January 11-15 - How to Manipulate and Clean Your Data

### ISSUE THREAD

**Issue by mebaumb** [microsoft/ReactorPlanning#146]
# Event Information
| Category | Details |
|-----------|---------|
| Reactor Topic | Data Science and Machine Learning |
| Monthly Topic (if applicable) | <Topic taken from [Azure Dev Marketing](https://aka.ms/DevEdCalFY21H1)> |
| Weekly Topic (if applicable) |  |
| Workshop Topic | Intro To DS/ML |
| Workshop Duration | 60 minutes| 
| Title | How to Manipulate and Clean your Data |
| Description |  What is the session about? The most important tool a Data Scientist has is a good, clean data set. Unfortunately, in the real world, data often comes from multiple sources and is not immediately ready for analysis. About 80% of the data science process is usually spent on cleaning and preparing data so that it makes sense, is complete, and doesn't introduce biases all before the actual analysis can happen. This session will focus on the tools, processes, and strategies that data scientists use in preparing their data sets. Who is it aimed at? This session is aimed at anyone who is looking to learn more about the data science process and how to improve their data sets using industry standard tools, strategies, and tips. Why should you attend? This session will give beginners and veterans alike the opportunity to learn or reinforce the industry standards for data manipulation and will give them the opportunity to practice these skills in a hands on workshop. |

# Workshop(s) details
| Date |  Local Start Time |  Location |  Speaker | SharePoint ID | Platform |
|------|-------------------|-----------|----------|---------------|----------|
| Jan 12, 2021 | 6:30 PM | Bangalore | Avinash Mishra | 12464 |----------|
| Jan 12, 2021 | 4:00 PM | US/CA/AU | Dave Wade-Stein | 12465 |----------|
| Jan 13, 2021 | 7:30 PM | Sao Paulo | Pedro Olmo Vaz de Melo| 12466 |----------|
| Jan 13, 2021 | 7:30 PM | Shanghai | Ryan Chung | 12467 |----------|
| Jan 13, 2021 | 12:00 PM | EMEA | Dave Wade-Stein | 12468 |----------|

# Event Checklist

## 10 Weeks Prior
- [x] Reactor Content Team (RCT) opens a new issue for an upcoming local workshop filling in the Event Information and Workshop details tables. RCT member who owns content (content owner) this week will be the assignee.
- [x] RCT and content owner discuss details of the event in the comments of this issue. RCT adds a _confirmed-event_ label and _local-digital-event_ tag to the issue and adds event to the __Local Digital Events__ project. Issue will appear in the __Upcoming Streams__ column
- [ ] RCT adds a _ready-for-marketing-edit_ label so the RCT can review title and description

## 8 Weeks Prior
- [ ] RCT does a review of title and description and removes the _ready-for-marketing-edit_ label 
- [ ] RCT moves the issue to the __Ready for SharePoint__ column
- [ ] RCT informs the Reactor Marketing Team of the new event information
- [ ] RCT confirms the speaker
- [ ] RCT provides speaker with assets (e.g. slides, overlays) and the survey data for the event
- [ ] RCT moves the issue to the __Content Preparation In Progress__ column

## 5 weeks Prior
- [ ] Content owner opens a PR with the new content for the workshop on the [customer-facing Reactor repository](https://github.com/microsoft/Reactors/tree/main/online-event-resources) and adds the _content-development_ and _local-digital-event_ tag to the PR. 
- [ ] RCT reviews, approves, and merges the changes
- [ ] RCT shares content with the vendor/instructor
- [ ] RCT provides vendor/instructor with assets (e.g. slides, overlays) and the survey data for the event
- [ ] RCT ensures that instructors have received an invite to the workshops and that PM team works with instructors to get setup in the platform (e.g. Teams, Teams Live Event)

## 1 Week Prior
- [ ] Connect vendor/instructor with the PM(s) for the locations where this event has been marketed
- [ ] Check-in with vendor/instructor that they are prepared for the workshop
- [ ] RCT moves the issue to the __Ready to Stream__ column

## During and After Stream
- [ ] Instructor (and optional moderator) run the stream
- [ ] _(Optional)_RCT submits recording to be uploaded to the Reactor YouTube and to be made available on LearnTV
- [ ] RCT moves issue to the __Stream Complete__ column

**Comment by mebaumb** [comment]
@meaghanlewis - Here is the previous description I found for this session: 
"Real world data often comes from multiple sources and isn't always ready for analysis. Before you can get started with really analyzing your data, you have to clean and manipulate it so that it makes sense, is complete, and doesn't introduce biases. Join us in learning about best practices and how to get your data ready."

Using the template, I expanded it below, please let me know your thoughts!:

What is the session about?
The most important tool a Data Scientist has is a good, clean data set. Unfortunately, in the real world, data often comes from multiple sources and is not immediately ready for analysis. About 80% of the data science process is usually spent on cleaning and preparing data so that it makes sense, is complete, and doesn't introduce biases all before the actual analysis can happen. This session will focus on the tools, processes, and strategies that data scientists use in preparing their data sets.
 
Who is it aimed at?
This session is aimed at anyone who is looking to learn more about the data science process and how to improve their data sets using industry standard tools, strategies, and tips.

Why should you attend?
This session will give beginners and veterans alike the opportunity to learn or reinforce the industry standards for data manipulation and will give them the opportunity to practice these skills in a hands on workshop.

**Comment by meaghanlewis** [comment]
@mebaumb thanks! I made a few edits inline. If you're happy with them, feel free to go ahead and update in the appropriate places.

**Comment by mebaumb** [comment]
Thank you! I will get this published! :)

**Comment by mebaumb** [comment]
Published without speaker data (11/23)
