### ISSUE TITLE
January 18 -22 - Intro to Machine Learning Models

### ISSUE THREAD

**Issue by mebaumb** [microsoft/ReactorPlanning#147]
# Event Information
| Category | Details |
|-----------|---------|
| Reactor Topic | Data Science and Machine Learning |
| Monthly Topic (if applicable) | <Topic taken from [Azure Dev Marketing](https://aka.ms/DevEdCalFY21H1)> |
| Weekly Topic (if applicable) |  |
| Workshop Topic | Machine Learning Models |
| Workshop Duration | 60 minutes | 
| Title | Intro to Machine Learning Models |
| Description |  What is the session about? Every day new data is created. New parts are made and shipped from factories, people continuously tweet, and companies grow and fluctuate causing major changes in the market. With the addition of more data comes the difficulty of being able to process that data. As humans, we can understand complex scenarios, but computers are much better at being able to analyze large datasets. In this workshop, you will get a glimpse into how we can teach machines to analyze complex scenarios at a much larger scale than we're able to. We'll use a cleaned data set to train and test machine learning models and publish your predictor online for others to explore. Who is it aimed at? This session is aimed at learners who are interested in learning about how to train and test Machine Learning Models. While you don't need to have any previous data science experience, ideally you should have at least 1 year of experience coding, preferably in Python. Why should you attend? This session is a great intro to Data Science and Machine Learning. We'll show you the basics of Machine Learning Models and how to build a foundational understanding of these principles. |

# Workshop(s) details
| Date |  Local Start Time |  Location |  Speaker | SharePoint ID | Platform |
|------|-------------------|-----------|----------|---------------|----------|
| Jan 19, 2021 | 6:30 PM | Bangalore | Avinash Mishra | 12479 |----------|
| Jan 19, 2021 | 4:00 PM | US/CA/AU | Dave Wade-Stein | 12478 |----------|
| Jan 20, 2021 | 7:30 PM | Sao Paulo | Pedro Olmo Vaz de Melo | 12482 |----------|
| Jan 20, 2021 | 7:30 PM | Shanghai | Ryan Chung | 12481 |----------|
| Jan 20, 2021 | 12:00 PM | EMEA | Dave Wade-Stein | 12480 |----------|

# Event Checklist

## 10 Weeks Prior
- [x] Reactor Content Team (RCT) opens a new issue for an upcoming local workshop filling in the Event Information and Workshop details tables. RCT member who owns content (content owner) this week will be the assignee.
- [x] RCT and content owner discuss details of the event in the comments of this issue. RCT adds a _confirmed-event_ label and _local-digital-event_ tag to the issue and adds event to the __Local Digital Events__ project. Issue will appear in the __Upcoming Streams__ column
- [ ] RCT adds a _ready-for-marketing-edit_ label so the RCT can review title and description

## 8 Weeks Prior
- [ ] RCT does a review of title and description and removes the _ready-for-marketing-edit_ label 
- [ ] RCT moves the issue to the __Ready for SharePoint__ column
- [ ] RCT informs the Reactor Marketing Team of the new event information
- [ ] RCT confirms the speaker
- [ ] RCT provides speaker with assets (e.g. slides, overlays) and the survey data for the event
- [ ] RCT moves the issue to the __Content Preparation In Progress__ column

## 5 weeks Prior
- [ ] Content owner opens a PR with the new content for the workshop on the [customer-facing Reactor repository](https://github.com/microsoft/Reactors/tree/main/online-event-resources) and adds the _content-development_ and _local-digital-event_ tag to the PR. 
- [ ] RCT reviews, approves, and merges the changes
- [ ] RCT shares content with the vendor/instructor
- [ ] RCT provides vendor/instructor with assets (e.g. slides, overlays) and the survey data for the event
- [ ] RCT ensures that instructors have received an invite to the workshops and that PM team works with instructors to get setup in the platform (e.g. Teams, Teams Live Event)

## 1 Week Prior
- [ ] Connect vendor/instructor with the PM(s) for the locations where this event has been marketed
- [ ] Check-in with vendor/instructor that they are prepared for the workshop
- [ ] RCT moves the issue to the __Ready to Stream__ column

## During and After Stream
- [ ] Instructor (and optional moderator) run the stream
- [ ] _(Optional)_RCT submits recording to be uploaded to the Reactor YouTube and to be made available on LearnTV
- [ ] RCT moves issue to the __Stream Complete__ column

**Comment by mebaumb** [comment]
@meaghanlewis - here is the original description I found: 
"Every day new data is created. New parts are made and shipped from factories, people continuously tweet, and companies grow and fluctuate causing major changes in the market. With the addition of more data comes the   difficulty of being able to process that data. As humans, we can understand   complex scenarios, but computers are much better at being able to analyze   large datasets. In this workshop, you will get a glimpse into how we can   teach machines to analyze complex scenarios at a much larger scale than we're   able to. After you've cleaned and organized your data, you will have an   opportunity to train and test machine learning models, and even publish your   predictor online for others to explore."

Here is my attempt to expand/move it into the new template, please let me know what you think:

What is the session about?
Every day new data is created. New parts are made and shipped from factories, people continuously tweet, and companies grow and fluctuate causing major changes in the market. With the addition of more data comes the difficulty of being able to process that data. As humans, we can understand complex scenarios, but computers are much better at being able to analyze large datasets. In this workshop, you will get a glimpse into how we can teach machines to analyze complex scenarios at a much larger scale than we're able to. We'll use a cleaned data set to train and test machine learning models and publish your predictor online for others to explore.

Who is it aimed at?
This session is aimed at learners who are interested in learning about how to train and test Machine Learning Models. While you don't need to have any previous data science experience, ideally you should have at least 1 year of experience coding, preferably in Python.

Why should you attend?
This session is a great intro to Data Science and Machine Learning. We'll show you the basics of Machine Learning Models and how to build a foundational understanding of these principles.

**Comment by meaghanlewis** [comment]
This looks great to me @mebaumb!

**Comment by mebaumb** [comment]
This has been published without speaker data!
