### ISSUE TITLE
January 25 - 29 - Add AI to your applications the easy way

### ISSUE THREAD

**Issue by mebaumb** [microsoft/ReactorPlanning#148]
# Event Information
| Category | Details |
|-----------|---------|
| Reactor Topic | AI Services |
| Monthly Topic (if applicable) | <Topic taken from [Azure Dev Marketing](https://aka.ms/DevEdCalFY21H1)> |
| Weekly Topic (if applicable) |  |
| Workshop Topic | AI |
| Workshop Duration | 60 Minutes | 
| Title | Add AI to your applications the easy way |
| Description | |

# Workshop(s) details
| Date |  Local Start Time |  Location |  Speaker | SharePoint ID | Platform |
|------|-------------------|-----------|----------|---------------|----------|
| Jan 26, 2021 | 6:30 PM | Bangalore | Avinash Mishra | 12484 |----------|
| Jan 26, 2021 | 4:00 PM | US/CA/AU | Andrew Schwartz | 12483|----------|
| Jan 27, 2021 | 7:30 PM | Sao Paulo | Flavio Figueiredo | 12487 |----------|
| Jan 27, 2021 | 7:30 PM | Shanghai | Ryan Chung | 12486 |----------|
| Jan 27, 2021 | 12:00 PM | EMEA | Andrew Schwartz | 12485 |----------|

# Event Checklist

## 10 Weeks Prior
- [x] Reactor Content Team (RCT) opens a new issue for an upcoming local workshop filling in the Event Information and Workshop details tables. RCT member who owns content (content owner) this week will be the assignee.
- [x] RCT and content owner discuss details of the event in the comments of this issue. RCT adds a _confirmed-event_ label and _local-digital-event_ tag to the issue and adds event to the __Local Digital Events__ project. Issue will appear in the __Upcoming Streams__ column
- [ ] RCT adds a _ready-for-marketing-edit_ label so the RCT can review title and description

## 8 Weeks Prior
- [ ] RCT does a review of title and description and removes the _ready-for-marketing-edit_ label 
- [ ] RCT moves the issue to the __Ready for SharePoint__ column
- [ ] RCT informs the Reactor Marketing Team of the new event information
- [ ] RCT confirms the speaker
- [ ] RCT provides speaker with assets (e.g. slides, overlays) and the survey data for the event
- [ ] RCT moves the issue to the __Content Preparation In Progress__ column

## 5 weeks Prior
- [ ] Content owner opens a PR with the new content for the workshop on the [customer-facing Reactor repository](https://github.com/microsoft/Reactors/tree/main/online-event-resources) and adds the _content-development_ and _local-digital-event_ tag to the PR. 
- [ ] RCT reviews, approves, and merges the changes
- [ ] RCT shares content with the vendor/instructor
- [ ] RCT provides vendor/instructor with assets (e.g. slides, overlays) and the survey data for the event
- [ ] RCT ensures that instructors have received an invite to the workshops and that PM team works with instructors to get setup in the platform (e.g. Teams, Teams Live Event)

## 1 Week Prior
- [ ] Connect vendor/instructor with the PM(s) for the locations where this event has been marketed
- [ ] Check-in with vendor/instructor that they are prepared for the workshop
- [ ] RCT moves the issue to the __Ready to Stream__ column

## During and After Stream
- [ ] Instructor (and optional moderator) run the stream
- [ ] _(Optional)_RCT submits recording to be uploaded to the Reactor YouTube and to be made available on LearnTV
- [ ] RCT moves issue to the __Stream Complete__ column

**Comment by mebaumb** [comment]
@meaghanlewis - Here is the old description:

Adding artificial intelligence to an application does not need to involve creating one's own models, powerful GPUs (graphics processing units), and terabytes of training data. In fact, it can be distilled down to a couple of API or REST calls with the right services - like Cognitive Services. Cognitive Services is a full suite of models available for you to call from existing (or newly created) applications, and includes the ability to detect text in pictures, translate text, and even provide sentiment analysis. We'll explore how you can take advantage of pre-built models, adding them to an application using Python. (Note: Python experience is assumed)

What is the session about?
Adding artificial intelligence to an application does not need to involve creating one's own models, using powerful processing computers, or large amounts of training data. In fact, it can be distilled down to a couple of API or REST calls with the right services - like Cognitive Services. Cognitive Services is a full suite of models available for you to call from existing or newly created applications, and includes the ability to detect text in pictures, translate text, and even provide sentiment analysis. We'll explore how you can take advantage of pre-built models, adding them to an application using Python.

Who is it aimed at?
This session is aimed at learners who want to learn about easy ways to add AI services to their applications by using cognitive services. While you can be a beginning developer, we will assume that you have some prior experience coding in Python.

Why should you attend?
This workshop will be a hands on opportunity to learn about Cognitive Services. We'll practice adding these pre-built models to existing applications and you'll leave with the understanding of how they work and the ability to do it to your own projects.

**Comment by meaghanlewis** [comment]
@mebaumb I made a few edits to the first and second sections. If those look okay to you, please feel free to go ahead and update in all the places accordingly.

Thanks for getting this abstract together 😄

**Comment by mebaumb** [comment]
This has been published without speaker data
