### ISSUE TITLE
Feb 1-5 - HTML/CSS

### ISSUE THREAD

**Issue by mebaumb** [microsoft/ReactorPlanning#149]
# Event Information
| Category | Details |
|-----------|---------|
| Reactor Topic | Coding, Languages, and Frameworks |
| Monthly Topic (if applicable) | <Topic taken from [Azure Dev Marketing](https://aka.ms/DevEdCalFY21H1)> |
| Weekly Topic (if applicable) |  |
| Workshop Topic | HTML/CSS |
| Workshop Duration | 60 Minutes | 
| Title | Getting started with HTML & CSS  |
| Description | What is the session about? If you’re interested in exploring creating websites, the most logical first step is learning the core components used to display   information in a browser. In this workshop you will start by getting hands on experience with HTML, and see how to use tags to identify certain sections of a page, and allow the user to enter information. You’ll then play with CSS, which will allow you to format the page’s content and determine where everything goes. Who is it aimed at? This session is for learners who are just beginning their web development journey and want to learn the basics of HTML and CSS. Why should you attend? This is a hands-on workshops where you will learn the basics of Web Development. If you're new to HTML and CSS this will give you the building blocks you need to build and design websites.|
| Content | https://github.com/microsoft/Reactors/tree/main/workshop-resources/web-development/Web_Fundamentals_1 |

# Workshop(s) details
| Date |  Local Start Time |  Location |  Speaker | SharePoint ID | Platform |
|------|-------------------|-----------|----------|---------------|----------|
| Feb 2, 2021 | 6:30 PM | Bangalore | Devendra Rawat | 12489 |----------|
| Feb 2, 2021 | 4:00 PM | US/CA/AU | | 12488 |----------|
| Feb 3, 2021 | 7:30 PM | Sao Paulo | Helder de Rocha | 12491 |----------|
| Feb 3, 2021 | 7:30 PM | Shanghai | Ryan Chung | 12492 |----------|
| Feb 3, 2021 | 12:00 PM | EMEA | Dana Wyatt | 12490 |----------|

# Event Checklist

## 10 Weeks Prior
- [ ] Reactor Content Team (RCT) opens a new issue for an upcoming local workshop filling in the Event Information and Workshop details tables. RCT member who owns content (content owner) this week will be the assignee.
- [ ] RCT and content owner discuss details of the event in the comments of this issue. RCT adds a _confirmed-event_ label and _local-digital-event_ tag to the issue and adds event to the __Local Digital Events__ project. Issue will appear in the __Upcoming Streams__ column
- [ ] RCT adds a _ready-for-marketing-edit_ label so the RCT can review title and description

## 8 Weeks Prior
- [ ] RCT does a review of title and description and removes the _ready-for-marketing-edit_ label 
- [ ] RCT moves the issue to the __Ready for SharePoint__ column
- [ ] RCT informs the Reactor Marketing Team of the new event information
- [ ] RCT confirms the speaker
- [ ] RCT provides speaker with assets (e.g. slides, overlays) and the survey data for the event
- [ ] RCT moves the issue to the __Content Preparation In Progress__ column

## 5 weeks Prior
- [ ] Content owner opens a PR with the new content for the workshop on the [customer-facing Reactor repository](https://github.com/microsoft/Reactors/tree/main/online-event-resources) and adds the _content-development_ and _local-digital-event_ tag to the PR. 
- [ ] RCT reviews, approves, and merges the changes
- [ ] RCT shares content with the vendor/instructor
- [ ] RCT provides vendor/instructor with assets (e.g. slides, overlays) and the survey data for the event
- [ ] RCT ensures that instructors have received an invite to the workshops and that PM team works with instructors to get setup in the platform (e.g. Teams, Teams Live Event)

## 1 Week Prior
- [ ] Connect vendor/instructor with the PM(s) for the locations where this event has been marketed
- [ ] Check-in with vendor/instructor that they are prepared for the workshop
- [ ] RCT moves the issue to the __Ready to Stream__ column

## During and After Stream
- [ ] Instructor (and optional moderator) run the stream
- [ ] _(Optional)_RCT submits recording to be uploaded to the Reactor YouTube and to be made available on LearnTV
- [ ] RCT moves issue to the __Stream Complete__ column

**Comment by mebaumb** [comment]
@meaghanlewis Here is the Old Abstract: 
"If you’re interested in exploring creating websites, the most logical first step is learning the core components used to display   information in a browser. In this 2 hour workshop you will start by getting hands on experience with HTML, and see how to use tags to identify certain sections of a page, and allow the user to enter information. You’ll then play with CSS, which will allow you to format the page’s content and determine where everything goes."

What is the session about?
If you’re interested in exploring how to create websites, the most logical first step is learning the core components used to display   information in a browser. In this workshop you will start by getting hands on experience with HTML, and see how to use tags to identify certain sections of a page, and allow the user to enter information. You’ll then play with CSS, which will allow you to format the page’s content and determine where everything goes.

Who is it aimed at?
This session is for learners who are just beginning their web development journey and want to learn the basics of HTML and CSS. 

Why should you attend?
This is a hands-on workshops where you will learn the basics of Web Development. If you're new to HTML and CSS this will give you the building blocks you need to build and design websites.

**Comment by meaghanlewis** [comment]
@mebaumb sorry it took me a while to respond to this. The abstract looks good to me!

**Comment by mebaumb** [comment]
This was published on Dynamics/Meetup on 12/11
