### ISSUE TITLE
Feb 8 - 12 - JavaScript

### ISSUE THREAD

**Issue by mebaumb** [microsoft/ReactorPlanning#150]
# Event Information
| Category | Details |
|-----------|---------|
| Reactor Topic | Coding, Languages, and Frameworks |
| Monthly Topic (if applicable) | <Topic taken from [Azure Dev Marketing](https://aka.ms/DevEdCalFY21H1)> |
| Weekly Topic (if applicable) |  |
| Workshop Topic | JavaScript |
| Workshop Duration | 60 Minutes | 
| Title | Getting Started with JavaScript |
| Description | What is the session about? If you want to start programming for the web, one language you’ll need to have in your toolbelt is JavaScript. JavaScript is the industry standard for web development. With the use of JavaScript, you can make your pages dynamic and interactive. In this workshop, you’ll get started by walking through the core syntax and functionality. Then you'll learn about libraries and frameworks which can help make your life as a developer easier. Who is it aimed at? This beginners workshop is for learners who are new to Javascript and want to use it for web development. Why should you attend? This workshop is a great hands-on opportunity to learn how to get started with JavaScript and to leverage it to make your web pages more dynamic. You'll leave this workshop with the skills and tools needed to implement this in your own projects. |
| Content | https://github.com/microsoft/Reactors/tree/main/workshop-resources/web-development/Web_Fundamentals_2/3_Javascript |

# Workshop(s) details
| Date |  Local Start Time |  Location |  Speaker | SharePoint ID | Platform |
|------|-------------------|-----------|----------|---------------|----------|
| Feb 9, 2021 | 6:30 PM | Bangalore | Devendra Rawat | 12494 |----------|
| Feb 9, 2021 | 4:00 PM | US/CA/AU | | 12493 |----------|
| Feb 10, 2021 | 7:30 PM | Sao Paulo | Helder de Rocha | 12497 |----------|
| Feb 10, 2021 | 7:30 PM | Shanghai | Ryan Chung | 12498 |----------|
| Feb 10, 2021 | 12:00 PM | EMEA | Dana Wyatt | 12496 |----------|

# Event Checklist

## 10 Weeks Prior
- [ ] Reactor Content Team (RCT) opens a new issue for an upcoming local workshop filling in the Event Information and Workshop details tables. RCT member who owns content (content owner) this week will be the assignee.
- [ ] RCT and content owner discuss details of the event in the comments of this issue. RCT adds a _confirmed-event_ label and _local-digital-event_ tag to the issue and adds event to the __Local Digital Events__ project. Issue will appear in the __Upcoming Streams__ column
- [ ] RCT adds a _ready-for-marketing-edit_ label so the RCT can review title and description

## 8 Weeks Prior
- [ ] RCT does a review of title and description and removes the _ready-for-marketing-edit_ label 
- [ ] RCT moves the issue to the __Ready for SharePoint__ column
- [ ] RCT informs the Reactor Marketing Team of the new event information
- [ ] RCT confirms the speaker
- [ ] RCT provides speaker with assets (e.g. slides, overlays) and the survey data for the event
- [ ] RCT moves the issue to the __Content Preparation In Progress__ column

## 5 weeks Prior
- [ ] Content owner opens a PR with the new content for the workshop on the [customer-facing Reactor repository](https://github.com/microsoft/Reactors/tree/main/online-event-resources) and adds the _content-development_ and _local-digital-event_ tag to the PR. 
- [ ] RCT reviews, approves, and merges the changes
- [ ] RCT shares content with the vendor/instructor
- [ ] RCT provides vendor/instructor with assets (e.g. slides, overlays) and the survey data for the event
- [ ] RCT ensures that instructors have received an invite to the workshops and that PM team works with instructors to get setup in the platform (e.g. Teams, Teams Live Event)

## 1 Week Prior
- [ ] Connect vendor/instructor with the PM(s) for the locations where this event has been marketed
- [ ] Check-in with vendor/instructor that they are prepared for the workshop
- [ ] RCT moves the issue to the __Ready to Stream__ column

## During and After Stream
- [ ] Instructor (and optional moderator) run the stream
- [ ] _(Optional)_RCT submits recording to be uploaded to the Reactor YouTube and to be made available on LearnTV
- [ ] RCT moves issue to the __Stream Complete__ column

**Comment by mebaumb** [comment]
@meaghanlewis - Here is the old abstract: 
"If you want to start programming for the web, one language you’ll need to have in your toolbelt is JavaScript. JavaScript is the lingua franca of the web. With the use of JavaScript you can make your pages dynamic and interactive. In this 2 hour workshop you’ll see how to get started with JavaScript, walk through the core syntax and functionality. You’ll also gain experience with libraries and frameworks which can help make your life as a developer easier. "

Here is my re-write in the new template:
What is the session about?
If you want to start programming for the web, one language you’ll need to have in your toolbelt is JavaScript. JavaScript is the industry standard for web development. With the use of JavaScript, you can make your pages dynamic and interactive. In this workshop, you’ll get started by walking through the core syntax and functionality. Then you'll learn about libraries and frameworks which can help make your life as a developer easier.

Who is it aimed at?
This beginners workshop is for learners who are new to Javascript and want to use it for web development.

Why should you attend?
This workshop is a great hands-on opportunity to learn how to get started with JavaScript and to leverage it to make your web pages more dynamic. You'll leave this workshop with the skills and tools needed to implement this in your own projects.

**Comment by meaghanlewis** [comment]
@mebaumb made a few edits inline to your abstract. It looks good to go to me!

**Comment by mebaumb** [comment]
This event has been published in all the locations!
