### ISSUE TITLE
Feb 15 - 22 - Build continuous integration (CI) workflows by using GitHub Actions

### ISSUE THREAD

**Issue by mebaumb** [microsoft/ReactorPlanning#151]
# Event Information
| Category | Details |
|-----------|---------|
| Reactor Topic | DevOps and Dev Tools |
| Monthly Topic (if applicable) | <Topic taken from [Azure Dev Marketing](https://aka.ms/DevEdCalFY21H1)> |
| Weekly Topic (if applicable) |  |
| Workshop Topic | Github Actions |
| Workshop Duration | 60 Minutes | 
| Title | Build continuous integration (CI) workflows by using GitHub Actions |
| Description | |
| Content | https://docs.microsoft.com/learn/modules/github-actions-ci/ |
# Workshop(s) details
| Date |  Local Start Time |  Location |  Speaker | SharePoint ID | Platform |
|------|-------------------|-----------|----------|---------------|----------|
| Feb 16, 2021 | 6:30 PM | Bangalore |  | 12500 |----------|
| Feb 16, 2021 | 4:00 PM | US/CA/AU |  | 12499 |----------|
| Feb 17, 2021 | 7:30 PM | Sao Paulo |  | 12503 |----------|
| Feb 17, 2021 | 7:30 PM | Shanghai |  | 12502 |----------|
| Feb 17, 2021 | 12:00 PM | EMEA |  | 12501 |----------|

# Event Checklist

## 10 Weeks Prior
- [ ] Reactor Content Team (RCT) opens a new issue for an upcoming local workshop filling in the Event Information and Workshop details tables. RCT member who owns content (content owner) this week will be the assignee.
- [ ] RCT and content owner discuss details of the event in the comments of this issue. RCT adds a _confirmed-event_ label and _local-digital-event_ tag to the issue and adds event to the __Local Digital Events__ project. Issue will appear in the __Upcoming Streams__ column
- [ ] RCT adds a _ready-for-marketing-edit_ label so the RCT can review title and description

## 8 Weeks Prior
- [ ] RCT does a review of title and description and removes the _ready-for-marketing-edit_ label 
- [ ] RCT moves the issue to the __Ready for SharePoint__ column
- [ ] RCT informs the Reactor Marketing Team of the new event information
- [ ] RCT confirms the speaker
- [ ] RCT provides speaker with assets (e.g. slides, overlays) and the survey data for the event
- [ ] RCT moves the issue to the __Content Preparation In Progress__ column

## 5 weeks Prior
- [ ] Content owner opens a PR with the new content for the workshop on the [customer-facing Reactor repository](https://github.com/microsoft/Reactors/tree/main/online-event-resources) and adds the _content-development_ and _local-digital-event_ tag to the PR. 
- [ ] RCT reviews, approves, and merges the changes
- [ ] RCT shares content with the vendor/instructor
- [ ] RCT provides vendor/instructor with assets (e.g. slides, overlays) and the survey data for the event
- [ ] RCT ensures that instructors have received an invite to the workshops and that PM team works with instructors to get setup in the platform (e.g. Teams, Teams Live Event)

## 1 Week Prior
- [ ] Connect vendor/instructor with the PM(s) for the locations where this event has been marketed
- [ ] Check-in with vendor/instructor that they are prepared for the workshop
- [ ] RCT moves the issue to the __Ready to Stream__ column

## During and After Stream
- [ ] Instructor (and optional moderator) run the stream
- [ ] _(Optional)_RCT submits recording to be uploaded to the Reactor YouTube and to be made available on LearnTV
- [ ] RCT moves issue to the __Stream Complete__ column

**Comment by mebaumb** [comment]
@meaghanlewis - I found these past workshops I am not sure if it is continuous integration though:
[Event ID: 7995] GitHub is no longer just a place to store your code. That’s a good thing, because the work doesn't end after code has been pushed or merged. There are unit tests to execute, linting to run, and deployments to push. With GitHub Actions, you can perform any of these activities based on the events you define. Join us in this session for a conversation on GitHub Actions and take your repositories to the next level.

[Event ID: 11629] GitHub Actions automate many development cycle tasks like and executing unit tests, running linting, and pushing deployments to Azure. In this workshop, you'll become familiar with GitHub Actions by automating some of these tasks and workflows.

not sure if either of these are the same workshop or if we need to create a new description.

**Comment by meaghanlewis** [comment]
@mebaumb I don't think we've had this exact workshop topic before. Here's my take at anabstract:

What is this session about?
Continuous Integration (CI) is the practice of merging developer's work to a shared repository several times a day. Each new merge is verified by automated builds and tests, allowing a team to work confidently knowing their code is error free. In this workshop, learn how to create workflows that enable you to use CI for your projects by using GitHub Actions. You'll go through an exercise to create a CI workflow, debug and test a Node.js app, and then customize and optimize your workflow with GitHub Actions.

Who is it aimed at?
This workshop is aimed at developers, DevOps engineers, students, and GitHub enthusiasts. It is recommended that you be familiar with GitHub and have an idea of how GitHub Actions can help optimize development workflows.

Why should you attend?
You should attend this workshop if you want to get more familiar with CI and GitHub Actions and learn how to create these workflows for your own development projects.

**Comment by mebaumb** [comment]
@meaghanlewis  I added a bit of text about CI. LMK what you think - is this beginner or intermediate content?

**Comment by meaghanlewis** [comment]
@mebaumb alright if I re-write that slightly? I didn't like the word "mainline" since that's not a term commonly used.

_Continuous Integration (CI) is the practice of merging developer's work to a shared repository several times a day. Each new merge is verified by automated builds and tests, allowing a team to work confidently knowing their code is error free._

**Comment by mebaumb** [comment]
@meaghanlewis - please edit away! :) If you're happy with it, we can publish - otherwise if you'd like to tweak it a bit that's fine too! 

Just let me know. :)

**Comment by meaghanlewis** [comment]
Oh, and I'd say this is intermediate content.

**Comment by mebaumb** [comment]
@meaghanlewis  - is this good to publish with the edit that you made above?

**Comment by meaghanlewis** [comment]
Yes, it's good to go! Sorry I forgot to come back to this one!

**Comment by meaghanlewis** [comment]
Here's an overview of what this workshop will cover and suggested agenda to follow with links and resources.

## Content to teach
This workshop will take Reactor community members through this module: [Build CI workflows by using GitHub Actions](http://aka.ms/BuildCIWorkflows-8)

**SHARE THIS LINK WITH REACTOR ATTENDEES: http://aka.ms/BuildCIWorkflows-8** (this is for tracking purposes. please do not share the direct link to the Learn module)

**Encourage attendees to go through the module with you and complete it. Also encourage them to rate the module at the end.**

## Agenda
1. **Intro/Overview** 2 min
   - Welcome community members
   - Provide overview of content to be covered
   - Show the module
   - Encourage community members to complete and rate the modules as they go along
     -  Mention that there are other modules in this learning path they can complete in their own time: https://aka.ms/AutomateWorkflowGitActions-8 
   - Make sure community members are aware of the pre-reqs:
      - A GitHub account
      - The ability to navigate and edit files in GitHub
      - Basic familiarity with GitHub Actions and workflows
2. **[Introduction](https://docs.microsoft.com/en-us/learn/modules/github-actions-ci/1-introduction)** 5 min
   - Provide an overview of Actions
     - Features: https://github.com/features/actions
     - Docs: https://docs.github.com/en/free-pro-team@latest/actions
     - Repos: https://github.com/actions
       - Show off a few actions from here 
3. **[How do I use GitHub Actions to create workflows for CI](https://docs.microsoft.com/en-us/learn/modules/github-actions-ci/2-github-actions-workflows-ci)** 10 min
   - Demo how to:
     -  Create a workflow from a template
     - Action logs for the build
     - Customize workflow templates
     - Store artifacts
     - Automate reviews
4. **[Create the CI workflow on GitHub](https://docs.microsoft.com/en-us/learn/modules/github-actions-ci/3-exercise-ci-workflow-github)** 40 min
   - Demo how to start the learning lab and walk through each step to use CI with GitHub Actions, and create a Tic Tac Toe game
5. **Closing** 3 min
    - Walk through [knowledge check questions](https://docs.microsoft.com/en-us/learn/modules/github-actions-ci/4-knowledge-check)
    - Q&A
    - **Ask attendees to take the survey: https://aka.ms/Reactor/Survey**
      - Note: The event code is listed in this issue description and/or your Reactor contact can share that with the community members during the workshop
    - Share any helpful resources
      - https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions
