### ISSUE TITLE
February 22 - 29 - Publish a Blazor WebAssembly app with Azure Static Web Apps

### ISSUE THREAD

**Issue by mebaumb** [microsoft/ReactorPlanning#152]
# Event Information
| Category | Details |
|-----------|---------|
| Reactor Topic | Coding, Languages, and Frameworks |
| Monthly Topic (if applicable) | <Topic taken from [Azure Dev Marketing](https://aka.ms/DevEdCalFY21H1)> |
| Weekly Topic (if applicable) |  |
| Workshop Topic | ASWA |
| Workshop Duration | 60 Minutes | 
| Title | Publish a Blazor WebAssembly app with Azure Static Web Apps |
| Description | |
| Content | https://docs.microsoft.com/learn/modules/publish-app-service-static-web-app-api-dotnet/ |

# Workshop(s) details
| Date |  Local Start Time |  Location |  Speaker | SharePoint ID | Platform |
|------|-------------------|-----------|----------|---------------|----------|
| Feb 23, 2021 | 6:30 PM | Bangalore |  | 12505 |----------|
| Feb 23, 2021 | 4:00 PM | US/CA/AU |  | 12504 |----------|
| Feb 24, 2021 | 7:30 PM | Sao Paulo |  | 12507 |----------|
| Feb 24, 2021 | 7:30 PM | Shanghai |  | 12508 |----------|
| Feb 24, 2021 | 12:00 PM | EMEA |  | 12506 |----------|

# Event Checklist

## 10 Weeks Prior
- [ ] Reactor Content Team (RCT) opens a new issue for an upcoming local workshop filling in the Event Information and Workshop details tables. RCT member who owns content (content owner) this week will be the assignee.
- [ ] RCT and content owner discuss details of the event in the comments of this issue. RCT adds a _confirmed-event_ label and _local-digital-event_ tag to the issue and adds event to the __Local Digital Events__ project. Issue will appear in the __Upcoming Streams__ column
- [ ] RCT adds a _ready-for-marketing-edit_ label so the RCT can review title and description

## 8 Weeks Prior
- [ ] RCT does a review of title and description and removes the _ready-for-marketing-edit_ label 
- [ ] RCT moves the issue to the __Ready for SharePoint__ column
- [ ] RCT informs the Reactor Marketing Team of the new event information
- [ ] RCT confirms the speaker
- [ ] RCT provides speaker with assets (e.g. slides, overlays) and the survey data for the event
- [ ] RCT moves the issue to the __Content Preparation In Progress__ column

## 5 weeks Prior
- [ ] Content owner opens a PR with the new content for the workshop on the [customer-facing Reactor repository](https://github.com/microsoft/Reactors/tree/main/online-event-resources) and adds the _content-development_ and _local-digital-event_ tag to the PR. 
- [ ] RCT reviews, approves, and merges the changes
- [ ] RCT shares content with the vendor/instructor
- [ ] RCT provides vendor/instructor with assets (e.g. slides, overlays) and the survey data for the event
- [ ] RCT ensures that instructors have received an invite to the workshops and that PM team works with instructors to get setup in the platform (e.g. Teams, Teams Live Event)

## 1 Week Prior
- [ ] Connect vendor/instructor with the PM(s) for the locations where this event has been marketed
- [ ] Check-in with vendor/instructor that they are prepared for the workshop
- [ ] RCT moves the issue to the __Ready to Stream__ column

## During and After Stream
- [ ] Instructor (and optional moderator) run the stream
- [ ] _(Optional)_RCT submits recording to be uploaded to the Reactor YouTube and to be made available on LearnTV
- [ ] RCT moves issue to the __Stream Complete__ column

**Comment by mebaumb** [comment]
@meaghanlewis - Found this previous workshop, we may need to update it a bit to talk about Blazor WebAssembly App

[Event ID: 7846] Most developers want to focus on writing code. At the same time, they need deployment to be seamless, server architecture to be invisible, and scaling to be automatic. Enter Azure Static Web Apps. This (currently in preview) service enables you to write your client-side code using the framework you love, create back-end code using any language you prefer, and employ GitHub and Azure to take care of the rest! Join this session to see how you can use Azure Static Web Apps for easier dynamic web development.

**Comment by meaghanlewis** [comment]
@mebaumb here's my first take at the abstract for this workshop:

What is this session about?
_Blazor is a feature of ASP.Net that allows you to, among other things, build robust and interactive Web User Interfaces (UI) using C# instead of Javascript, right from your browser._ In this workshop, you'll deploy and update a Blazor web application and its API with Azure Static Web Apps. You will start with cloning and running an existing Blazor web app locally, then create an API for the app with Azure Functions, and end with publishing the app and API to Azure Static Web Apps.

Who is it aimed at?
This workshop is for web developer and those interested in web development who want to learn about Azure Statics Web Apps for easy and seamless deployment of their apps. To attend this workshop, you should have a basic knowledge of wen app concepts, an Azure account, and a GitHub account. You should also have Visual Studio installed.

Why should you attend?
You should attend if you want to learn more about Azure Static Web Apps and Blazor, so that you can build and deploy full stack web apps with .NET.

**Comment by mebaumb** [comment]
I added a piece about what Blazor is, LMK your thoughts :) 

Is this an intermediate or beginner workshop?

**Comment by meaghanlewis** [comment]
That edit looks good to me! Let's call this an intermediate workshop.

**Comment by meaghanlewis** [comment]
## Content to teach
This workshop will take Reactor community members through this module: [Publish a Blazor WebAssembly app with Azure Static Web Apps](https://aka.ms/BlazorWebAssembly-8)

**SHARE THIS LINK WITH REACTOR ATTENDEES: https://aka.ms/BlazorWebAssembly-8** (this is for tracking purposes. please do not share the direct link to the Learn module)

**Encourage attendees to go through the module with you and complete it. Also encourage them to rate the module at the end.**

## Agenda
1. **Intro/Overview** 5 min
   - Welcome community members
   - Provide overview of content to be covered
   - Encourage community members to complete and rate the module at the end
   - Make sure community members are aware of the pre-reqs:
     - Basic knowledge of web app concepts
     - C# .NET experience at a beginner level
     - A GitHub account
     - [Visual Studio 2019 (or newer)](https://visualstudio.microsoft.com/vs/)
2. **[Introduction](https://docs.microsoft.com/en-us/learn/modules/publish-app-service-static-web-app-api-dotnet/1-introduction)** 5 min
   - Overview of Azure Static Web Apps
     - https://azure.microsoft.com/services/app-service/static/
   - Review learning objectives and tasks for workshop
3. **[Get started with the exercise](https://docs.microsoft.com/en-us/learn/modules/publish-app-service-static-web-app-api-dotnet/2-exercise-get-started)** 3 min
   - Create a GitHub repository
   - Run your app
   - Browser to your app
4. **[Plan your Azure Static Web App](https://docs.microsoft.com/en-us/learn/modules/publish-app-service-static-web-app-api-dotnet/3-static-web-apps)** 3 min
   - Connect your static web apps instance to GitHub
5. **[Create an Azure Static Web App](https://docs.microsoft.com/en-us/learn/modules/publish-app-service-static-web-app-api-dotnet/4-exercise-static-web-apps)** 5 min
   - Create the app
   - Configure the app
   - Review the GitHub Action
   - View website
6. **[Create fallback routes](https://docs.microsoft.com/en-us/learn/modules/publish-app-service-static-web-app-api-dotnet/6-exercise-fallback-routes)** 6 min
   - Configure fallback routes
   - Pull code
   - Create a routing file
   - Push changes
   - Try the fallback routes
7. **[Build an API with Azure Functions](https://docs.microsoft.com/en-us/learn/modules/publish-app-service-static-web-app-api-dotnet/7-build-api)** 3 min
   - Create an API for the web app
   - Preview changes
   - Configure communication between the app and API
8. **[Create an Azure Functions project](https://docs.microsoft.com/en-us/learn/modules/publish-app-service-static-web-app-api-dotnet/8-exercise-function-app)** 6 min
9. **[Publish the API with GitHub Actions](https://docs.microsoft.com/en-us/learn/modules/publish-app-service-static-web-app-api-dotnet/9-action)** 7 min
   - Configure GitHub Actions
   - Trigger the action
   - Push changes to GitHub
   - Create a pull request
   - Publish
10. **Closing** 5 min
    - Walk through [knowledge check questions and answers](https://docs.microsoft.com/en-us/learn/modules/publish-app-service-static-web-app-api-dotnet/11-knowledge-check)
    - [Provide a summary](https://docs.microsoft.com/en-us/learn/modules/publish-app-service-static-web-app-api-dotnet/12-summary)
    - Q&A
    - **IMPORTANT: Ask attendees to take the survey: https://aka.ms/Reactor/Survey**
      - Note: The event code is listed in this issue description and/or your Reactor contact can share that with the community members during the workshop
    - Share any helpful resources
      - [Azure Static Web Apps on Microsoft Docs](https://docs.microsoft.com/en-us/azure/static-web-apps)
      - [Blazor website](https://dotnet.microsoft.com/apps/aspnet/web-apps/blazor)

**Comment by mebaumb** [comment]
Based on the conversation, what do you think about this (updated "who is it aimed at"):
@meaghanlewis  
What is this session about?
Blazor is a feature of ASP.Net that allows you to, among other things, build robust and interactive Web User Interfaces (UI) using C# instead of Javascript, right from your browser. In this workshop, you'll deploy and update a Blazor web application and its API with Azure Static Web Apps. You will start with cloning and running an existing Blazor web app locally, then create an API for the app with Azure Functions, and end with publishing the app and API to Azure Static Web Apps.

Who is it aimed at?
This workshop is for web developer and those interested in web development who want to learn about Azure Statics Web Apps for easy and seamless deployment of their apps. To attend this workshop, you should have a basic knowledge of wen app concepts, an Azure account, and a GitHub account. You should also have either Visual Studio or VS Code installed.

Why should you attend?
You should attend if you want to learn more about Azure Static Web Apps and Blazor, so that you can build and deploy full stack web apps with .NET.

**Comment by meaghanlewis** [comment]
Thanks @mebaumb! Updated you edit slightly. This looks good to go.
