### ISSUE TITLE
March 1-5 - Rust: understand common concepts

### ISSUE THREAD

**Issue by mebaumb** [microsoft/ReactorPlanning#153]
# Event Information
| Category | Details |
|-----------|---------|
| Reactor Topic | Coding, Languages, and Frameworks |
| Monthly Topic (if applicable) | <Topic taken from [Azure Dev Marketing](https://aka.ms/DevEdCalFY21H1)> |
| Weekly Topic (if applicable) |  |
| Workshop Topic | Rust |
| Workshop Duration | 60 Minutes | 
| Title | Rust: Understand common concepts |
| Description | What is this session about? Rust is a reliable and efficient programming language that developers use for everything from web development to networking to embedded devices. In this workshop we'll focus on an introduction to programming with Rust. We'll learn about common programming language concepts like variables, data types, and functions, and show how they work in Rust. This session will teach the foundations of how to use these concepts in Rust programs and give you experience and confidence to start building your own programs. This is the first session of a 2 part mini series. Who is it aimed at? This workshop is aimed at developers who want to learn about Rust. No prior experience with Rust is needed, although it will be helpful it you have experience with coding in another programming language. Why should you attend? You should attend this workshop if you want to get more familiar with Rust topics including: variables, data types, functions, collection types, and control flow. |
| Content | https://docs.microsoft.com/learn/modules/rust-understand-common-concepts/ |

# Workshop(s) details
| Date |  Local Start Time |  Location |  Speaker | SharePoint ID | Platform |
|------|-------------------|-----------|----------|---------------|----------|
| March 2, 2021 | 6:30 PM | Bangalore |  | 12510 |----------|
| March 2, 2021 | 4:00 PM | US/CA/AU |  | 12509 |----------|
| March 3, 2021 | 7:30 PM | Sao Paulo |  | 12512 |----------|
| March 3, 2021 | 7:30 PM | Shanghai |  | 12513 |----------|
|  March 3, 2021 | 12:00 PM | EMEA |  | 12511 |----------|

# Event Checklist

## 10 Weeks Prior
- [ ] Reactor Content Team (RCT) opens a new issue for an upcoming local workshop filling in the Event Information and Workshop details tables. RCT member who owns content (content owner) this week will be the assignee.
- [ ] RCT and content owner discuss details of the event in the comments of this issue. RCT adds a _confirmed-event_ label and _local-digital-event_ tag to the issue and adds event to the __Local Digital Events__ project. Issue will appear in the __Upcoming Streams__ column
- [ ] RCT adds a _ready-for-marketing-edit_ label so the RCT can review title and description

## 8 Weeks Prior
- [ ] RCT does a review of title and description and removes the _ready-for-marketing-edit_ label 
- [ ] RCT moves the issue to the __Ready for SharePoint__ column
- [ ] RCT informs the Reactor Marketing Team of the new event information
- [ ] RCT confirms the speaker
- [ ] RCT provides speaker with assets (e.g. slides, overlays) and the survey data for the event
- [ ] RCT moves the issue to the __Content Preparation In Progress__ column

## 5 weeks Prior
- [ ] Content owner opens a PR with the new content for the workshop on the [customer-facing Reactor repository](https://github.com/microsoft/Reactors/tree/main/online-event-resources) and adds the _content-development_ and _local-digital-event_ tag to the PR. 
- [ ] RCT reviews, approves, and merges the changes
- [ ] RCT shares content with the vendor/instructor
- [ ] RCT provides vendor/instructor with assets (e.g. slides, overlays) and the survey data for the event
- [ ] RCT ensures that instructors have received an invite to the workshops and that PM team works with instructors to get setup in the platform (e.g. Teams, Teams Live Event)

## 1 Week Prior
- [ ] Connect vendor/instructor with the PM(s) for the locations where this event has been marketed
- [ ] Check-in with vendor/instructor that they are prepared for the workshop
- [ ] RCT moves the issue to the __Ready to Stream__ column

## During and After Stream
- [ ] Instructor (and optional moderator) run the stream
- [ ] _(Optional)_RCT submits recording to be uploaded to the Reactor YouTube and to be made available on LearnTV
- [ ] RCT moves issue to the __Stream Complete__ column

**Comment by meaghanlewis** [comment]
@mebaumb first pass at an abstract for Rust week 1.

What is this session about?
Rust is a reliable and efficient programming language that developers use for everything from web development to networking to embedded devices. In this workshop we'll focus on an introduction to programming with Rust. We'll learn about common programming language concepts like variables, data types, and functions, and show how they work in Rust. This session will teach the foundations of how to use these concepts in Rust programs and give you experience and confidence to start building your own programs. This is the first session of a 2 part mini series. 

Who is it aimed at?
This workshop is aimed at developers who want to learn about Rust. No prior experience with Rust is needed, although it will be helpful it you have experience with coding in another programming language.

Why should you attend?
You should attend this workshop if you want to get more familiar with Rust topics including: variables, data types, functions, collection types, and control flow.

**Comment by mebaumb** [comment]
@meaghanlewis - 1st edit done, let me know what you think!

**Comment by meaghanlewis** [comment]
Thanks @mebaumb! I made a couple other slight inline edits. The last thing I'm wondering if we should indicate if this is a series?

**Comment by mebaumb** [comment]
@meaghanlewis  - I think that we should, I added a line in the comment, let me know what you think!

**Comment by meaghanlewis** [comment]
@mebaumb the edit looks good to me. thanks!

**Comment by mebaumb** [comment]
This has been published!

**Comment by meaghanlewis** [comment]
## Instructor Notes

**Please share this link with attendees to follow along: https://aka.ms/RustConcepts-8**.  

This workshop will cover the following:
- Variables
- Data types: numbers, booleans, characters, strings, tuples
- Structs
- Enums
- Functions
- Collection types: arrays, vectors, hash maps
- Control flow: if/else, loop, while, for

Recommendations for going through the content:
- Use the Rust Playground for demonstrating code writing and execution. There  are links provided for most examples like this one about variables: https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=723a1c9bd36161c3cfc056f572ed9c11%3Fazure-portal%3Dtrue
- Try to spend as much time in the playground as possible, explaining concepts there, and less time actually walking through and showing the Learn module
- I know that is kind of a lot of content to fit in one hour. It means you can't spend more than 5-10 minutes on each topic. 
  - Please encourage attendees to do the examples with you and then complete the exercises on their own later and revisit the content as needed to reinforce their learning

Wrapping up:
-  At the end of the workshop, ask attendees to complete the knowledge check and summary so they can get a badge for completing the module. 
- Also please encourage them to rate the module please 😄
- Share out the survey link: https://aka.ms/Reactor/Survey with the event code (the Reactor contact on the call can give you this)
