### ISSUE TITLE
March 8 - 12 - Learn about error handling in Rust

### ISSUE THREAD

**Issue by mebaumb** [microsoft/ReactorPlanning#154]
# Event Information
| Category | Details |
|-----------|---------|
| Reactor Topic | Coding, Languages, and Frameworks |
| Monthly Topic (if applicable) | <Topic taken from [Azure Dev Marketing](https://aka.ms/DevEdCalFY21H1)> |
| Weekly Topic (if applicable) |  |
| Workshop Topic | Rust |
| Workshop Duration | 60 Minutes | 
| Title | Learn about error handling in Rust  |
| Description | What is this session about? Error handling is the process of anticipating and working with the possibility of failure. For example, a program's failure to read a file, followed by its continuing use of that bad input, would cause problematic errors. Your ability to notice and manage errors can save the program from additional pitfalls. In this session, you will learn about the ways to deal with errors in Rust using panic!, Option and Result. With this knowledge you'll be able to identify and resolve possible errors with confidence. This is part 2 of 2 of our Rust mini series. Who is it aimed at? This workshop is aimed at developers who want to learn about how to program in Rust. This is a beginner's session, although some knowledge of basic concepts in Rust is needed to best follow along. Why should you attend? You should attend this workshop if you want to get more familiar with how to write programs in Rust that can anticipate and recover from errors. |
| Content | https://docs.microsoft.com/learn/modules/rust-error-handling/ |

# Workshop(s) details
| Date |  Local Start Time |  Location |  Speaker | SharePoint ID | Platform |
|------|-------------------|-----------|----------|---------------|----------|
| March 9, 2021 | 6:30 PM | Bangalore |----------|12515 |----------|
| March 9, 2021 | 4:00 PM | US/CA/AU |----------| 12514 |----------|
| March 10, 2021 | 7:30 PM | Sao Paulo |----------| 12518 |----------|
| March 10, 2021 | 7:30 PM | Shanghai |----------| 12517 |----------|
|  March 10, 2021 | 12:00 PM | EMEA |----------| 12516 |----------|

# Event Checklist

## 10 Weeks Prior
- [ ] Reactor Content Team (RCT) opens a new issue for an upcoming local workshop filling in the Event Information and Workshop details tables. RCT member who owns content (content owner) this week will be the assignee.
- [ ] RCT and content owner discuss details of the event in the comments of this issue. RCT adds a _confirmed-event_ label and _local-digital-event_ tag to the issue and adds event to the __Local Digital Events__ project. Issue will appear in the __Upcoming Streams__ column
- [ ] RCT adds a _ready-for-marketing-edit_ label so the RCT can review title and description

## 8 Weeks Prior
- [ ] RCT does a review of title and description and removes the _ready-for-marketing-edit_ label 
- [ ] RCT moves the issue to the __Ready for SharePoint__ column
- [ ] RCT informs the Reactor Marketing Team of the new event information
- [ ] RCT confirms the speaker
- [ ] RCT provides speaker with assets (e.g. slides, overlays) and the survey data for the event
- [ ] RCT moves the issue to the __Content Preparation In Progress__ column

## 5 weeks Prior
- [ ] Content owner opens a PR with the new content for the workshop on the [customer-facing Reactor repository](https://github.com/microsoft/Reactors/tree/main/online-event-resources) and adds the _content-development_ and _local-digital-event_ tag to the PR. 
- [ ] RCT reviews, approves, and merges the changes
- [ ] RCT shares content with the vendor/instructor
- [ ] RCT provides vendor/instructor with assets (e.g. slides, overlays) and the survey data for the event
- [ ] RCT ensures that instructors have received an invite to the workshops and that PM team works with instructors to get setup in the platform (e.g. Teams, Teams Live Event)

## 1 Week Prior
- [ ] Connect vendor/instructor with the PM(s) for the locations where this event has been marketed
- [ ] Check-in with vendor/instructor that they are prepared for the workshop
- [ ] RCT moves the issue to the __Ready to Stream__ column

## During and After Stream
- [ ] Instructor (and optional moderator) run the stream
- [ ] _(Optional)_RCT submits recording to be uploaded to the Reactor YouTube and to be made available on LearnTV
- [ ] RCT moves issue to the __Stream Complete__ column

**Comment by meaghanlewis** [comment]
@mebaumb take 1 at an abstract for this session.

What is this session about?
Error handling is the process of anticipating and working with the possibility of failure. For example, a program's failure to read a file, followed by its continuing use of that bad input, would cause problematic errors. Your ability to notice and manage errors can save the program from additional pitfalls. In this session, you will learn about the ways to deal with errors in Rust using panic!, Option and Result. With this knowledge you'll be able to identify and resolve possible errors with confidence. This is part 2 of 2 of our Rust mini series.

Who is it aimed at?
This workshop is aimed at developers who want to learn about how to program in Rust. This is a beginner's session, although some knowledge of basic concepts in Rust is needed to best follow along.

Why should you attend?
You should attend this workshop if you want to get more familiar with how to write programs in Rust that can anticipate and recover from errors.

**Comment by mebaumb** [comment]
@meaghanlewis - a quick revision, let me know your thoughts!

**Comment by mebaumb** [comment]
@meaghanlewis  - updated this one to add part 2 of 2. please let me know your thoughts!

**Comment by meaghanlewis** [comment]
Looks good to go to me @mebaumb!

**Comment by mebaumb** [comment]
This has been published!

**Comment by meaghanlewis** [comment]
## Instructor notes

**Please share this link with attendees to follow along: https://aka.ms/RustErrors-8**. 

This workshop covers how to:
- Use panic! to deal with unrecoverable errors.
- Use the Option enum when a value is optional or the lack of a value is not an error condition.
- Use the Result enum when things could go wrong and a caller might have to deal with the problem.

Recommendations for walking through the content:
- Use the Rust Playground for all code examples: https://play.rust-lang.org/
- You should have enough time to go through each unit
- For the exercises, try to give attendees a few minutes to solve them on their own
- Try to spend as much time in the playground as possible, explaining concepts there, and less time actually walking through and showing the Learn module


Wrapping up:
-  At the end of the workshop, ask attendees to complete the knowledge check and summary so they can get a badge for completing the module. 
- Also please encourage them to rate the module please 😄
- Share out the survey link: https://aka.ms/Reactor/Survey with the event code (the Reactor contact on the call can give you this)

**Comment by mebaumb** [comment]
Events run and stream data recorded
