### ISSUE TITLE
March 15 -19 - Get started with Go

### ISSUE THREAD

**Issue by mebaumb** [microsoft/ReactorPlanning#155]
# Event Information
| Category | Details |
|-----------|---------|
| Reactor Topic | Coding, Languages, and Frameworks |
| Monthly Topic (if applicable) | <Topic taken from [Azure Dev Marketing](https://aka.ms/DevEdCalFY21H1)> |
| Weekly Topic (if applicable) |  |
| Workshop Topic | Go |
| Content Level | Intermediate |
| Workshop Duration | 60 Minutes | 
| Title | Get started with Go |
| Description | What is this session about? This session will teach you about how to get started programming with Go, a popular open source programming language that makes it easy to build simple, reliable, and efficient software. We'll start off with learning about Go's history and the main features of the language. Then we'll explore the Go Playground and configure Go on our local workstations. We'll end the session by writing a Go application. This is part 1 of a 3 part mini series on Go. Who is it aimed at? This workshop is aimed at developers who want to learn about Go and why it is a good language to learn and code with. This is a beginner's session. No prior experience with Go or other programming languages is required. Why should you attend? You should attend this workshop if you want to get more familiar with the Go programming language and see if it's a good fit for you to explore more.|
| Content | https://docs.microsoft.com/learn/modules/go-get-started/ | 

# Workshop(s) details
| Date |  Local Start Time |  Location |  Speaker | SharePoint ID | Platform |
|------|-------------------|-----------|----------|---------------|----------|
| March 16, 2021 | 6:30 PM | Bangalore |----------|12520 |----------|
| March 16, 2021 | 4:00 PM | US/CA/AU |----------| 12519 |----------|
| March 17, 2021 | 7:30 PM | Sao Paulo |----------| 12523 |----------|
| March 17, 2021 | 7:30 PM | Shanghai |----------| 12522 |----------|
|  March 17, 2021 | 12:00 PM | EMEA |----------| 12521 |----------|

# Event Checklist

## 10 Weeks Prior
- [ ] Reactor Content Team (RCT) opens a new issue for an upcoming local workshop filling in the Event Information and Workshop details tables. RCT member who owns content (content owner) this week will be the assignee.
- [ ] RCT and content owner discuss details of the event in the comments of this issue. RCT adds a _confirmed-event_ label and _local-digital-event_ tag to the issue and adds event to the __Local Digital Events__ project. Issue will appear in the __Upcoming Streams__ column
- [ ] RCT adds a _ready-for-marketing-edit_ label so the RCT can review title and description

## 8 Weeks Prior
- [ ] RCT does a review of title and description and removes the _ready-for-marketing-edit_ label 
- [ ] RCT moves the issue to the __Ready for SharePoint__ column
- [ ] RCT informs the Reactor Marketing Team of the new event information
- [ ] RCT confirms the speaker
- [ ] RCT provides speaker with assets (e.g. slides, overlays) and the survey data for the event
- [ ] RCT moves the issue to the __Content Preparation In Progress__ column

## 5 weeks Prior
- [ ] Content owner opens a PR with the new content for the workshop on the [customer-facing Reactor repository](https://github.com/microsoft/Reactors/tree/main/online-event-resources) and adds the _content-development_ and _local-digital-event_ tag to the PR. 
- [ ] RCT reviews, approves, and merges the changes
- [ ] RCT shares content with the vendor/instructor
- [ ] RCT provides vendor/instructor with assets (e.g. slides, overlays) and the survey data for the event
- [ ] RCT ensures that instructors have received an invite to the workshops and that PM team works with instructors to get setup in the platform (e.g. Teams, Teams Live Event)

## 1 Week Prior
- [ ] Connect vendor/instructor with the PM(s) for the locations where this event has been marketed
- [ ] Check-in with vendor/instructor that they are prepared for the workshop
- [ ] RCT moves the issue to the __Ready to Stream__ column

## During and After Stream
- [ ] Instructor (and optional moderator) run the stream
- [ ] _(Optional)_RCT submits recording to be uploaded to the Reactor YouTube and to be made available on LearnTV
- [ ] RCT moves issue to the __Stream Complete__ column

**Comment by meaghanlewis** [comment]
@mebaumb updated the details and description for this week's workshop. Let me know if you have feedback/edits!

What is this session about?
This session will teach you about how to get started programming with Go, a popular open source programming language that makes it easy to build simple, reliable, and efficient software. We'll start off with learning about Go's history and the main features of the language. Then we'll explore the Go Playground and configure Go on our local workstations. We'll end the session by writing a Go application. This is part 1 of a 3 part mini series on Go.

Who is it aimed at?
This workshop is aimed at developers who want to learn about Go and why it is a good language to learn and code with. This is a beginner's session. No prior experience with Go or other programming languages is required.

Why should you attend?
You should attend this workshop if you want to get more familiar with the Go programming language and see if it's a good fit for you to explore more.

**Comment by mebaumb** [comment]
@meaghanlewis  - I added the line about the series! Otherwise I think it looks really good!

Would you call this intermediate content?

**Comment by meaghanlewis** [comment]
@mebaumb this looks good to go. I would call this first part in the series beginner content.

**Comment by mebaumb** [comment]
This has been published!

**Comment by meaghanlewis** [comment]
## Instructor notes

**Please share this link with attendees to follow along: https://aka.ms/GoGetStarted-8**

**This workshop covers the following:**
- An introduction to Go
  - Highlight the principles, what makes Go unique, and some examples of how it's used 
- Install Go
- Install Visual Studio Code and the Go extension
- Explore the Go Playground
- Hello World exercise

**Recommendations for walking through the content:**
- You have more than enough time to go through the whole module. 
  - Take each unit slow and try to get attendees involved and interactive
  - For the exercises, allow a few minutes for attendees to try on their own
- Make sure everyone is able to install Go for their operating system
- Make sure everyone has a working Hello, World program
- Walk through the knowledge check questions together

**Wrapping up:**

- At the end of the workshop, ask attendees to complete the summary so they can get a badge for completing the module.
- Also please encourage them to rate the module please 😄
- Share out the survey link: https://aka.ms/Reactor/Survey with the event code (the Reactor contact on the call can give you this)
