### ISSUE TITLE
March 22-26 - Learn the foundations of programming in Go

### ISSUE THREAD

**Issue by mebaumb** [microsoft/ReactorPlanning#156]
# Event Information
| Category | Details |
|-----------|---------|
| Reactor Topic | Coding, Languages, and Frameworks |
| Monthly Topic (if applicable) | <Topic taken from [Azure Dev Marketing](https://aka.ms/DevEdCalFY21H1)> |
| Weekly Topic (if applicable) |  |
| Workshop Topic | Go |
| Content Level | Intermediate |
| Workshop Duration | 60 Minutes | 
| Title |  Learn the foundations of programming in Go |
| Description | What is this session about? This session will teach you about the main components and concepts that you'll need to write Go applications. We'll cover how to: declare variables and constants, use the basic data types available, write functions, and create and use packages. This session will be a hands on workshop that will teach you the tools that you need to start using Go. This is part 2 of our 3 part mini series about Go. Who is it aimed at? This workshop is aimed at developers who want to learn more about Go and get hands-on experience writing code with Go. This is a beginner's session. No prior experience with Go is required. To participate, you should have Visual Studio Code installed. Why should you attend? You should attend this workshop if you want to get more familiar with the Go programming language and be more comfortable creating your own Go applications. |
| Content | https://docs.microsoft.com/learn/modules/go-variables-functions-packages/ |

# Workshop(s) details
| Date |  Local Start Time |  Location |  Speaker | SharePoint ID | Platform |
|------|-------------------|-----------|----------|---------------|----------|
| March 23, 2021 | 6:30 PM | Bangalore |----------|12525 |----------|
| March 23, 2021 | 4:00 PM | US/CA/AU |----------| 12524 |----------|
| March 24, 2021 | 7:30 PM | Sao Paulo |----------| 12528 |----------|
| March 24, 2021 | 7:30 PM | Shanghai |----------| 12527 |----------|
|  March 24, 2021 | 12:00 PM | EMEA |----------| 12526 |----------|

# Event Checklist

## 10 Weeks Prior
- [ ] Reactor Content Team (RCT) opens a new issue for an upcoming local workshop filling in the Event Information and Workshop details tables. RCT member who owns content (content owner) this week will be the assignee.
- [ ] RCT and content owner discuss details of the event in the comments of this issue. RCT adds a _confirmed-event_ label and _local-digital-event_ tag to the issue and adds event to the __Local Digital Events__ project. Issue will appear in the __Upcoming Streams__ column
- [ ] RCT adds a _ready-for-marketing-edit_ label so the RCT can review title and description

## 8 Weeks Prior
- [ ] RCT does a review of title and description and removes the _ready-for-marketing-edit_ label 
- [ ] RCT moves the issue to the __Ready for SharePoint__ column
- [ ] RCT informs the Reactor Marketing Team of the new event information
- [ ] RCT confirms the speaker
- [ ] RCT provides speaker with assets (e.g. slides, overlays) and the survey data for the event
- [ ] RCT moves the issue to the __Content Preparation In Progress__ column

## 5 weeks Prior
- [ ] Content owner opens a PR with the new content for the workshop on the [customer-facing Reactor repository](https://github.com/microsoft/Reactors/tree/main/online-event-resources) and adds the _content-development_ and _local-digital-event_ tag to the PR. 
- [ ] RCT reviews, approves, and merges the changes
- [ ] RCT shares content with the vendor/instructor
- [ ] RCT provides vendor/instructor with assets (e.g. slides, overlays) and the survey data for the event
- [ ] RCT ensures that instructors have received an invite to the workshops and that PM team works with instructors to get setup in the platform (e.g. Teams, Teams Live Event)

## 1 Week Prior
- [ ] Connect vendor/instructor with the PM(s) for the locations where this event has been marketed
- [ ] Check-in with vendor/instructor that they are prepared for the workshop
- [ ] RCT moves the issue to the __Ready to Stream__ column

## During and After Stream
- [ ] Instructor (and optional moderator) run the stream
- [ ] _(Optional)_RCT submits recording to be uploaded to the Reactor YouTube and to be made available on LearnTV
- [ ] RCT moves issue to the __Stream Complete__ column

**Comment by meaghanlewis** [comment]
@mebaumb this is ready for your review!

What is this session about?
This session will teach you about the main components and concepts that you'll need to write Go applications. We'll cover how to: declare variables and constants, use the basic data types available, write functions, and create and use packages. This session will be a hands on workshop that will teach you the tools that you need to start using Go. This is part 2 of our 3 part mini series about Go. 

Who is it aimed at?
This workshop is aimed at developers who want to learn more about Go and get hands-on experience writing code with Go. This is a beginner's session. No prior experience with Go is required. To participate, you should have Visual Studio Code installed.

Why should you attend?
You should attend this workshop if you want to get more familiar with the Go programming language and be more comfortable creating your own Go applications.

**Comment by mebaumb** [comment]
@meaghanlewis Looks really good, added something to the about section - let me know what you think!

**Comment by meaghanlewis** [comment]
@mebaumb - 🚢  it!

**Comment by mebaumb** [comment]
This has been published!

**Comment by meaghanlewis** [comment]
## Instructor notes

**Please share this link with attendees to follow along: https://aka.ms/PackagesVariablesFunctions-8**

**This workshop covers the following:**
- Variables
- Constants
- Data types: integers, floating-point numbers, booleans, strings
- Functions
- Packages

**Recommendations for walking through the content:**
- You have more than enough time to go through the whole module. 
- Visual Studio Code with the Go extension should be used to run all the examples in this module. (The Go Playground will work as an alternative, but not for all examples). Try to spend most of your time in Visual Studio Code and less time showing the actual Learn module
- Go through the knowledge check questions together

**Wrapping up:**

- At the end of the workshop, ask attendees to complete the summary so they can get a badge for completing the module.
- Also please encourage them to rate the module please 😄
- Share out the survey link: https://aka.ms/Reactor/Survey with the event code (the Reactor contact on the call can give you this)
