### ISSUE TITLE
Aug 3 - 7:  Blockchain development fundamentals

### ISSUE THREAD

**Issue by meaghanlewis** [microsoft/ReactorPlanning#17]
# Event Information
| Category | Details |
|-----------|---------|
| Reactor Topic | Emerging Technologies |
| Monthly Topic (if applicable) | API |
| Weekly Topic (if applicable) | Blockchain |
| Stream Topic | Explore the foundations of Blockchain development |
| Stream Date | Aug 3 - 7, 2020  | 
| Stream Duration | 90 minutes | 
| Title | Blockchain Basics |
| Description | Why is blockchain important? Take a first look into the history of blockchain, present-day use cases, and what the future might hold for this emerging technology. Join in as we discuss ways blockchain can help you become a better crypto user, developer, or business manager.|
| Content | https://github.com/microsoft/Reactors/tree/main/Blockchain_1/Part_1_Blockchain_and_Ethereum |

# Workshop details
| Date |  Local Start Time |  Location |  Speaker | SharePoint ID | Platform |
|------|-------------------|-----------|----------|---------------|----------|
| Aug 3 |  4:00 PM GMT+4 | Abu Dhabi | Avinash Mishra | 7878 | Teams |
| Aug 3 |  6:00 PM  GMT+3 | Tel Aviv | Avinash Mishra | 7879 | Teams |
| Aug 4 |  8:00 PM  GMT+10| Sydney | Maddie Shang | 7880 | Teams |
| Aug 4 |  6:30 PM GMT+5:30| Bangalore | Avinash Mishra | 7881 | Teams |
| Aug 5 |  7:30 PM GMT-3| Sao Paulo | Solange Gueiros | 7755 | Teams |
| Aug 5 |  7:30 PM GMT+8 | Shanghai | Maddie Shang | 7883 | Teams |
| Aug 5 | 6:00 PM GMT+1  | London | Maddie Shang | 7884 | Teams |
| Aug 5 | 7:00 PM PDT | US/Canada | Maddie Shang | 7885 | Teams |

# Event Checklist

## 10 Weeks Prior
- [X] Reactor Content Team (RCT) opens a new issue for an upcoming local workshop filling in the Event Information and Workshop details tables. RCT member who owns content (content owner) this week will be the assignee.
- [X] RCT and content owner discuss details of the event in the comments of this issue. RCT adds a _confirmed-event_ label and _local-digital-event_ tag to the issue and adds event to the __Local Digital Events__ project. Issue will appear in the __Upcoming Streams__ column
- [X] RCT adds a _ready-for-marketing-edit_ label so the RCT can review title and description

## 8 Weeks Prior
- [X] RCT does a review of title and description and removes the _ready-for-marketing-edit_ label 
- [X] RCT moves the issue to the __Ready for SharePoint__ column
- [X] RCT informs the Reactor Marketing Team of the new event information
- [ ] RCT confirms the speaker
- [ ] RCT provides speaker with assets (e.g. slides, overlays) and the survey data for the event
- [ ] RCT moves the issue to the __Content Preparation In Progress__ column

## 5 weeks Prior
- [ ] Content owner opens a PR with the new content for the workshop on the [customer-facing Reactor repository](https://github.com/microsoft/Reactors) and adds the _content-development_ and _local-digital-event_ tag to the PR. 
- [ ] Content owner adds to the same PR modification to the [Streaming README](https://github.com/microsoft/Reactors/tree/main/Online) 
- [ ] RCT reviews, approves, and merges the changes
- [ ] RCT shares content with the vendor/instructor
- [ ] RCT provides vendor/instructor with assets (e.g. slides, overlays) and the survey data for the event
- [ ] RCT ensures that instructors have received an invite to the workshops and that PM team works with instructors to get setup in the platform (e.g. Teams, Teams Live Event)

## 1 Week Prior
- [ ] Connect vendor/instructor with the PM(s) for the locations where this event has been marketed
- [ ] Check-in with vendor/instructor that they are prepared for the workshop
- [ ] RCT moves the issue to the __Ready to Stream__ column

## During and After Stream
- [ ] Instructor (and optional moderator) run the stream
- [ ] _(Optional)_RCT submits recording to be uploaded to the Reactor YouTube and to be made available on LearnTV
- [ ] RCT moves issue to the __Stream Complete__ column

**Comment by mebaumb** [comment]
Abu Dhabi, Bangalore, & Tel Aviv published (6/25)

**Comment by mebaumb** [comment]
Sydney, London, & USA Published without Speakers (7/6)

**Comment by mebaumb** [comment]
Sydney and USA speakers updated.

**Comment by mebaumb** [comment]
All events are published!
