### ISSUE TITLE
Aug 4 - Dive into Azure Blockchain Service

### ISSUE THREAD

**Issue by meaghanlewis** [microsoft/ReactorPlanning#19]
# Event Information
| Category | Details |
|-----------|---------|
| Reactor Topic | Emerging Technologies |
| Monthly Topic (if applicable) | Powerful APIs and Power Platform |
| Weekly Topic (if applicable) | Blockchain |
| Stream Date | Aug 4, 2020 | 
| Stream Time | 4PM PT | 
| Stream Duration | 60 min | 
| Title | Dive into Azure Blockchain Service|
| Description | Let’s take a deeper look at Azure Blockchain Service, a fully managed ledger service that helps users grow and operate blockchain networks at scale. In this session, we'll use the Azure Blockchain Service API to build and manage blockchain networks and deploy our smart contracts. Next, we'll explore how to capture contract and transaction data in the cloud with the Blockchain Data Manager. Along the way, we'll use VS Code to code, test, and deploy Ethereum smart contracts. 
A basic knowledge of blockchain foundations will be helpful. If you plan to follow along with the session, you'll also need an Azure account.|
| Speaker | @meaghanlewis  |
| Moderator | TBD |
| Event ID | 7845 |

Additional Resources:  
<Additional resources that can be linked from social media for promotion or added to the description of VOD>

# Event Checklist

## 10 Weeks Prior
- [X] Reactor Content Team (RCT) or Speaker opens a new issue for an upcoming stream filling in the Event Information table. Both RCT and Speaker are marked as assignees.
- [X] RCT and Speaker discuss details of the event in the comments of this issue. RCT adds a _confirmed-event_ label and _global-twitch-event_ tag to the issue and adds event to the __Global Live Streams__ project. Issue will appear in the __Upcoming Streams__ column
- [X] Speaker adds a _ready-for-marketing-edit_ label so the RCT can review title and description

## 8 Weeks Prior
- [X] RCT does a review of title and description and removes the _ready-for-marketing-edit_ label 
- [X] RCT moves the issue to the __Ready for SharePoint__ column
- [x] RCT informs the Reactor Marketing Team of the new event information
- [x] RCT provides speaker with assets (e.g. slides, overlays) and the survey data for the event
- [x] RCT moves the issue to the __MONTH Streams Prep__ column (according to the month it will be streamed in)

## 2 Weeks Prior *(Done in /microsoft/Reactors)*
- [ ] Speaker opens a PR with the new content for the stream on the [customer-facing Reactor repository](https://github.com/microsoft/Reactors) and adds the _content-development_ and _global-twitch-event_ tag to the PR. 
- [ ] Speaker adds to the same PR a modification to the [Streaming README](https://github.com/microsoft/Reactors/tree/main/Online) to include their stream information.
- [ ] Speaker adds the RCT assigned to the issue as the reviewer when it is ready for review/merge
- [ ] RCT reviews, approves, and merges the changes

## 1 Week Prior
- [ ] Speaker and Moderator test setup for streaming (instructions coming soon)
- [ ] RCT checks in with the speaker and moves the issue to the __Ready to Stream__ column

## During and After Stream
- [ ] Speaker and Moderator run the stream
- [x] RCT submits recording to be uploaded to the Reactor YouTube and to be made available on LearnTV
- [x] RCT moves issue to the __Stream Complete__ column

**Comment by KimberlyBolton1** [comment]
Session completed and recording uploaded to YouTube: https://youtu.be/wEAMjU3K9-U. Closing issue.
