### ISSUE TITLE
Feb 17th - Create a crypto game token

### ISSUE THREAD

**Issue by meaghanlewis** [microsoft/ReactorPlanning#193]
# Event Information
| Category | Details |
|-----------|---------|
| Stream Date | Feb 17th | 
| Stream Time | 9 am | 
| Title | Create a crypto game token |
| Description | below |
| Speaker | @meaghanlewis |
| SharePoint ID | 12960 |  
| SharePoint Status | Published | 
| content | https://github.com/microsoft/Reactors/blob/main/workshop-resources/emerging-tech/Blockchain_2/creating_decentralized_apps/create-a-crypto-game-item.md |

What is this workshop about?
We'll begin with an overview of blockchain tokens, including what they are and the different types that are available. Then we'll focus on creating a blockchain token for a crypto game piece that will represent the player and the balance available. To see the token in action, we will build a decentralized app with a simple user interface. In this workshop, we'll be using Visual Studio Code, Truffle, and the MetaMask browser extension.

Who is it for?
This workshop is for those that know the basic fundamentals of blockchain and want more hands-on experience with creating and using tokens and decentralized apps.

Why should you attend?
To learn about blockchain tokens, see them in action, and think up ideas of how you can use tokens in your blockchain app.

Additional Resources:  
<Additional resources that can be linked from social media for promotion or added to the description of VOD>

# Event Checklist

## 10 Weeks Prior
- [ ] Title & Description Finalized
- [ ] Tracking Links/Short links
- [ ] Published
- [ ] Calendar Invite

**Comment by meaghanlewis** [comment]
@mebaumb this is ready for your review

**Comment by mebaumb** [comment]
@meaghanlewis Updated below with your edits. 

Create a Blockchain Token Game Piece

What is this workshop about?
We'll begin with an overview of blockchain tokens, including what they are and the different types that are available. Then we'll focus on creating a blockchain token for a crypto game piece that will represent the player and the balance available. To see the token in action, we will build a decentralized app with a simple user interface. In this workshop, we'll be using Visual Studio Code, Truffle, and the MetaMask browser extension.

Who is it for?
This workshop is for those that know the basic fundamentals of blockchain and want more hands-on experience with creating and using tokens and decentralized apps.

Why should you attend?
To learn about blockchain tokens, see them in action, and think up ideas of how you can use tokens in your blockchain app.

**Comment by meaghanlewis** [comment]
Thanks for reviewing @mebaumb. Appreciate the suggestions.

For the title, how about: "Create a blockchain token game piece"

And the token will be for a general crypto game player. Does this sentence below make more sense?
"Then we'll focus on creating a blockchain token for a crypto game piece that will represent the player and the balance available."

**Comment by mebaumb** [comment]
@meaghanlewis - I updated everything above! :) 

Let me know if this is intermediate content and if it's good to publish! :)

**Comment by meaghanlewis** [comment]
@mebaumb this is good to publish. And yes, it is intermediate content. Thanks!
