### ISSUE TITLE
Feb 24 - Learn about blockchain oracles

### ISSUE THREAD

**Issue by meaghanlewis** [microsoft/ReactorPlanning#194]
# Event Information
| Category | Details |
|-----------|---------|
| Stream Date |Feb 24 | 
| Stream Time | 9am | 
| Title | Learn about blockchain oracles |
| Description | below |
| Speaker | @meaghanlewis |
| SharePoint ID | 12961 |  
| SharePoint Status | Published | 
| content | https://github.com/microsoft/Reactors/blob/main/workshop-resources/emerging-tech/Blockchain_2/building_better_smart_contracts/introduction-to-oracles.md |

What is this workshop about?
In this workshop, we'll begin by building a shared understanding of what Oracles are, what purpose they serve, and some of the top solutions to create Oracles. Then we'll go through a demo of a smart contract using Oracles to grab the latest Ethereum price from an external source. We'll use the [Remix IDE](https://remix.ethereum.org/) to write a smart contract, the [Kovan Test Network](https://kovan-testnet.github.io/website/) to deploy the contract, and [MetaMask](https://metamask.io/) as the wallet client to manage test Ether and tokens.

Who is it for?
This workshop is for those that know the basic fundamentals of blockchain and want more hands-on experience with creating smart contracts using Oracles.

Why should you attend?
To learn about blockchain Oracles, including being able to explain clearly what they are, why you would use them, and get an idea of how to build solutions using Oracles.

# Event Checklist

## 10 Weeks Prior
- [ ] Title & Description Finalized
- [ ] Tracking Links/Short links
- [ ] Published
- [ ] Calendar Invite

**Comment by meaghanlewis** [comment]
@mebaumb this is ready for your review.

**Comment by mebaumb** [comment]
@meaghanlewis - this sounds great! What do you think about the title being something like: 

Oracles in Action, From Fundamentals to Deployment

is the stream intermediate?

**Comment by meaghanlewis** [comment]
@mebaumb, yes this stream is intermediate. 

Thanks for the title suggestion! How about something like _Blockchain Oracles in actions, from fundamentals to development_
