### ISSUE TITLE
March 24 - Build a to-do list command line program in Rust 

### ISSUE THREAD

**Issue by meaghanlewis** [microsoft/ReactorPlanning#195]
# Event Information
| Category | Details |
|-----------|---------|
| Stream Date | March 24 | 
| Stream Time | 9am | 
| Title | Build a to-do list command line program in Rust  |
| Description | below|
| Speaker | @meaghanlewis |
| SharePoint ID | 12963 |  
| SharePoint Status | Published | 
| content | https://github.com/microsoft/aed-rust-learn-content/tree/main/create-a-command-line-program | 

What is this workshop about?
The goal of this workshop is to create a command-line program using Rust. The program will allow you to add and remove tasks from a to-do list. Along the way we'll integrate various third-party crates for command line argument parsing and error handling.

Who is it for?
This workshop is for those who have an understanding of commond concepts including variables, data types and functions. You should also be familiar with generic data types. To participate in this workshop you should have Rust and Visual Studio Code installed.

Why should you attend?
You should attend if you want to learn more about Rust and get more experience bulding Rust programs.

# Event Checklist

## 10 Weeks Prior
- [ ] Title & Description Finalized
- [ ] Tracking Links/Short links
- [ ] Published
- [ ] Calendar Invite

**Comment by meaghanlewis** [comment]
@mebaumb this is ready for your review

**Comment by mebaumb** [comment]
@meaghanlewis - This looks good to me! 
Is this Intermediate content?
Is this good to publish?

**Comment by meaghanlewis** [comment]
@mebaumb yes this is intermediate content. Thanks!
