### ISSUE TITLE
March 17 - Write automated tests in Rust

### ISSUE THREAD

**Issue by meaghanlewis** [microsoft/ReactorPlanning#196]
# Event Information
| Category | Details |
|-----------|---------|
| Stream Date | March 17 | 
| Stream Time |  9am | 
| Title | Write automated tests in Rust |
| Description | below |
| Speaker | @meaghanlewis |
| SharePoint ID | 12962 |  
| SharePoint Status | Published |
| content | https://github.com/microsoft/aed-rust-learn-content/blob/main/automated-tests |

What is this workshop about?
Rust comes with a simple yet powerful test suite built into the language. In this workshop, we'll explore how we can use different test strategies to ensure our program's correctness even further. Learn about the three different types of test available in Rust: unit, documentation, and integration. Then put what you've learned into practice by writing and running examples of each type of test.

Who is it for?
This workshop is for Rust enthusiast's who want to explore the testing features of the language. To participate in this workshop you should have Rust and Visual Studio Code installed. Some prior experience programming in Rust is highly recommended.

Why should you attend?
To get familiar with the test types Rust offers, and know when and how to write each type of test.

# Event Checklist

## 10 Weeks Prior
- [ ] Title & Description Finalized
- [ ] Tracking Links/Short links
- [ ] Published
- [ ] Calendar Invite

**Comment by meaghanlewis** [comment]
@mebaumb this is ready for your review.

**Comment by mebaumb** [comment]
@meaghanlewis - this is good! Are you ready for me to publish? 

Should this be intermediate content?

**Comment by meaghanlewis** [comment]
@mebaumb yes, this is intermediate content. All good to publish!
