### ISSUE TITLE
Feb 2 - Azure Quantum Developer Workshop

### ISSUE THREAD

**Issue by meaghanlewis** [microsoft/ReactorPlanning#211]
# Event Information
| Category | Details |
|-----------|---------|
| Stream Date | Feb 2 | 
| Stream Time | 8am-12pm PST | 
| Title | Azure Quantum Developer Workshop |
| Description | below |
| SharePoint ID | 12920 |  
| SharePoint Status | Published | 

**Description:**
Do you want to become a quantum developer? Join us for an inside look at Azure Quantum— your path to scalable quantum computing.

Azure Quantum is an open ecosystem bringing the most innovative quantum computing and optimization solutions into a single marketplace.

In this [Azure Quantum Developer Workshop](https://cloudblogs.microsoft.com/quantum/2021/01/19/industry-leaders-showcase-solutions-azure-quantum-developer-workshop/) episode, learn about the Azure Quantum service, the vibrant partner ecosystem supporting it and how developers and other technical roles can use Azure Quantum solutions to drive impact today.

**Please register today at: aka.ms/AQDW2**

**And check out our blog post for more details about the workshop at: https://cloudblogs.microsoft.com/quantum/2021/01/19/industry-leaders-showcase-solutions-azure-quantum-developer-workshop/**

# Event Checklist

## 10 Weeks Prior
- [ ] Title & Description Finalized
- [ ] Tracking Links/Short links
- [ ] Published
- [ ] Calendar Invite

**Comment by meaghanlewis** [comment]
@mebaumb can you help me get this event published please? Let me know if you need additional details.

**Comment by mebaumb** [comment]
This has been published!
