### ISSUE TITLE
April 14 - Learn about how concurrency works in Go

### ISSUE THREAD

**Issue by meaghanlewis** [microsoft/ReactorPlanning#219]
# Event Information
| Category | Details |
|-----------|---------|
| Stream Date | 4/14 | 
| Stream Time | 9 am | 
| Title | Learn about how concurrency works in Go |
| Description |---------|
| Speaker | @meaghanlewis |
| SharePoint ID | 13113 |  
| SharePoint Status | Planning |
| content | https://github.com/microsoft/aed-go-learn-content/tree/main/concurrency | 

What is this session about?
In this stream, join Meaghan Lewis to learn about concurrency, one of the most unique features in Go. You'll learn about how concurrency works and how it can help you to write faster and more dynamic programs. This will be a hands-on session where we'll walk through examples of how to integrate concurrency into programs.

Who is it for?
This session is for those who are familiar with how to write and run Go programs. You should understand basic data types like string, int, and boolean, and know how to write basic control flows and functions. You should also have a Go environment ready to create programs. Ideally, you should have installed and configured Go locally and have installed Visual Studio Code.

Why should you attend?
You should attend if you want to learn more about Go and get more experience bulding Go programs.

# Event Checklist

## 10 Weeks Prior
- [ ] Title & Description Finalized
- [ ] Tracking Links/Short links
- [ ] Published
- [ ] Calendar Invite

**Comment by mebaumb** [comment]
@meaghanlewis  - is this ready to publish? I read through the description that you provided, I think it looks really good!

**Comment by meaghanlewis** [comment]
@mebaumb this looks good to go! thanks.
