### ISSUE TITLE
Aug 10 - Actionable GitHub Actions

### ISSUE THREAD

**Issue by GeekTrainer** [microsoft/ReactorPlanning#22]
# Event Information
| Category | Details |
|-----------|---------|
| Reactor Topic | DevTools |
| Monthly Topic (if applicable) | Powerful APIs |
| Weekly Topic (if applicable) | Azure Static Web Apps |
| Stream Topic | Azure Static Web Apps |
| Stream Date | Aug 10 | 
| Stream Time | 1600 PDT | 
| Stream Duration | 60 | 
| Title | Get Moving with GitHub Actions |
| Description | GitHub is no longer just a place to store your code. That’s a good thing, because the work doesn't end after code has been pushed or merged. There are unit tests to execute, linting to run, and deployments to push. With GitHub Actions, you can perform any of these activities based on the events you define. Join us in this session for a conversation on GitHub Actions and take your repositories to the next level! |
| Speaker | Christopher Harrison (@geektrainer) and Luis Bosquez |
| Moderator | <Name or GitHub alias> |
| Event ID | 7995  (7871 - cancelled) |

Additional Resources:  
N/A

# Event Checklist

## 10 Weeks Prior
- [X] Reactor Content Team (RCT) or Speaker opens a new issue for an upcoming stream filling in the Event Information table. Both RCT and Speaker are marked as assignees.
- [X] RCT and Speaker discuss details of the event in the comments of this issue. RCT adds a _confirmed-event_ label and _global-twitch-event_ tag to the issue and adds event to the __Global Live Streams__ project. Issue will appear in the __Upcoming Streams__ column
- [X] Speaker adds a _ready-for-marketing-edit_ label so the RCT can review title and description

## 8 Weeks Prior
- [X] RCT does a review of title and description and removes the _ready-for-marketing-edit_ label 
- [x] RCT moves the issue to the __Ready for SharePoint__ column
- [x] RCT informs the Reactor Marketing Team of the new event information
- [ ] RCT provides speaker with assets (e.g. slides, overlays) and the survey data for the event
- [x] RCT moves the issue to the __MONTH Streams Prep__ column (according to the month it will be streamed in)

## 2 Weeks Prior *(Done in /microsoft/Reactors)*
- [ ] Speaker opens a PR with the new content for the stream on the [customer-facing Reactor repository](https://github.com/microsoft/Reactors) and adds the _content-development_ and _global-twitch-event_ tag to the PR. 
- [ ] Speaker adds to the same PR a modification to the [Streaming README](https://github.com/microsoft/Reactors/tree/main/Online) to include their stream information.
- [ ] Speaker adds the RCT assigned to the issue as the reviewer when it is ready for review/merge
- [ ] RCT reviews, approves, and merges the changes

## 1 Week Prior
- [ ] Speaker and Moderator test setup for streaming (instructions coming soon)
- [ ] RCT checks in with the speaker and moves the issue to the __Ready to Stream__ column

## During and After Stream
- [ ] Speaker and Moderator run the stream
- [x] RCT submits recording to be uploaded to the Reactor YouTube and to be made available on LearnTV
- [x] RCT moves issue to the __Stream Complete__ column

**Comment by mebaumb** [comment]
@KimberlyBolton1 - We need to re-edit this one! The topic, title and abstract changed.

**Comment by KimberlyBolton1** [comment]
@GeekTrainer 
Here's an edited version of your abstract. Let me know if it's good to go:
Get Moving with GitHub Actions
GitHub is no longer just a place to store your code. That’s a good thing, because the work doesn't end after code has been pushed or merged. There are unit tests to execute, linting to run, and deployments to push. With GitHub Actions, you can perform any of these activities based on the events you define. Join us in this session for a conversation on GitHub Actions and take your repositories to the next level!

**Comment by GeekTrainer** [comment]
🚢

**Comment by KimberlyBolton1** [comment]
@mbaumb
Abstract final and moved to Ready for Sharepoint.

**Comment by mebaumb** [comment]
Uploaded into SharePoint (6/22)

**Comment by KimberlyBolton1** [comment]
Session recorded and uploaded to YouTube: https://www.youtube.com/watch?v=JdosmmR3wFE&t=19s. Closing issue.
