### ISSUE TITLE
Aug 11- Functional Functions

### ISSUE THREAD

**Issue by drguthals** [microsoft/ReactorPlanning#23]
# Event Information
| Category | Details |
|-----------|---------|
| Reactor Topic | Coding, Languages, and Frameworks |
| Monthly Topic (if applicable) | <Topic taken from [Azure Dev Marketing](https://aka.ms/DevEdCalFY21H1)> |
| Weekly Topic (if applicable) | <Topic decided by RCT if relevant> |
| Stream Topic | <2-5 words describing the topic> |
| Stream Date | August 11, 2020 | 
| Stream Time | 4:00 pm | 
| Stream Duration | 60 | 
| Title | Be Better Served by Serverless Computing |
| Description | Setting up traditional web servers can be tricky, even those based in the cloud. How do you manage scaling? How many VMs are too many? What size should they be? And how do you manage those little operations which are executed in bursts and then not for days? Serverless computing can ease your burden. You can focus on your code while letting serverless Azure Functions handle the scaling for you. In this session, we'll create and deploy some functions with Python and develop applications with less overhead.|
| Speaker | Christopher Harrison |
| Moderator | <Name or GitHub alias> |
| SharePoint ID | 7952 |  

Additional Resources:  
<Additional resources that can be linked from social media for promotion or added to the description of VOD>

# Event Checklist

## 10 Weeks Prior
- [x] Reactor Content Team (RCT) or Speaker opens a new issue for an upcoming stream filling in the Event Information table. Both RCT and Speaker are marked as assignees.
- [x] RCT and Speaker discuss details of the event in the comments of this issue. RCT adds a _confirmed-event_ label and _global-twitch-event_ tag to the issue and adds event to the __Global Live Streams__ project. Issue will appear in the __Upcoming Streams__ column
- [x] Speaker adds a _ready-for-marketing-edit_ label so the RCT can review title and description

## 8 Weeks Prior
- [x] RCT does a review of title and description and removes the _ready-for-marketing-edit_ label 
- [x] RCT moves the issue to the __Ready for SharePoint__ column
- [ ] RCT informs the Reactor Marketing Team of the new event information
- [ ] RCT provides speaker with assets (e.g. slides, overlays) and the survey data for the event
- [ ] RCT moves the issue to the __MONTH Streams Prep__ column (according to the month it will be streamed in)

## 2 Weeks Prior *(Done in /microsoft/Reactors)*
- [ ] Speaker opens a PR with the new content for the stream on the [customer-facing Reactor repository](https://github.com/microsoft/Reactors) and adds the _content-development_ and _global-twitch-event_ tag to the PR. 
- [ ] Speaker adds to the same PR a modification to the [Streaming README](https://github.com/microsoft/Reactors/tree/main/Online) to include their stream information.
- [ ] Speaker adds the RCT assigned to the issue as the reviewer when it is ready for review/merge
- [ ] RCT reviews, approves, and merges the changes

## 1 Week Prior
- [ ] Speaker and Moderator test setup for streaming (instructions coming soon)
- [ ] RCT checks in with the speaker and moves the issue to the __Ready to Stream__ column

## During and After Stream
- [ ] Speaker and Moderator run the stream
- [x] RCT submits recording to be uploaded to the Reactor YouTube and to be made available on LearnTV
- [x] RCT moves issue to the __Stream Complete__ column

**Comment by sguthals** [comment]
I'm confirming with Anne that the date works.

**Comment by mebaumb** [comment]
@KimberlyBolton1 - Hey this event is ready for Marketing!

**Comment by KimberlyBolton1** [comment]
@GeekTrainer 
Edited abstract below...let me know if you have any feedback:
Work Less with Serverless Computing
Setting up traditional web servers can be tricky, even ones based in the cloud. How do you manage scaling? How many VMs are too many or too few? And what about those little operations which might be executed in bursts and then not again for days? Let serverless computing ease your burden. With serverless computing, you can put your focus on the code and let Azure Functions handle the complex orchestration problems. In this session, we’ll walk through how to create functions with Python for an easier, better end-to-end development experience.

**Comment by KimberlyBolton1** [comment]
Received feedback from content owner that we need to pivot away from serverless being less work. Here's the final edit:
Be Better Served by Serverless Computing

Setting up traditional web servers can be tricky, even those based in the cloud. How do you manage scaling? How many VMs are too many? What size should they be? And how do you manage those little operations which are executed in bursts and then not for days? Serverless computing can ease your burden. You can focus on your code while letting serverless Azure Functions handle the scaling for you. In this session, we'll create and deploy some functions with Python and develop applications with less overhead.
@mebaumb abstract final and moved to ready for sharepoint.

**Comment by mebaumb** [comment]
Published on Sharepoint (6/29)

**Comment by KimberlyBolton1** [comment]
Session recorded and uploaded to YouTube: https://www.youtube.com/watch?v=LF_wO1yMUTM. Closing issue.
