### ISSUE TITLE
April 12 - 16 - Leverage GitHub Actions to Publish to GitHub Packages

### ISSUE THREAD

**Issue by mebaumb** [microsoft/ReactorPlanning#232]
# Event Information
| Category | Details |
|-----------|---------|
| Reactor Topic | DevOps and Dev Tools |
| Monthly Topic (if applicable) | <Topic taken from [Azure Dev Marketing](https://aka.ms/DevEdCalFY21H1)> |
| Weekly Topic (if applicable) |  |
| Workshop Topic |  |
| Workshop Duration | | 
| Title | Leverage GitHub Actions to Publish to GitHub Packages |
| Description | GitHub Packages is a package management service that makes it easy to use and publish packages in your code. When developing open-source packages, you can use GitHub Actions to help manage the development process. In this workshop, we'll explore when to use a Package Repository, create a Dockerfile, and build a container image to run in Continuous Integration (CI). Then, we'll show you how to locally run a container image hosted on GitHub Docker Registry and publish your code with GitHub Packages. To follow along with this workshop, you'll need a GitHub account and some experience with Docker and Docker Registry. |

# Content
https://aka.ms/GHAPackages-8

# Workshop(s) details
| Date |  Local Start Time |  Location |  Speaker | SharePoint ID | Platform |
|------|-------------------|-----------|----------|---------------|----------|
| April 13, 2021 | 6:30 PM | Bangalore | Devendra Rawat | 13045 |----------|
| April 13, 2021 | 4:00 PM | US/CA/AU | Christian Melendez | 13046 |----------|
| April 14, 2021 | 7:00 PM | Sao Paulo | Flavio Figueiredo | 13047 |----------|
| April 14, 2021 | 7:30 PM | Shanghai | Warren Wong | 13048 |----------|
| April 14, 2021 | 12:00 PM | EMEA | Andrew Smith | 13049 |----------|

# Event Checklist

## 10 Weeks Prior
- [ ] Reactor Content Team (RCT) opens a new issue for an upcoming local workshop filling in the Event Information and Workshop details tables. RCT member who owns content (content owner) this week will be the assignee.
- [ ] RCT and content owner discuss details of the event in the comments of this issue. RCT adds a _confirmed-event_ label and _local-digital-event_ tag to the issue and adds event to the __Local Digital Events__ project. Issue will appear in the __Upcoming Streams__ column
- [ ] RCT adds a _ready-for-marketing-edit_ label so the RCT can review title and description

## 8 Weeks Prior
- [ ] RCT does a review of title and description and removes the _ready-for-marketing-edit_ label 
- [ ] RCT moves the issue to the __Ready for SharePoint__ column
- [ ] RCT informs the Reactor Marketing Team of the new event information
- [ ] RCT confirms the speaker
- [ ] RCT provides speaker with assets (e.g. slides, overlays) and the survey data for the event
- [ ] RCT moves the issue to the __Content Preparation In Progress__ column

## 5 weeks Prior
- [ ] Content owner opens a PR with the new content for the workshop on the [customer-facing Reactor repository](https://github.com/microsoft/Reactors/tree/main/online-event-resources) and adds the _content-development_ and _local-digital-event_ tag to the PR. 
- [ ] RCT reviews, approves, and merges the changes
- [ ] RCT shares content with the vendor/instructor
- [ ] RCT provides vendor/instructor with assets (e.g. slides, overlays) and the survey data for the event
- [ ] RCT ensures that instructors have received an invite to the workshops and that PM team works with instructors to get setup in the platform (e.g. Teams, Teams Live Event)

## 1 Week Prior
- [ ] Connect vendor/instructor with the PM(s) for the locations where this event has been marketed
- [ ] Check-in with vendor/instructor that they are prepared for the workshop
- [ ] RCT moves the issue to the __Ready to Stream__ column

## During and After Stream
- [ ] Instructor (and optional moderator) run the stream
- [ ] _(Optional)_RCT submits recording to be uploaded to the Reactor YouTube and to be made available on LearnTV
- [ ] RCT moves issue to the __Stream Complete__ column

**Comment by mebaumb** [comment]
@meaghanlewis - what do you think about this? 

Title: Leverage GitHub Actions to Publish to GitHub Packages

Description: GitHub Packages make it easy to find and connect to public packages anywhere on GitHub and to find private packages that are approved for use by your organization. If you are developing an open-source package, you can use GitHub Actions to help manage the development process. In this workshop, we'll explore when to use a Package Repository, set up a Continuous Integration (CI) workflow, create a Dockerfile, and build a container image in CI. Then, we'll show you how to locally run a container image hosted on GitHub Docker Registry. 

We recommend that you have some experience with Docker and Docker Registry before attending this workshop.

**Comment by meaghanlewis** [comment]
@mebaumb how about this edit?

GitHub Packages is a package management service that makes it easy to use and publish packages in your code. When developing open-source packages, you can use GitHub Actions to help manage the development process.

In this workshop, we'll explore when to use a Package Repository, create a Dockerfile, and build a container image to run in Continuous Integration (CI). Then, we'll show you how to locally run a container image hosted on GitHub Docker Registry and publish your code with GitHub Packages.

During this workshop, we'll be going through this Learn module: https://aka.ms/GHAPackages-8. To follow along, you'll need a GitHub account and some experience with Docker and Docker Registry.

**Comment by mebaumb** [comment]
@meaghanlewis - This looks great! We're not supposed to put the learn module in the description anymore - they're hoping to drive more people to actually register so they will get the link. 

Updated (only change is the last line): 
GitHub Packages is a package management service that makes it easy to use and publish packages in your code. When developing open-source packages, you can use GitHub Actions to help manage the development process.

In this workshop, we'll explore when to use a Package Repository, create a Dockerfile, and build a container image to run in Continuous Integration (CI). Then, we'll show you how to locally run a container image hosted on GitHub Docker Registry and publish your code with GitHub Packages.

To follow along with this workshop, you'll need a GitHub account and some experience with Docker and Docker Registry.

**Comment by meaghanlewis** [comment]
@mebaumb thanks! I guess I missed. the memo about the link to the learn module 😄

**Comment by mebaumb** [comment]
@meaghanlewis - no worries! I feel like it changes all the time :D 

Is this intermediate or beginner content?

**Comment by meaghanlewis** [comment]
this is intermediate content. ill call out the level going forward from here on!

**Comment by mebaumb** [comment]
Thanks! I'll get this into dynamics and published!

**Comment by mebaumb** [comment]
All of the content has been updated in Dynamics. I am waiting for the shortlinks to the learn modules before publishing.

**Comment by meaghanlewis** [comment]
## Instructor notes

**Share this link with attendees at the beginning of the workshop: https://aka.ms/GHAPackages-8**

Let them know this is the content that will be covered, and that after the workshops they should step through to complete the module, including answering the knowledge check questions and rating the module.

This workshop covers using GitHub Actions to publish packages on the GitHub Docker Registry. Be sure to have both a GitHub acount.

**Workshop steps:**

1. It would be helpful to start with an overview of GitHub Packages. Some helpful links include:
    - https://docs.microsoft.com/learn/modules/github-actions-packages/2-what-is-github-packages
    - https://github.com/features/packages
    - https://docs.github.com/packages
 
2. It would also be helpful to give an overview of Docker and Docker Registry: 
    - https://www.docker.com/
    - https://docs.docker.com/registry/
    - https://github.com/docker
  
3. Walk through the Learning Lab for _Publishing to GitHub Packages_: https://lab.github.com/githubtraining/github-actions:-publish-to-github-packages

**Wrapping up:**

- At the end of the workshop, remind attendees to complete the knowledge check and summary so they can get a badge for completing the module.
- Also please encourage them to rate the module 😄
- Share out the survey link: https://aka.ms/Reactor/Survey with the event code (the Reactor contact on the call can give you this)
