### ISSUE TITLE
April 19 - 23 - Contribute to an Open Source Project on GitHub

### ISSUE THREAD

**Issue by mebaumb** [microsoft/ReactorPlanning#233]
# Event Information
| Category | Details |
|-----------|---------|
| Reactor Topic | DevOps and Dev Tools |
| Monthly Topic (if applicable) | <Topic taken from [Azure Dev Marketing](https://aka.ms/DevEdCalFY21H1)> |
| Weekly Topic (if applicable) |  |
| Workshop Topic |  |
| Workshop Duration | | 
| Title | Use GitHub to Contribute to an Open-Source Project |
| Description | GitHub is the largest open source community in the world, with millions of open-source projects. One of GitHub's strengths is how easy it is to collaborate on projects. In this workshop, we'll walk through how easy it is to find and contribute to open-source projects on GitHub. We'll show you how to create pull requests, communicate with the project maintainers to effectively to get your changes accepted and will deep dive into the benefits of getting involved with open-source communities. This is a beginner's level workshop, but you should join this workshop with a GitHub account set up and a basic knowledge of how to navigate and edit files in GitHub. |

# Content
https://aka.ms/GHOSProject-8

# Workshop(s) details
| Date |  Local Start Time |  Location |  Speaker | SharePoint ID | Platform |
|------|-------------------|-----------|----------|---------------|----------|
| April 20, 2021 | 6:30 PM | Bangalore | Devendra Rawat | 13051 |----------|
| April 20, 2021 | 4:00 PM | US/CA/AU | Christian Melendez | 13052 |----------|
| April 21, 2021 | 7:00 PM | Sao Paulo | Flavio Figueiredo | 13053 |----------|
| April 21, 2021 | 7:30 PM | Shanghai | Warren Wong | 13054 |----------|
| April 21, 2021 | 12:00 PM | EMEA | Allen Sanders  | 13055 |----------|

# Event Checklist

## 10 Weeks Prior
- [ ] Reactor Content Team (RCT) opens a new issue for an upcoming local workshop filling in the Event Information and Workshop details tables. RCT member who owns content (content owner) this week will be the assignee.
- [ ] RCT and content owner discuss details of the event in the comments of this issue. RCT adds a _confirmed-event_ label and _local-digital-event_ tag to the issue and adds event to the __Local Digital Events__ project. Issue will appear in the __Upcoming Streams__ column
- [ ] RCT adds a _ready-for-marketing-edit_ label so the RCT can review title and description

## 8 Weeks Prior
- [ ] RCT does a review of title and description and removes the _ready-for-marketing-edit_ label 
- [ ] RCT moves the issue to the __Ready for SharePoint__ column
- [ ] RCT informs the Reactor Marketing Team of the new event information
- [ ] RCT confirms the speaker
- [ ] RCT provides speaker with assets (e.g. slides, overlays) and the survey data for the event
- [ ] RCT moves the issue to the __Content Preparation In Progress__ column

## 5 weeks Prior
- [ ] Content owner opens a PR with the new content for the workshop on the [customer-facing Reactor repository](https://github.com/microsoft/Reactors/tree/main/online-event-resources) and adds the _content-development_ and _local-digital-event_ tag to the PR. 
- [ ] RCT reviews, approves, and merges the changes
- [ ] RCT shares content with the vendor/instructor
- [ ] RCT provides vendor/instructor with assets (e.g. slides, overlays) and the survey data for the event
- [ ] RCT ensures that instructors have received an invite to the workshops and that PM team works with instructors to get setup in the platform (e.g. Teams, Teams Live Event)

## 1 Week Prior
- [ ] Connect vendor/instructor with the PM(s) for the locations where this event has been marketed
- [ ] Check-in with vendor/instructor that they are prepared for the workshop
- [ ] RCT moves the issue to the __Ready to Stream__ column

## During and After Stream
- [ ] Instructor (and optional moderator) run the stream
- [ ] _(Optional)_RCT submits recording to be uploaded to the Reactor YouTube and to be made available on LearnTV
- [ ] RCT moves issue to the __Stream Complete__ column

**Comment by mebaumb** [comment]
@meaghanlewis - What do you think of this? 

Title: Use GitHub to Contribute to an Open-Source Project

Description: GitHub is the largest open source community in the world, with millions of open-source projects. One of GitHub's strengths is how easy it is to collaborate on projects. In this workshop, we'll walk through how easy it is to find and contribute to open-source projects on GitHub. We'll show you how to create pull requests, communicate with the project maintainers to effectively to get your changes accepted and will deep dive into the benefits of getting involved with open-source communities.

This is a beginner's level workshop, but you should join this workshop with a GitHub account set up and a basic knowledge of how to navigate and edit files in GitHub.

**Comment by meaghanlewis** [comment]
@mebaumb. Looks great! I added one sentence in the opening paragraph: "GitHub is the largest open source community in the world, with millions of open-source projects."

**Comment by meaghanlewis** [comment]
## Instructor notes

**Share this link with attendees at the beginning of the workshop:  https://aka.ms/GHOSProject-8**

Let them know this is the content that will be covered, and that following the workshops they should step through to complete the module, including answering the knowledge check questions and rating the module.

This workshop covers using how to contribute to an open-source project.

**Workshop steps:**

1. Start with an overview about GitHub being the home for open source projects. Explain the benefits of contributing to and/or maintaining open-source software. 
 
2. Identify how to find an open source project that needs contributions. Here are some helpful links you might share:
    - https://github.com/search and search by topic. see if projects have issues that need help
    - https://docs.github.com/github/getting-started-with-github/finding-ways-to-contribute-to-open-source-on-github
    - https://github.com/MunGell/awesome-for-beginners
    - https://github.com/showcases/great-for-new-contributors
    - https://goodfirstissue.dev/
    - https://github.com/topics/good-first-issue

3. Explore a repository. Pick a repository and have a look through their **README**, **contributing docs** and **code of conduct.**  Check out which **[open source license](https://choosealicense.com/)** the project has. Then look at the **issues** that are open for contribution. Explain how you can find an issue to work on that's good for your skillset.

4. Walk through how you would submit a Pull Request to an open source project. You can pick an existing project of your choosing, or create a new repository of your own with an issue to fix.
    - Pick an issue and assign yourself to it (first make sure no one else has assigned themselves before you).
    - Fork the repository
    - Start on a fix to the issue
    - Create the pull request
    - Make sure statuses pass
    - Make sure to tag the appropriate people/teams as reviewers
    - Watch for comments and changes on your pull request

5. Explain [GitHub Sponsors](https://github.com/sponsors) and how that works for project maintainers.

**Wrapping up:**

- At the end of the workshop, remind attendees to complete the knowledge check and summary so they can get a badge for completing the module.
- Also please encourage them to rate the module 😄
- Share out the survey link: https://aka.ms/Reactor/Survey with the event code (the Reactor contact on the call can give you this)
