### ISSUE TITLE
April 26 - 30 - Learn the basics of PowerShell

### ISSUE THREAD

**Issue by mebaumb** [microsoft/ReactorPlanning#234]
# Event Information
| Category | Details |
|-----------|---------|
| Reactor Topic | DevOps and Dev Tools |
| Monthly Topic (if applicable) | <Topic taken from [Azure Dev Marketing](https://aka.ms/DevEdCalFY21H1)> |
| Weekly Topic (if applicable) |  |
| Workshop Topic |  |
| Workshop Duration | | 
| Title |  |
| Description | |

# Content
https://aka.ms/IntroPowershell-8

# Workshop(s) details
| Date |  Local Start Time |  Location |  Speaker | SharePoint ID | Platform |
|------|-------------------|-----------|----------|---------------|----------|
| April 27, 2021 | 6:30 PM | Bangalore | Devendra Rawat | 13056 |----------|
| April 27, 2021 | 4:00 PM | US/CA/AU | Allen Sanders | 13057 |----------|
| April 28, 2021 | 7:30 PM | Sao Paulo | Flavio Figueredo | 13058 |----------|
| April 28, 2021 | 7:30 PM | Shanghai | Ryan Chung | 13059 |----------|
| April 28, 2021 | 12:00 PM | EMEA | allen Sanders | 13060 |----------|

# Event Checklist

## 10 Weeks Prior
- [ ] Reactor Content Team (RCT) opens a new issue for an upcoming local workshop filling in the Event Information and Workshop details tables. RCT member who owns content (content owner) this week will be the assignee.
- [ ] RCT and content owner discuss details of the event in the comments of this issue. RCT adds a _confirmed-event_ label and _local-digital-event_ tag to the issue and adds event to the __Local Digital Events__ project. Issue will appear in the __Upcoming Streams__ column
- [ ] RCT adds a _ready-for-marketing-edit_ label so the RCT can review title and description

## 8 Weeks Prior
- [ ] RCT does a review of title and description and removes the _ready-for-marketing-edit_ label 
- [ ] RCT moves the issue to the __Ready for SharePoint__ column
- [ ] RCT informs the Reactor Marketing Team of the new event information
- [ ] RCT confirms the speaker
- [ ] RCT provides speaker with assets (e.g. slides, overlays) and the survey data for the event
- [ ] RCT moves the issue to the __Content Preparation In Progress__ column

## 5 weeks Prior
- [ ] Content owner opens a PR with the new content for the workshop on the [customer-facing Reactor repository](https://github.com/microsoft/Reactors/tree/main/online-event-resources) and adds the _content-development_ and _local-digital-event_ tag to the PR. 
- [ ] RCT reviews, approves, and merges the changes
- [ ] RCT shares content with the vendor/instructor
- [ ] RCT provides vendor/instructor with assets (e.g. slides, overlays) and the survey data for the event
- [ ] RCT ensures that instructors have received an invite to the workshops and that PM team works with instructors to get setup in the platform (e.g. Teams, Teams Live Event)

## 1 Week Prior
- [ ] Connect vendor/instructor with the PM(s) for the locations where this event has been marketed
- [ ] Check-in with vendor/instructor that they are prepared for the workshop
- [ ] RCT moves the issue to the __Ready to Stream__ column

## During and After Stream
- [ ] Instructor (and optional moderator) run the stream
- [ ] _(Optional)_RCT submits recording to be uploaded to the Reactor YouTube and to be made available on LearnTV
- [ ] RCT moves issue to the __Stream Complete__ column

**Comment by mebaumb** [comment]
@meaghanlewis - what do you think about this? 

Title: Introduction to PowerShell

Description: PowerShell is a cross platform command-line shell and scripting language that is built for task automation and configuration management. It started as a framework that allowed users to automate administrative tasks in Windows using cmdlets. Over time it's use has evolved to a cross-platform tool to support many other jobs. You can use PowerShell to interact with cloud resources, store commands and scripts in a text file for easy repeatability, and run batch commands for task automation and pipelines. In this workshop, we'll deep dive into examples of how to use PowerShell, explore cmdlets, create pipelines by connecting a sequence of cmdlets, and format cmdlets to filter for specific data.

This is a beginner's level workshop, but you should join this workshop with a basic familiarity using command-line shell, Visual Studio Code installed, ability to install Visual Studio Code extensions, and the ability to install software on your computer if you're not using a Windows operating system.

**Comment by meaghanlewis** [comment]
@mebaumb made a handful of edits inline. This description looks good to go to me.

What do you think about the title **Learn the basics of PowerShell**?

**Comment by meaghanlewis** [comment]
## Instructor notes

**Share this link with attendees at the beginning of the workshop:  https://aka.ms/IntroPowershell-8**

Let them know this is the content that will be covered, and that following the workshops they should step through to complete the module, including answering the knowledge check questions and rating the module.

This workshop covers an introduction to PowerShell. Getting started, make sure all the attendees have PowerShell installed. You should spend the majority of the workshop in PowerShell.

**Workshop steps:**

1. Start with an overview of PowerShell
    - Features
    - How to install
    - Highlight the PowerShell extension for VS Code
2. Complete the exercise to run PowerShell commands
   - $PSVersionTable
   - $PSVersionTable.PSVersion
   - Could be helpful to show some common commands, and share some kind of [command cheetsheet](https://www.pdq.com/powershell/)
3. Share an overview of cmdlets
   - What are cmdlets
   - Discover cmdlets
4. Complete the exercise on using core cmdlets
    - Locate a command
    - Use Get-Help
    - Discover an object by using Get-Member
5. Create pipelines by connecting cmdlets
6. Complete the exercise to create a pipeline and follow the response

**Wrapping up:**

- At the end of the workshop, remind attendees to complete the knowledge check and summary so they can get a badge for completing the module.
- Also please encourage them to rate the module 😄
- Share out the survey link: https://aka.ms/Reactor/Survey with the event code (the Reactor contact on the call can give you this)
