### ISSUE TITLE
May 3-7 - Use the UNIX shell to wrangle log data

### ISSUE THREAD

**Issue by mebaumb** [microsoft/ReactorPlanning#235]
# Event Information
| Category | Details |
|-----------|---------|
| Reactor Topic | DevOps and Dev Tools |
| Level | Beginner |
| Content | https://aka.ms/UNIXShellData-8 |

# Workshop(s) details
| Date |  Local Start Time |  Location |  Speaker | SharePoint ID | Platform |
|------|-------------------|-----------|----------|---------------|----------|
| May 4, 2021 | 6:30 PM | Bangalore | Devendra Rawat | 13065 |----------|
| May 4, 2021 | 4:00 PM | US/CA/AU | Allen Sanders | 13066 |----------|
| May 5, 2021 | 7:00 PM | Sao Paulo | Fabricio Murai | 13067 |----------|
| May 7, 2021 | 7:30 PM | Shanghai | Ryan Chung | 13068 |----------|
| May 5, 2021 | 12:00 PM | EMEA | Allen Sanders | 13069 |----------|

# Event Checklist

## 10 Weeks Prior
- [ ] Reactor Content Team (RCT) opens a new issue for an upcoming local workshop filling in the Event Information and Workshop details tables. RCT member who owns content (content owner) this week will be the assignee.
- [ ] RCT and content owner discuss details of the event in the comments of this issue. RCT adds a _confirmed-event_ label and _local-digital-event_ tag to the issue and adds event to the __Local Digital Events__ project. Issue will appear in the __Upcoming Streams__ column
- [ ] RCT adds a _ready-for-marketing-edit_ label so the RCT can review title and description

## 8 Weeks Prior
- [ ] RCT does a review of title and description and removes the _ready-for-marketing-edit_ label 
- [ ] RCT moves the issue to the __Ready for SharePoint__ column
- [ ] RCT informs the Reactor Marketing Team of the new event information
- [ ] RCT confirms the speaker
- [ ] RCT provides speaker with assets (e.g. slides, overlays) and the survey data for the event
- [ ] RCT moves the issue to the __Content Preparation In Progress__ column

## 5 weeks Prior
- [ ] Content owner opens a PR with the new content for the workshop on the [customer-facing Reactor repository](https://github.com/microsoft/Reactors/tree/main/online-event-resources) and adds the _content-development_ and _local-digital-event_ tag to the PR. 
- [ ] RCT reviews, approves, and merges the changes
- [ ] RCT shares content with the vendor/instructor
- [ ] RCT provides vendor/instructor with assets (e.g. slides, overlays) and the survey data for the event
- [ ] RCT ensures that instructors have received an invite to the workshops and that PM team works with instructors to get setup in the platform (e.g. Teams, Teams Live Event)

## 1 Week Prior
- [ ] Connect vendor/instructor with the PM(s) for the locations where this event has been marketed
- [ ] Check-in with vendor/instructor that they are prepared for the workshop
- [ ] RCT moves the issue to the __Ready to Stream__ column

## During and After Stream
- [ ] Instructor (and optional moderator) run the stream
- [ ] _(Optional)_RCT submits recording to be uploaded to the Reactor YouTube and to be made available on LearnTV
- [ ] RCT moves issue to the __Stream Complete__ column

**Comment by mebaumb** [comment]
Hey @meaghanlewis - what do you think about this? 

Title: Use the UNIX Shell to Wrangle Log Data
Description: Transforming data from one format to another is a very common task for developers. You often have to deal with raw data that needs to be manipulated or transformed to be useable. In this session, we'll walk through how to wrangle - or transform - data using the UNIX shell. You'll be introduced to some commonly used tools and to the basics of regular expressions (regex). You'll learn commands to help you do basic file inspections, create and append files, do pattern matching and basic text transformations. 

This is a beginner's workshop, but it is recommended that you have some familiarity with the command line and basic shell commands.

**Comment by meaghanlewis** [comment]
thank you @mebaumb! This looks great to me! I just made a few little tweaks.

**Comment by meaghanlewis** [comment]
## Instructor notes

**Share this link with attendees at the beginning of the workshop: https://aka.ms/UNIXShellData-8**

Let them know this is the content that will be covered, and that following the workshops they should step through to complete the module, including answering the knowledge check questions and rating the module.

This workshop will teach learners how to use the UNIX shell to wrangle data and inspect data files.

**Workshop steps:**

1. **Perform file inspection in the UNIX shell**. Remind attendees that they need an Azure account. This unit uses the Cloud Shell within the unit as a sandbox. Walk through the steps, running the commands in the shell to get familiar with using the terminal to explore files.
2. **Basic file manipulation with the cat command**. Get familiar with the cat command to display and create content.
3. **Introduction to regular expressions**. Talk about the importance of using regex and share helpful resources such as: https://regex101.com/. Walk through the most commonly used regular expressions
4. **Use the grep command to match regular expressions** Explain and demonstrate how the grep command works.
5. **Introduction to the stream editor**. Get familiar with the sed tool for text parsing and manipulation.
6. **Use pipes and filters to put it all together**. Use all the concepts from this module to inspect files and manipulate data.

**Wrapping up:**

- Walk through the knowledge check questions with attendees
- Remind attendees to complete the knowledge check and summary so they can get a badge for completing the module. Also please encourage them to rate the module 😄
- Share out the survey link: https://aka.ms/Reactor/Survey with the event code (the Reactor contact on the call can give you this)
