### ISSUE TITLE
May 10 - 14 - Get started with the Windows Subsystem for Linux 

### ISSUE THREAD

**Issue by mebaumb** [microsoft/ReactorPlanning#236]
# Event Information
| Category | Details |
|-----------|---------|
| Reactor Topic | DevOps and Dev Tools |
| Level | Beginner | 
| Content | https://aka.ms/WindowsSSLinux-8 |

One of the most important decisions that you need to make as a developer is what tools and development environments you want to use. Windows Subsystem for Linux (WSL) lets you use the tools that you want, in the environment you want, on the hardware you want. In the past, most developers have opted to use macOS or Linux because the most common development tools, languages and frameworks are easy to install and and work with on those operating systems. With WSL, you can easily run a GNU/Linux environment directly on Windows! In this workshop, we'll show you how to install the tools, set them up, and use WSL to create a website!

# Workshop(s) details
| Date |  Local Start Time |  Location |  Speaker | SharePoint ID | Platform |
|------|-------------------|-----------|----------|---------------|----------|
| May 11, 2021 | 6:30 PM | Bangalore | Devendra Rawat | 13070 |----------|
| May 11, 2021 | 4:00 PM | US/CA/AU | Allen Sanders | 13071 |----------|
| May 12, 2021 | 7:00 PM | Sao Paulo | Fabricio Murai | 13072 |----------|
| May 12, 2021 | 7:30 PM | Shanghai | Ryan Chung | 13073 |----------|
| May 12, 2021 | 12:00 PM | EMEA | Allen Sanders | 13074 |----------|

**Comment by mebaumb** [comment]
@meaghanlewis - What do you think about this? 

 Title: Get Started Using Windows Subsystem for Linux
Description: One of the most important decisions that you need to make as a developer is what tools and development environments you want to use. Windows Subsystem for Linux (WSL) lets you use the tools that you want, in the environment you want, on the hardware you want. In the past, most developers have opted to use macOS or Linux because the most common development tools, languages and frameworks are easy to install and and work with on those operating systems. With WSL, you can easily run a GNU/Linux environment directly on Windows! In this workshop, we'll show you how to install the tools, set them up, and use WSL to create a website!

**Comment by meaghanlewis** [comment]
Thanks @mebaumb! Added a few edits inline.

**Comment by meaghanlewis** [comment]
## Instructor notes

**Share this link with attendees at the beginning of the workshop: https://aka.ms/WindowsSSLinux-8**

As a pre-req for this workshop, attendees must be running the current release of Windows 10. It will also be helpful if attendees have Visual Studio Code installed. This is a fairly long module, so some of it might need to be left to the attendees to complte after the workshop.

**Workshop steps:**
1. Start with an introduction on the benefits that WSL provides
2. Walk through the steps to enable WSL on your computer. Make sure that everyone is able to do this successfully.
3. Get familiar with the command line. Create and run a sumple Python app.
4. Create a website with Node.js. Start by explaining what Node is, and how it's used. Explain the package managers available for Linux, and then install all the tools needed with the command line.
5. Walk through the steps to set up your dev environment with Visual Studio Code. Allow 5-10 minutes to install VS Code, Git for Windows, and the WSL extension. Then update your Node.js app and track changes with Git.

**Wrapping up:**

After setting up your environment with Visual Studio Code, you will likely be out of time. Encourage attendees to complete the rest of the module on their own.
- Remind attendees to complete the knowledge check and summary so they can get a badge for completing the module. Also please encourage them to rate the module 😄
- Share out the survey link: https://aka.ms/Reactor/Survey with the event code (the Reactor contact on the call can give you this)
