### ISSUE TITLE
May 17 - 21  - Explore the art world by using RESTFUL APIs 

### ISSUE THREAD

**Issue by mebaumb** [microsoft/ReactorPlanning#238]
# Event Information
| Category | Details |
|-----------|---------|
| Reactor Topic | Coding, Languages, and Frameworks |
| Level | Beginner | 
| Content | https://aka.ms/RESTfulAPIArt-8 |

# Workshop(s) details
| Date |  Local Start Time |  Location |  Speaker | SharePoint ID | Platform |
|------|-------------------|-----------|----------|---------------|----------|
| May 18, 2021 | 6:30 PM | Bangalore |  | 13080 |----------|
| May 18, 2021 | 4:00 PM | US/CA/AU |  | 13081 |----------|
| May 19, 2021 | 7:00 PM | Sao Paulo |  | 13082 |----------|
| May 19, 2021 | 7:30 PM | Shanghai |  | 13083 |----------|
| May 19, 2021 | 12:00 PM | EMEA |  | 13084 |----------|

**Comment by mebaumb** [comment]
@meaghanlewis - What do you think about this?

Title: Explore the Art World by Using RESTful APIs
Description: API, short for application programming interface, is a convenient way to interface between a user and a product. In this workshop, we will dive deep into what an API is and how it's used. Then we'll show you how to build your own API using the REST protocols to get images of artwork made public by museums around the world. You will also learn how to connect to external APIs and query two different sets of data. This is a beginner's workshop that will give you the confidence to start using RESTful APIs on your own!

**Comment by meaghanlewis** [comment]
thank you @mebaumb! Added a few edits inline.

**Comment by meaghanlewis** [comment]
## Instructor notes

**Share this link with attendees at the beginning of the workshop: https://aka.ms/RESTfulAPIArt-8**

This workshop will teach learners how to build and query a basic API.

**Workshop steps:**

1. Explain what an API is. Share any examples or resources that you think are helpful. Encourage attendees to watch Burke Holland's explanation of an API after the workshop.
2. Focusing your attention on a terminal or command prompt, follow the steps to set up a REST API server and query a database. Then explain the different parts of a REST API call including the endpoint, method, headers, and data. Walk through the knowledge check questions.
3. Introduce the Metroplitan API and query data from it.
4. Discuss the different authentication strategies
5. Introduce and query the Cooper Hewitt API. Use the API to explore different status codes that might be returned. Share any helpful resources about status codes, such as: https://en.wikipedia.org/wiki/List_of_HTTP_status_codes
6. Choose a development language and walk through the steps to work with the Cooper Hewitt API using a library.

**Wrapping up:**

- Walk through the knowledge check questions with attendees
- Remind attendees to complete the knowledge check and summary so they can get a badge for completing the module. Also please encourage them to rate the module 😄
- Share out the survey link: https://aka.ms/Reactor/Survey with the event code (the Reactor contact on the call can give you this)
