### ISSUE TITLE
May 31 - June 4 - Get started with TypeScript 

### ISSUE THREAD

**Issue by mebaumb** [microsoft/ReactorPlanning#239]
# Event Information
| Category | Details |
|-----------|---------|
| Reactor Topic | Coding, Languages, and Frameworks |
| Title | Get started with TypeScript |
| Description | TypeScript offers all the features of JavaScript, plus an additional layer on top of these - the TypeScript type system. In this workshop, you'll be introduced to the TypeScript language, why it was created, and learn how to use it for JavaScript development. You'll set up a development environment with Visual Studio Code and create your first TypeScript project. Then you'll learn about the available data types and shows how to associate them with variables. Leave this workshop with an understanding of what TypeScript is and how to write simple programs. |
| Content | Get started with TypeScript: https://aka.ms/GetStartedTypeScript Declare variable types: https://aka.ms/VariablesTypeScript |

# Workshop(s) details
| Date |  Local Start Time |  Location |  Speaker | SharePoint ID | Platform |
|------|-------------------|-----------|----------|---------------|----------|
| June 1, 2021 | 6:30 PM | Bangalore | Devendra Rawat | 13085 |----------|
| June 1, 2021 | 4:00 PM | US/CA/AU | Allen Sanders | 13086 |----------|
| June 2, 2021 | 7:00 PM | Sao Paulo | Rafael dos Santos | 13087 |----------|
| June 2, 2021 | 7:30 PM | Shanghai | Ryan Chung | 13088 |----------|
| June 2, 2021 | 12:00 PM | EMEA | Allen Sanders | 13089 |----------|

# Event Checklist

## 10 Weeks Prior
- [ ] Reactor Content Team (RCT) opens a new issue for an upcoming local workshop filling in the Event Information and Workshop details tables. RCT member who owns content (content owner) this week will be the assignee.
- [ ] RCT and content owner discuss details of the event in the comments of this issue. RCT adds a _confirmed-event_ label and _local-digital-event_ tag to the issue and adds event to the __Local Digital Events__ project. Issue will appear in the __Upcoming Streams__ column
- [ ] RCT adds a _ready-for-marketing-edit_ label so the RCT can review title and description

## 8 Weeks Prior
- [ ] RCT does a review of title and description and removes the _ready-for-marketing-edit_ label 
- [ ] RCT moves the issue to the __Ready for SharePoint__ column
- [ ] RCT informs the Reactor Marketing Team of the new event information
- [ ] RCT confirms the speaker
- [ ] RCT provides speaker with assets (e.g. slides, overlays) and the survey data for the event
- [ ] RCT moves the issue to the __Content Preparation In Progress__ column

## 5 weeks Prior
- [ ] Content owner opens a PR with the new content for the workshop on the [customer-facing Reactor repository](https://github.com/microsoft/Reactors/tree/main/online-event-resources) and adds the _content-development_ and _local-digital-event_ tag to the PR. 
- [ ] RCT reviews, approves, and merges the changes
- [ ] RCT shares content with the vendor/instructor
- [ ] RCT provides vendor/instructor with assets (e.g. slides, overlays) and the survey data for the event
- [ ] RCT ensures that instructors have received an invite to the workshops and that PM team works with instructors to get setup in the platform (e.g. Teams, Teams Live Event)

## 1 Week Prior
- [ ] Connect vendor/instructor with the PM(s) for the locations where this event has been marketed
- [ ] Check-in with vendor/instructor that they are prepared for the workshop
- [ ] RCT moves the issue to the __Ready to Stream__ column

## During and After Stream
- [ ] Instructor (and optional moderator) run the stream
- [ ] _(Optional)_RCT submits recording to be uploaded to the Reactor YouTube and to be made available on LearnTV
- [ ] RCT moves issue to the __Stream Complete__ column

**Comment by meaghanlewis** [comment]
@mebaumb here's my first pass at a description for this:

TypeScript offers all the features of JavaScript, plus the additional layer of the TypeScript type system. In this workshop, you'll be introduced to the TypeScript language, why it was created, and learn how to use it for JavaScript development. You'll set up a development environment with Visual Studio Code and create your first TypeScript project. Then you'll learn about the available data types and shows how to associate them with variables. Leave this workshop with an understanding of what TypeScript is and how to write simple programs.

And I changed the title to: **Get started with TypeScript** if that's okay.

**Comment by mebaumb** [comment]
This looks great! I edited the 1st sentence a bit - but other than that I think it looks really good!

Am I good to get this published?

**Comment by meaghanlewis** [comment]
Cool, thanks @mebaumb. Good to publish.

**Comment by meaghanlewis** [comment]
## Instructor notes

**Share these link with attendees at the beginning of the workshop: https://aka.ms/GetStartedTypeScript and https://aka.ms/VariablesTypeScript**

This workshop is an introduction to TypeScript. It includes exercises to get started using TypeScript and to get familiar with types and variables.

**Workshop steps:**
1. Provide an overview of what TypeScript is: https://www.typescriptlang.org/. Spend some time using the Playground: https://www.typescriptlang.org/play and going through simple eamples there. Explain that the workshop will involve writing and running examples in both the Playground and Visual Studio Code.
2. Walk through the process to install TypeScript, npm and Visual Studio Code. Give attendees enough time to complete these steps.
3. Walk through the exercise to create a new TypeScript project in Visual Studio Code.
4. Go through the knowledge check and summary.
5. Move on to the variables module and start out with an overview of types. You can use the Playground to create variables and show examples of primitive types.
6. Walk through the enums exercise.
7. Discuss any and unknown types
8. Discuss union and intersection types.
9. Discuss collection types
10. Complete the lab on using types in TypeScript in Visual Studio Code.
11. Go through the knowledge check and summary.

**Wrapping up:**
- Please encourage attendees to rate the module 😄
- Share out the survey link: https://aka.ms/Reactor/Survey with the event code (the Reactor contact on the call can give you this)
