### ISSUE TITLE
Aug 12 - Drinking from the IoT firehose

### ISSUE THREAD

**Issue by meaghanlewis** [microsoft/ReactorPlanning#24]
# Event Information
| Category | Details |
|-----------|---------|
| Reactor Topic | IoT |
| Monthly Topic (if applicable) | Powerful APIs |
| Weekly Topic (if applicable) | <Topic decided by RCT if relevant> |
| Stream Topic | <2-5 words describing the topic> |
| Stream Date | August 12, 2020> | 
| Stream Time | 9:00 PT | 
| Stream Duration | 60 mins | 
| Title | Drinking from the IoT Data Firehose |
| Description | IoT generates data—A LOT of data. To add to the complexity, this data can be streamed from a variety of devices and run the scope from a home with a single sensor to a factory with millions of them. So…where does all this data go once it is sent? In this session, we'll take that next step to look at how you can take the glut of IoT data and make it useful. We’ll query the data it in real time, analyzing it with code and storing it in a database, such as a CosmosDB, for future offline analysis. |
| Speaker | Jim Bennett |
| Moderator | TBD |
| Event ID | 7870 |

Additional Resources:  
<Additional resources that can be linked from social media for promotion or added to the description of VOD>

# Event Checklist

## 10 Weeks Prior
- [X] Reactor Content Team (RCT) or Speaker opens a new issue for an upcoming stream filling in the Event Information table. Both RCT and Speaker are marked as assignees.
- [X] RCT and Speaker discuss details of the event in the comments of this issue. RCT adds a _confirmed-event_ label and _global-twitch-event_ tag to the issue and adds event to the __Global Live Streams__ project. Issue will appear in the __Upcoming Streams__ column
- [X] Speaker adds a _ready-for-marketing-edit_ label so the RCT can review title and description

## 8 Weeks Prior
- [x] RCT does a review of title and description and removes the _ready-for-marketing-edit_ label 
- [x] RCT moves the issue to the __Ready for SharePoint__ column
- [x] RCT informs the Reactor Marketing Team of the new event information
- [ ] RCT provides speaker with assets (e.g. slides, overlays) and the survey data for the event
- [x] RCT moves the issue to the __MONTH Streams Prep__ column (according to the month it will be streamed in)

## 2 Weeks Prior *(Done in /microsoft/Reactors)*
- [ ] Speaker opens a PR with the new content for the stream on the [customer-facing Reactor repository](https://github.com/microsoft/Reactors) and adds the _content-development_ and _global-twitch-event_ tag to the PR. 
- [ ] Speaker adds to the same PR a modification to the [Streaming README](https://github.com/microsoft/Reactors/tree/main/Online) to include their stream information.
- [ ] Speaker adds the RCT assigned to the issue as the reviewer when it is ready for review/merge
- [ ] RCT reviews, approves, and merges the changes

## 1 Week Prior
- [ ] Speaker and Moderator test setup for streaming (instructions coming soon)
- [ ] RCT checks in with the speaker and moves the issue to the __Ready to Stream__ column

## During and After Stream
- [ ] Speaker and Moderator run the stream
- [x] RCT submits recording to be uploaded to the Reactor YouTube and to be made available on LearnTV
- [x] RCT moves issue to the __Stream Complete__ column

**Comment by drguthals** [comment]
👋 @jimbobbennett 
We will be using this to make sure you have everything you need for your stream in August :)

You don't need to worry about checking things off here, but we look forward to supporting you on your stream!

One question:
Do you have a moderator for this session?

**Comment by jimbobbennett** [comment]
Nope, haven't planned that far yet.

**Comment by drguthals** [comment]
@jimbobbennett - Once you do let us know so we can make sure they also get the calendar invite :)

**Comment by jimbobbennett** [comment]
Will do. When will you be sending the calendar invites as I don’t have one for this stream?

**Comment by KimberlyBolton1** [comment]
Session recorded and uploaded to YouTube: https://www.youtube.com/watch?v=qKINxxyKTOY&t=45s. Closing issue.
