### ISSUE TITLE
June 7 - 11 - Implement interfaces in TypeScript

### ISSUE THREAD

**Issue by mebaumb** [microsoft/ReactorPlanning#240]
# Event Information
| Category | Details |
|-----------|---------|
| Reactor Topic | Coding, Languages, and Frameworks |
| Title | Implement interfaces in TypeScript |
| Description | In TypeScript, you can use interfaces as you would in traditional object-oriented programming. You can also use interfaces to define object types and this is the primary focus of this module. This workshop will explain the reasons for using an interface in TypeScript, and teach you how to declare, instantiate and extend an interface. No prior knowledge of TypeScript is required,  but you should already have Git, Visual Studio Code, and Node.js installed. |
| Level | Beginner |
| Content | Implement Interfaces: https://aka.ms/InterfacesTypeScript |

# Workshop(s) details
| Date |  Local Start Time |  Location |  Speaker | SharePoint ID | Platform |
|------|-------------------|-----------|----------|---------------|----------|
| June 8, 2021 | 6:30 PM | Bangalore |  | 13090 |----------|
| June 8, 2021 | 4:00 PM | US/CA/AU |  | 13091 |----------|
| June 9, 2021 | 7:00 PM | Sao Paulo |  | 13092 |----------|
| June 9, 2021 | 7:30 PM | Shanghai |  | 13093 |----------|
| June 9, 2021 | 12:00 PM | EMEA |  | 13094 |----------|

# Event Checklist

## 10 Weeks Prior
- [ ] Reactor Content Team (RCT) opens a new issue for an upcoming local workshop filling in the Event Information and Workshop details tables. RCT member who owns content (content owner) this week will be the assignee.
- [ ] RCT and content owner discuss details of the event in the comments of this issue. RCT adds a _confirmed-event_ label and _local-digital-event_ tag to the issue and adds event to the __Local Digital Events__ project. Issue will appear in the __Upcoming Streams__ column
- [ ] RCT adds a _ready-for-marketing-edit_ label so the RCT can review title and description

## 8 Weeks Prior
- [ ] RCT does a review of title and description and removes the _ready-for-marketing-edit_ label 
- [ ] RCT moves the issue to the __Ready for SharePoint__ column
- [ ] RCT informs the Reactor Marketing Team of the new event information
- [ ] RCT confirms the speaker
- [ ] RCT provides speaker with assets (e.g. slides, overlays) and the survey data for the event
- [ ] RCT moves the issue to the __Content Preparation In Progress__ column

## 5 weeks Prior
- [ ] Content owner opens a PR with the new content for the workshop on the [customer-facing Reactor repository](https://github.com/microsoft/Reactors/tree/main/online-event-resources) and adds the _content-development_ and _local-digital-event_ tag to the PR. 
- [ ] RCT reviews, approves, and merges the changes
- [ ] RCT shares content with the vendor/instructor
- [ ] RCT provides vendor/instructor with assets (e.g. slides, overlays) and the survey data for the event
- [ ] RCT ensures that instructors have received an invite to the workshops and that PM team works with instructors to get setup in the platform (e.g. Teams, Teams Live Event)

## 1 Week Prior
- [ ] Connect vendor/instructor with the PM(s) for the locations where this event has been marketed
- [ ] Check-in with vendor/instructor that they are prepared for the workshop
- [ ] RCT moves the issue to the __Ready to Stream__ column

## During and After Stream
- [ ] Instructor (and optional moderator) run the stream
- [ ] _(Optional)_RCT submits recording to be uploaded to the Reactor YouTube and to be made available on LearnTV
- [ ] RCT moves issue to the __Stream Complete__ column

**Comment by meaghanlewis** [comment]
@mebaumb this description is ready for your review:

In TypeScript, you can use interfaces as you would in traditional object-oriented programming. You can also use interfaces to define object types and this is the primary focus of this module. This workshop will explain the reasons for using an interface in TypeScript, and teach you how to declare, instantiate and extend an interface. No prior knowledge of TypeScript is required,  but you should already have Git, Visual Studio Code, and Node.js installed.

I also changed the title of this workshop to be more specific.

**Comment by mebaumb** [comment]
This also looks great! No edits!

Should I go get this published?

**Comment by meaghanlewis** [comment]
@mebaumb yes, you can go ahead and get this published. thanks!

**Comment by meaghanlewis** [comment]
## Instructor notes

**Share this link with attendees at the beginning of the workshop: https://aka.ms/InterfacesTypeScript**


**Workshop steps:**
1. Start with an overview of interfaces, and how this is specific to TypeScript and other object-oriented programming languages (not JavaScript). Share the learning objectives and what to expect in this workshop.
2. Provide some examples of interfaces, the reasons for using them, and how an interface is different from a type alias.
3. Go through the exercise to declare and instantiate an interface in the Playground: https://www.typescriptlang.org/play.
4. Walk through the exercise to extend an interface.
5. Go through the exercises in the lab on using interfaces in TypeScript. These examples are to be completed in VS Code.
6. Go through the knowledge check and summary.

**Wrapping up:**
- Please encourage attendees to rate the module 😄
- Share out the survey link: https://aka.ms/Reactor/Survey with the event code (the Reactor contact on the call can give you this)
