### ISSUE TITLE
June 14 - 18 - Get started with Vue

### ISSUE THREAD

**Issue by mebaumb** [microsoft/ReactorPlanning#241]
# Event Information
| Category | Details |
|-----------|---------|
| Reactor Topic |  Coding, Languages, and Frameworks |
| Title |  Get started with Vue |
| Description | Vue.js is a progressive web framework that allows developers to get up and running quickly, with just the addition of a script tag. But Vue.js can also grow with you. You can use it to create large scalable applications. In this workshop, you'll explore the core concepts of Vue.js and how to get started. To best follow along, you'll need knowledge in the following areas: HTML, CSS, Git, npm, and JavaScript. |
| Level | Beginner | 
| Content | https://aka.ms/GetStartedVue |

# Workshop(s) details
| Date |  Local Start Time |  Location |  Speaker | SharePoint ID | Platform |
|------|-------------------|-----------|----------|---------------|----------|
| June 15, 2021 | 6:30 PM | Bangalore |  | 13095 |----------|
| June 15, 2021 | 4:00 PM | US/CA/AU |  | 13096 |----------|
| June 16, 2021 | 7:00 PM | Sao Paulo |  | 13097 |----------|
| June 16, 2021 | 7:30 PM | Shanghai |  | 13098 |----------|
| June 16, 2021 | 12:00 PM | EMEA |  | 13099 |----------|

# Event Checklist

## 10 Weeks Prior
- [ ] Reactor Content Team (RCT) opens a new issue for an upcoming local workshop filling in the Event Information and Workshop details tables. RCT member who owns content (content owner) this week will be the assignee.
- [ ] RCT and content owner discuss details of the event in the comments of this issue. RCT adds a _confirmed-event_ label and _local-digital-event_ tag to the issue and adds event to the __Local Digital Events__ project. Issue will appear in the __Upcoming Streams__ column
- [ ] RCT adds a _ready-for-marketing-edit_ label so the RCT can review title and description

## 8 Weeks Prior
- [ ] RCT does a review of title and description and removes the _ready-for-marketing-edit_ label 
- [ ] RCT moves the issue to the __Ready for SharePoint__ column
- [ ] RCT informs the Reactor Marketing Team of the new event information
- [ ] RCT confirms the speaker
- [ ] RCT provides speaker with assets (e.g. slides, overlays) and the survey data for the event
- [ ] RCT moves the issue to the __Content Preparation In Progress__ column

## 5 weeks Prior
- [ ] Content owner opens a PR with the new content for the workshop on the [customer-facing Reactor repository](https://github.com/microsoft/Reactors/tree/main/online-event-resources) and adds the _content-development_ and _local-digital-event_ tag to the PR. 
- [ ] RCT reviews, approves, and merges the changes
- [ ] RCT shares content with the vendor/instructor
- [ ] RCT provides vendor/instructor with assets (e.g. slides, overlays) and the survey data for the event
- [ ] RCT ensures that instructors have received an invite to the workshops and that PM team works with instructors to get setup in the platform (e.g. Teams, Teams Live Event)

## 1 Week Prior
- [ ] Connect vendor/instructor with the PM(s) for the locations where this event has been marketed
- [ ] Check-in with vendor/instructor that they are prepared for the workshop
- [ ] RCT moves the issue to the __Ready to Stream__ column

## During and After Stream
- [ ] Instructor (and optional moderator) run the stream
- [ ] _(Optional)_RCT submits recording to be uploaded to the Reactor YouTube and to be made available on LearnTV
- [ ] RCT moves issue to the __Stream Complete__ column

**Comment by meaghanlewis** [comment]
@mebaumb updated title and description are ready for your review!

**Comment by meaghanlewis** [comment]
## Instructor notes

**Share this link with attendees at the beginning of the workshop: https://aka.ms/GetStartedVue**

This workshop is an introduction to Vue. It starts with an overview, and then is pretty interactive to allow hands-on experience with create Vue apps. This content runs pretty short, so please walk things slowly and make sure attendees are able to follow along with the exercises.

**Workshop steps:**
1. Provide an overview of what Vue.js is: https://vuejs.org/. Discuss the overview and what makes it unique.
2. Install the framework, create a Vue app, and then register it on the page
3. Create an app by using Vue.js
4. Learn about and practice attribute binding
5. Walk through the knowledge check questions and summary

**Wrapping up:**
- Encourage questions from attendees
- Please encourage attendees to rate the module 😄
- Share out the survey link: https://aka.ms/Reactor/Survey with the event code (the Reactor contact on the call can give you this)

**Comment by mebaumb** [comment]
> @mebaumb updated title and description are ready for your review!

Looks good to me! I will get this published!
