### ISSUE TITLE
June 21 - 25 - Create dynamic pages in Vue.js

### ISSUE THREAD

**Issue by mebaumb** [microsoft/ReactorPlanning#242]
# Event Information
| Category | Details |
|-----------|---------|
| Reactor Topic | Coding, Languages, and Frameworks |
| Title | Create dynamic pages in Vue.js | 
| Description | One of the goals of any web framework is to dynamically update the dynamically based on data values. In this workshop, explore how to make your page dynamic based on those values and how to display lists of information and render content conditionally. You'll see how to add forms to a Vue.js page and respond to user events. You'll also see how to add computed values that can be calculated based on updates to the data. It is recommended that you have familiarity with HTML, CSS, Git, npm and JavaSctipt. |
| Level | Beginner | 
| Content | https://aka.ms/VueDynamicRendering  and https://aka.ms/VueDataEvents |

# Workshop(s) details
| Date |  Local Start Time |  Location |  Speaker | SharePoint ID | Platform |
|------|-------------------|-----------|----------|---------------|----------|
| June 22, 2021 | 6:30 PM | Bangalore | Devendra Rawat | 13100 |----------|
| June 22, 2021 | 4:00 PM | US/CA/AU | Allen Sanders | 13101 |----------|
| June 23, 2021 | 7:00 PM | Sao Paulo | Rafael dos Santos | 13102 |----------|
| June 23, 2021 | 7:30 PM | Shanghai | Ryan Chung | 13103 |----------|
| June 23, 2021 | 12:00 PM | EMEA | Allen Sanders | 13104 |----------|

# Event Checklist

## 10 Weeks Prior
- [ ] Reactor Content Team (RCT) opens a new issue for an upcoming local workshop filling in the Event Information and Workshop details tables. RCT member who owns content (content owner) this week will be the assignee.
- [ ] RCT and content owner discuss details of the event in the comments of this issue. RCT adds a _confirmed-event_ label and _local-digital-event_ tag to the issue and adds event to the __Local Digital Events__ project. Issue will appear in the __Upcoming Streams__ column
- [ ] RCT adds a _ready-for-marketing-edit_ label so the RCT can review title and description

## 8 Weeks Prior
- [ ] RCT does a review of title and description and removes the _ready-for-marketing-edit_ label 
- [ ] RCT moves the issue to the __Ready for SharePoint__ column
- [ ] RCT informs the Reactor Marketing Team of the new event information
- [ ] RCT confirms the speaker
- [ ] RCT provides speaker with assets (e.g. slides, overlays) and the survey data for the event
- [ ] RCT moves the issue to the __Content Preparation In Progress__ column

## 5 weeks Prior
- [ ] Content owner opens a PR with the new content for the workshop on the [customer-facing Reactor repository](https://github.com/microsoft/Reactors/tree/main/online-event-resources) and adds the _content-development_ and _local-digital-event_ tag to the PR. 
- [ ] RCT reviews, approves, and merges the changes
- [ ] RCT shares content with the vendor/instructor
- [ ] RCT provides vendor/instructor with assets (e.g. slides, overlays) and the survey data for the event
- [ ] RCT ensures that instructors have received an invite to the workshops and that PM team works with instructors to get setup in the platform (e.g. Teams, Teams Live Event)

## 1 Week Prior
- [ ] Connect vendor/instructor with the PM(s) for the locations where this event has been marketed
- [ ] Check-in with vendor/instructor that they are prepared for the workshop
- [ ] RCT moves the issue to the __Ready to Stream__ column

## During and After Stream
- [ ] Instructor (and optional moderator) run the stream
- [ ] _(Optional)_RCT submits recording to be uploaded to the Reactor YouTube and to be made available on LearnTV
- [ ] RCT moves issue to the __Stream Complete__ column

**Comment by meaghanlewis** [comment]
@mebaumb this is ready for your review!

**Comment by meaghanlewis** [comment]
## Instructor notes

**Share these link with attendees at the beginning of the workshop:**
  - **https://aka.ms/VueDynamicRendering**
  - **https://aka.ms/VueDataEvents**

This workshop covers two short modules on dynamic displays and data events.

**Workshop steps:**
1. Start with an introduction to dynamic displays. Explain the learning objectives for this module.
2. Learn how to render lists.
3. Learn how to use conditional rendering.
4. Walk through knowledge check and summary
5. Move on to the data and events module. Start with an overview of dynamic data and events.
6. Explore how to work with forms.
7. Add event handlers
8. Add computed properties
9. Walk through knowledge check and summary

**Wrapping up:**
- Please encourage attendees to rate the module 😄
- Share out the survey link: https://aka.ms/Reactor/Survey with the event code (the Reactor contact on the call can give you this)

**Comment by mebaumb** [comment]
@meaghanlewis I think the first sentence has a typo, I updated the first sentence below: 
One of the goals of any web framework is to dynamically update the page based on data values. In this workshop, explore how to make your page dynamic based on those values and how to display lists of information and render content conditionally. You'll see how to add forms to a Vue.js page and respond to user events. You'll also see how to add computed values that can be calculated based on updates to the data. It is recommended that you have familiarity with HTML, CSS, Git, npm and JavaSctipt.

**Comment by fabriciomurai** [comment]
@meaghanlewis Based on the description of the workshop steps 1-4, I think the link to be shared with the attendees should be
[https://docs.microsoft.com/pt-br/learn/modules/vue-dynamic-rendering/](https://docs.microsoft.com/pt-br/learn/modules/vue-dynamic-rendering/) instead of https://aka.ms/VueCliComponents.

CLI components are covered in another workshop.

**Comment by mebaumb** [comment]
@fabriciomurai - You're absolutely correct, I have edited the instructor notes to reflect the change.
