### ISSUE TITLE
Aug 13- Dynamic development with Azure Static Web Apps

### ISSUE THREAD

**Issue by drguthals** [microsoft/ReactorPlanning#25]
# Event Information
| Category | Details |
|-----------|---------|
| Reactor Topic | Coding, Languages, and Frameworks |
| Monthly Topic (if applicable) | <Topic taken from [Azure Dev Marketing](https://aka.ms/DevEdCalFY21H1)> |
| Weekly Topic (if applicable) | <Topic decided by RCT if relevant> |
| Stream Topic | <2-5 words describing the topic> |
| Stream Date | Aug 13, 2020 | 
| Stream Time | 9:00 am PT | 
| Stream Duration | 120 | 
| Title | Use Azure Static Web Apps to Take the Headache out of Web Dev |
| Description | Most developers want to focus on writing code. At the same time, they need deployment to be seamless, server architecture to be invisible, and scaling to be automatic. Enter Azure Static Web Apps. This (currently in preview) service enables you to write your client-side code using the framework you love, create back-end code using any language you prefer, and employ GitHub and Azure to take care of the rest! Join this session to see how you can use Azure Static Web Apps for easier dynamic web development. |
| Speaker | Christopher Harrison |
| Moderator | <Name or GitHub alias> |
| SharePoint ID | 7846 |  

Additional Resources:  
<Additional resources that can be linked from social media for promotion or added to the description of VOD>

# Event Checklist

## 10 Weeks Prior
- [x] Reactor Content Team (RCT) or Speaker opens a new issue for an upcoming stream filling in the Event Information table. Both RCT and Speaker are marked as assignees.
- [x] RCT and Speaker discuss details of the event in the comments of this issue. RCT adds a _confirmed-event_ label and _global-twitch-event_ tag to the issue and adds event to the __Global Live Streams__ project. Issue will appear in the __Upcoming Streams__ column
- [x] Speaker adds a _ready-for-marketing-edit_ label so the RCT can review title and description

## 8 Weeks Prior
- [x] RCT does a review of title and description and removes the _ready-for-marketing-edit_ label 
- [x] RCT moves the issue to the __Ready for SharePoint__ column
- [x] RCT informs the Reactor Marketing Team of the new event information
- [ ] RCT provides speaker with assets (e.g. slides, overlays) and the survey data for the event
- [ ] RCT moves the issue to the __MONTH Streams Prep__ column (according to the month it will be streamed in)

## 2 Weeks Prior *(Done in /microsoft/Reactors)*
- [ ] Speaker opens a PR with the new content for the stream on the [customer-facing Reactor repository](https://github.com/microsoft/Reactors) and adds the _content-development_ and _global-twitch-event_ tag to the PR. 
- [ ] Speaker adds to the same PR a modification to the [Streaming README](https://github.com/microsoft/Reactors/tree/main/Online) to include their stream information.
- [ ] Speaker adds the RCT assigned to the issue as the reviewer when it is ready for review/merge
- [ ] RCT reviews, approves, and merges the changes

## 1 Week Prior
- [ ] Speaker and Moderator test setup for streaming (instructions coming soon)
- [ ] RCT checks in with the speaker and moves the issue to the __Ready to Stream__ column

## During and After Stream
- [ ] Speaker and Moderator run the stream
- [ ] RCT submits recording to be uploaded to the Reactor YouTube and to be made available on LearnTV
- [ ] RCT moves issue to the __Stream Complete__ column

**Comment by mebaumb** [comment]
@KimberlyBolton1 - Hey! This event is ready for a Marketing Edit!

**Comment by KimberlyBolton1** [comment]
@GeekTrainer 
Edited abstract for your review:
Get Your Web Dev Needs Met with Azure Static Web Apps
Developers have needs: they want deployment to be seamless, server architecture to be invisible, and performance to be automatic. Enter Azure Static Web Apps. This (currently in preview) service enables you to write your client-side code using the framework you love, create back-end code using any language you prefer, and employ GitHub and Azure to take care of the rest! Join this session to see how you can use Azure Static Web Apps for easier dynamic web development.

**Comment by GeekTrainer** [comment]
I'm not a big fan of the "needs" approach here

**Comment by KimberlyBolton1** [comment]
@geektrainer
In both title and description? Would "demands" or "wants" work better for you?

**Comment by GeekTrainer** [comment]
I'm not sure. I can't put my finger on it, but it's just not clicking with me. Let me come back to this tomorrow and see if I can better formulate my thoughts.

**Comment by drguthals** [comment]
Only because I created this and am getting notifications in email....what about:
`How Azure Static Web Apps can help your dynamic web development`

Or something? (switching it around)

**Comment by KimberlyBolton1** [comment]
@sguthals
I can live with it. I talk with Christopher shortly and will finalize.

**Comment by KimberlyBolton1** [comment]
@mebaumb
email exchange with content owner to finalize abstract. Moved to Ready for Sharepoint.

**Comment by mebaumb** [comment]
Published in SharePoint (6/23)

**Comment by mebaumb** [comment]
This is on YouTube!
