### ISSUE TITLE
April 6 - Intro to Application Security

### ISSUE THREAD

**Issue by meaghanlewis** [microsoft/ReactorPlanning#257]
# Event Information
| Category | Details |
|-----------|---------|
| Stream Date | April 6| 
| Stream Time | 4pm PT | 
| Title | Intro to Application Security |
| Description | In the first stream of the series, Meaghan Lewis will explain what Application Security, or AppSec for short, is and how it fits into the cybersecurity realm. Understand the skills you need to get into AppSec, AppSec activities, and some common roles in this field. You’ll gain a better understanding of what Application Security entails and have a set of resources to go forth and build your knowledge. |
| Speaker |---------|
| SharePoint ID | 13206 |  
| SharePoint Status |---------| 

Additional Resources:  
<Additional resources that can be linked from social media for promotion or added to the description of VOD>

# Event Checklist

## 10 Weeks Prior
- [ ] Title & Description Finalized
- [ ] Tracking Links/Short links
- [ ] Published
- [ ] Calendar Invite

**Comment by mebaumb** [comment]
Hey @meaghanlewis - what do you think about this? 

Cybersecurity is the protection and security of computer systems, software, and networks from theft, intrusion, damage or misdirection. Cybersecurity is complex and full of many specialties. Join Meaghan Lewis, Senior Program Manager, in the first stream of the series, where she will explain what Application Security, or AppSec for short, is and how it fits into the cybersecurity realm. Understand the skills you need to get into AppSec, AppSec activities, and some common roles in this field. You’ll gain a better understanding of what Application Security entails and have a set of resources and tools to use going forward.

**Comment by meaghanlewis** [comment]
Thanks @mebaumb! I like your edits. Just updated the last sentence a bit.

**Comment by mebaumb** [comment]
Analytics data captured!
