### ISSUE TITLE
April 13 - Learn about security fundamentals

### ISSUE THREAD

**Issue by meaghanlewis** [microsoft/ReactorPlanning#258]
# Event Information
| Category | Details |
|-----------|---------|
| Stream Date | April 13 | 
| Stream Time | 4pm PT | 
| Title | Learn about security fundamentals |
| Description | Before you begin developing software, it's vitally important that you know how to keep your application secure. To do this, you'll need to understand and know how to implement security fundamentals. Learning these fundamentals will ensure you make secure project decisions throughout each stage of development. In this session, we’ll dive into how to protect the confidentiality, integrity, and availability of software applications. We’ll look at some common threats that applications encounter, and focus on key tips on how to reduce the chance of being vulnerable to these threats. |
| Speaker |---------|
| SharePoint ID | 13207 |  
| SharePoint Status |---------| 

Additional Resources:  
<Additional resources that can be linked from social media for promotion or added to the description of VOD>

# Event Checklist

## 10 Weeks Prior
- [ ] Title & Description Finalized
- [ ] Tracking Links/Short links
- [ ] Published
- [ ] Calendar Invite

**Comment by mebaumb** [comment]
@meaghanlewis - what do you think about this? 

Before you begin developing software, it's vitally important that you know how to keep your application secure. To do this, you'll need to understand and know how to implement security fundamentals. Learning these fundamentals will ensure you make secure project decisions throughout each stage of development. In this session, we’ll dive into how to protect the confidentiality, integrity, and availability of software applications. We’ll look at some common threats that applications encounter, and focus on key tips on how to reduce the chance of being vulnerable to these threats.

**Comment by meaghanlewis** [comment]
Thanks @mebaumb! Did a slight rewrite. If it looks good to you, please go ahead and update. 😄
