### ISSUE TITLE
April 20 - How to implement secure design

### ISSUE THREAD

**Issue by meaghanlewis** [microsoft/ReactorPlanning#259]
# Event Information
| Category | Details |
|-----------|---------|
| Stream Date | April 20 | 
| Stream Time | 4pm PT | 
| Title | How to implement secure design |
| Description | It’s crucial that security practices and activities are introduced early in the software development life cycle (SDLC). In this session, Meaghan Lewis, Senior Program Manager, will look at how to have an eye for security during the requirements setting and design decision phases. As you start to determine what the final product will be, you can begin to understand the level of security needed and implement them from day 1. You'll walk away from this session with an understanding of what security decisions can be made in the design phase to later benefit the development, testing, and release phases of the SDLC.|
| Speaker |---------|
| SharePoint ID | 13208 |  
| SharePoint Status |---------| 

Additional Resources:  
<Additional resources that can be linked from social media for promotion or added to the description of VOD>

# Event Checklist

## 10 Weeks Prior
- [ ] Title & Description Finalized
- [ ] Tracking Links/Short links
- [ ] Published
- [ ] Calendar Invite

**Comment by mebaumb** [comment]
@meaghanlewis - how about this? 

It’s crucial that security practices and activities are introduced early in the software development life cycle (SDLC). In this session, Meaghan Lewis, Senior Program Manager, will look at how to have an eye for security during the requirements setting and design decision phases. As you start to determine what the final product will be, you can begin to understand the level of security needed and implement them from day 1. You'll walk away from this session with an understanding of what security decisions can be made in the design phase to later benefit the development, testing, and release phases of the SDLC.

**Comment by meaghanlewis** [comment]
Thanks @mebaumb!  Same as before, I made a few edits. If this looks good to you, go ahead an update the description.
