### ISSUE TITLE
Aug 10 - 14: Intro to Python

### ISSUE THREAD

**Issue by meaghanlewis** [microsoft/ReactorPlanning#26]
# Event Information
| Category | Details |
|-----------|---------|
| Reactor Topic | Coding, Languages, and Frameworks |
| Monthly Topic (if applicable) | API |
| Weekly Topic (if applicable) |  |
| Stream Date | Aug 10 - 14, 2020 | 
| Stream Duration | 90 min | 
| Title | Intro to Python Programming |
| Description | Python is an interpreted, high-level, general-purpose programming language and one of the best for data science and machine learning. This workshop explores the basics of Python, such as arithmetic, numeric, and data types. By the end, you’ll gain the familiarity you need to start using it on your own. In this workshop, we will use Python examples within a Jupyter Notebook in VS Code.|
| Content | https://github.com/microsoft/Reactors/blob/main/Data_Science_1/Full_Day/1-Python.ipynb |

# Workshop details
| Date |  Local Start Time |  Location |  Speaker | SharePoint ID |
|----- |------------------|-----------|----------|--------------|
| Aug 10 |  4:00 PM GMT+4 | Abu Dhabi | Avinash Mishra | 7886 |
| Aug 10 |  6:00 PM  GMT+3 | Tel Aviv | Avinash Mishra | 7887 |
| Aug 11 |  8:00 PM  GMT+10| Sydney | Maddie Shang | 7888 |
| Aug 11 |  6:30 PM GMT+5:30| Bangalore | Avinash Mishra | 7889 |
| Aug 12 |  3:30 PM GMT-3| Sao Paulo | Flavio Figueiredo | 7756 |
| Aug 12 |  7:30 PM GMT+8 | Shanghai | Ryan Chung | 7891 |
| Aug 12 | 6:00 PM GMT+1  | London | Dave Wade-Stein | 7892 |
| Aug 12 | 4:00 PM PDT | US/Canada | Dave Wade-Stein | 7893 |

Additional Resources:  
<Additional resources that can be linked from social media for promotion or added to the description of VOD>

# Event Checklist

## 10 Weeks Prior
- [X] Reactor Content Team (RCT) opens a new issue for an upcoming local workshop filling in the Event Information and Workshop details tables. RCT member who owns content (content owner) this week will be the assignee.
- [X] RCT and content owner discuss details of the event in the comments of this issue. RCT adds a _confirmed-event_ label and _local-digital-event_ tag to the issue and adds event to the __Local Digital Events__ project. Issue will appear in the __Upcoming Streams__ column
- [X] RCT adds a _ready-for-marketing-edit_ label so the RCT can review title and description

## 8 Weeks Prior
- [X] RCT does a review of title and description and removes the _ready-for-marketing-edit_ label 
- [X] RCT moves the issue to the __Ready for SharePoint__ column
- [X] RCT informs the Reactor Marketing Team of the new event information
- [ ] RCT provides speaker with assets (e.g. slides, overlays) and the survey data for the event
- [X] RCT moves the issue to the __Content Preparation In Progress__ column
- [ ] RCT confirms the speaker

## 5 weeks Prior
- [ ] Content owner opens a PR with the new content for the workshop on the [customer-facing Reactor repository](https://github.com/microsoft/Reactors) and adds the _content-development_ and _local-digital-event_ tag to the PR. 
- [ ] Content owner adds to the same PR modification to the [Streaming README](https://github.com/microsoft/Reactors/tree/main/Online) 
- [ ] RCT reviews, approves, and merges the changes
- [ ] RCT shares content with the vendor/instructor
- [ ] RCT provides vendor/instructor with assets (e.g. slides, overlays) and the survey data for the event
- [ ] RCT ensures that instructors have received an invite to the workshops and that PM team works with instructors to get setup in the platform (e.g. Teams, Teams Live Event)

## 1 Week Prior
- [ ] Connect vendor/instructor with the PM(s) for the locations where this event has been marketed
- [ ] Check-in with vendor/instructor that they are prepared for the workshop
- [ ] RCT moves the issue to the __Ready to Stream__ column

## During and After Stream
- [ ] Instructor (and optional moderator) run the stream
- [ ] _(Optional)_RCT submits recording to be uploaded to the Reactor YouTube and to be made available on LearnTV
- [ ] RCT moves issue to the __Stream Complete__ column

**Comment by mebaumb** [comment]
Abu Dhabi. Tel Aviv, and Bangalore Published (6/25)

**Comment by mebaumb** [comment]
Sydney published without speaker details (7/6)

**Comment by mebaumb** [comment]
Sydney speaker updated!
