### ISSUE TITLE
April 27 - How to implement secure code

### ISSUE THREAD

**Issue by meaghanlewis** [microsoft/ReactorPlanning#260]
# Event Information
| Category | Details |
|-----------|---------|
| Stream Date | April 27 | 
| Stream Time | 4pm PT | 
| Title | How to implement secure code |
| Description | Now that you understand security fundamentals and you have gone through your design phase with security in mind, it's time to write the code and actually build the product. In this phase of development, there are lots of decisions to be made about the way the product is built. There are also important and necessary steps that need to be taken to ensure that the application works as expected in a secure way. This requires that developers are equipped with the knowledge they need to write secure code. In this episode, Meaghan Lewis, Senior Program Manager will walk through how to go about selecting secure frameworks and programming languages, how to work with trusted data and APIs, best practices for HTTP protocols, how to protect identity, and how to securely log errors and prevent any important information from leaking there.|
| Speaker |---------|
| SharePoint ID | 13209 |  
| SharePoint Status |---------| 

Additional Resources:  
<Additional resources that can be linked from social media for promotion or added to the description of VOD>

# Event Checklist

## 10 Weeks Prior
- [ ] Title & Description Finalized
- [ ] Tracking Links/Short links
- [ ] Published
- [ ] Calendar Invite

**Comment by mebaumb** [comment]
@meaghanlewis - What do you think about this? 

Now that you understand security fundamentals and you have gone through your design phase with security in mind, it's time to write the code and actually build the product. In this phase of development, there are lots of decisions to be made about the way the product is built. There are also important and necessary steps that need to be taken to ensure that the application works as expected in a secure way. This requires that developers are equipped with the knowledge they need to write secure code. In this episode, Meaghan Lewis, Senior Program Manager will walk through how to go about selecting secure frameworks and programming languages, how to work with trusted data and APIs, best practices for HTTP protocols, how to protect identity, and how to securely log errors and prevent any important information from leaking there.

**Comment by meaghanlewis** [comment]
@mebaumb your rewrite looks great! I think it's good to go.
