### ISSUE TITLE
May 4 - Securely testing and deploying your application

### ISSUE THREAD

**Issue by meaghanlewis** [microsoft/ReactorPlanning#261]
# Event Information
| Category | Details |
|-----------|---------|
| Stream Date | May 4 | 
| Stream Time | 4pm PT | 
| Title |  Securely testing and deploying your application |
| Description | Even after writing secure code, it is essential to have a process to thoroughly test your application. In this session with Meaghan Lewis, Senior Program Manager, we’ll cover the strategies to test your code, application, and any integrations with your application such as with databases and external services. Then, we’ll cover solutions to deploy your application safely. Having a sound testing and deployment strategy will give you the confidence that your application will hold up against threats once it’s out in the wild. This is another crucial part of the Application Security process to ensure your software will maintain confidentiality, integrity, and availability. |
| Speaker |---------|
| SharePoint ID | 13210 |  
| SharePoint Status |---------| 

Additional Resources:  
<Additional resources that can be linked from social media for promotion or added to the description of VOD>

# Event Checklist

## 10 Weeks Prior
- [ ] Title & Description Finalized
- [ ] Tracking Links/Short links
- [ ] Published
- [ ] Calendar Invite

**Comment by mebaumb** [comment]
@meaghanlewis - What do you think about this? 

Even after writing secure code, it is essential to have a process to thoroughly test your application. In this session with Meaghan Lewis, Senior Program Manager, we’ll cover the strategies to test your code, application, and any integrations with your application such as with databases and external services. Then, we’ll cover solutions to deploy your application safely. Having a sound testing and deployment strategy will give you the confidence that your application will hold up against threats once it’s out in the wild. This is another crucial part of the Application Security process to ensure your software will maintain confidentiality, integrity, and availability.

**Comment by meaghanlewis** [comment]
This looks good to go @mebaumb
