### ISSUE TITLE
May 11 - How to create an AppSec program

### ISSUE THREAD

**Issue by meaghanlewis** [microsoft/ReactorPlanning#262]
# Event Information
| Category | Details |
|-----------|---------|
| Stream Date | May 11 | 
| Stream Time | 4pm PT| 
| Title | How to Create an AppSec Program |
| Description | After having gained knowledge of how Application Security can be applied throughout the design, code, test, and deployment of a system, you should consider how to best create an AppSec program. This includes program goals, activities and tools to consider and a framework you can use for all applications that you create and maintain. Join Meaghan Lewis, Senior Program Manager, in the last stream of this series, to learn about how to create and implement a repeatable program that can be used to ensure the reliability and security of software applications. |
| Speaker |---------|
| SharePoint ID | 13211 |  
| SharePoint Status |---------| 

Additional Resources:  
<Additional resources that can be linked from social media for promotion or added to the description of VOD>

# Event Checklist

## 10 Weeks Prior
- [ ] Title & Description Finalized
- [ ] Tracking Links/Short links
- [ ] Published
- [ ] Calendar Invite

**Comment by mebaumb** [comment]
@meaghanlewis - this looks great! No updates, just added your title in the text to make it consistent! copied below just for verification :) 

After having gained knowledge of how Application Security can be applied throughout the design, code, test, and deployment of a system, you should consider how to best create an AppSec program. This includes program goals, activities and tools to consider and a framework you can use for all applications that you create and maintain. Join Meaghan Lewis, Senior Program Manager, in the last stream of this series, to learn about how to create and implement a repeatable program that can be used to ensure the reliability and security of software applications.

**Comment by meaghanlewis** [comment]
Thank you!
