### ISSUE TITLE
Aug 17 - Keep Your Eye on the Design: How Microsoft Creates APIs

### ISSUE THREAD

**Issue by drguthals** [microsoft/ReactorPlanning#27]
# Event Information
| Category | Details |
|-----------|---------|
| Reactor Topic | Coding, Languages, and Frameworks |
| Monthly Topic (if applicable) | Powerful APIs and Power Platform |
| Weekly Topic (if applicable) | <Topic decided by RCT if relevant> |
| Stream Topic | <2-5 words describing the topic> |
| Stream Date | August 17, 2020 | 
| Stream Time | 4pm PT | 
| Stream Duration | 60 minutes | 
| Title | Keep Your Eye on the Design: How Microsoft Creates APIs |
| Description | As developers, our reliance on APIs is critical to efficient development. Using company and product API guidelines, Microsoft provides a consistent approach that helps you learn a new API quickly. In this session, a Microsoft API expert who not only designs .NET APIs for Azure but is also on the company-wide design team will walk you through Microsoft’s API development process so that the next API you learn will be a breeze. |
| Speaker | Anne Loomis Thompson |
| Moderator | Sarah Guthals, PhD |
| SharePoint ID | 7853 |  

Additional Resources:  
<Additional resources that can be linked from social media for promotion or added to the description of VOD>

# Event Checklist

## 10 Weeks Prior
- [X] Reactor Content Team (RCT) or Speaker opens a new issue for an upcoming stream filling in the Event Information table. Both RCT and Speaker are marked as assignees.
- [x] RCT and Speaker discuss details of the event in the comments of this issue. RCT adds a _confirmed-event_ label and _global-twitch-event_ tag to the issue and adds event to the __Global Live Streams__ project. Issue will appear in the __Upcoming Streams__ column
- [X] Speaker adds a _ready-for-marketing-edit_ label so the RCT can review title and description

## 8 Weeks Prior
- [x] RCT does a review of title and description and removes the _ready-for-marketing-edit_ label 
- [x] RCT moves the issue to the __Ready for SharePoint__ column
- [x] RCT informs the Reactor Marketing Team of the new event information
- [ ] RCT provides speaker with assets (e.g. slides, overlays) and the survey data for the event
- [ ] RCT moves the issue to the __MONTH Streams Prep__ column (according to the month it will be streamed in)

## 2 Weeks Prior *(Done in /microsoft/Reactors)*
- [ ] Speaker opens a PR with the new content for the stream on the [customer-facing Reactor repository](https://github.com/microsoft/Reactors) and adds the _content-development_ and _global-twitch-event_ tag to the PR. 
- [ ] Speaker adds to the same PR a modification to the [Streaming README](https://github.com/microsoft/Reactors/tree/main/Online) to include their stream information.
- [ ] Speaker adds the RCT assigned to the issue as the reviewer when it is ready for review/merge
- [ ] RCT reviews, approves, and merges the changes

## 1 Week Prior
- [ ] Speaker and Moderator test setup for streaming (instructions coming soon)
- [ ] RCT checks in with the speaker and moves the issue to the __Ready to Stream__ column

## During and After Stream
- [ ] Speaker and Moderator run the stream
- [ ] RCT submits recording to be uploaded to the Reactor YouTube and to be made available on LearnTV
- [ ] RCT moves issue to the __Stream Complete__ column

**Comment by drguthals** [comment]
Getting confirmation from Anne on the date.

**Comment by drguthals** [comment]
👋 @KimberlyBolton1 Here is a new session that needs review

**Comment by KimberlyBolton1** [comment]
edited abstract and sent to content owner for review.

**Comment by drguthals** [comment]
@KimberlyBolton1 - is the edited abstract the one in the issue body above? Or did you send it to @annelo-msft ? I wrote it broad enough for her, but just checking to see if I can help get this into Sharepoint.

**Comment by KimberlyBolton1** [comment]
@sguthals 
the edited version is both in the body above and I emailed it to her for review (before we updated our process to do it all in GitHub). That was yesterday and have not heard back from her yet. since it's already to her in email, I was going to finish the loop as I started it. To summarize, going forward, I'm putting the edited version in the comments only, use GitHub to notify the content owner to review, then upon approval, I move the final version to the body.

**Comment by KimberlyBolton1** [comment]
@mebaumb 
Small tweak to description...final and moved to Ready for Sharepoint.

**Comment by mebaumb** [comment]
Published in SharePoint (6/23)

**Comment by KimberlyBolton1** [comment]
@mebaumb Session was recorded but there were technical issues with latency/audio so Sarah wants to eventually re-record. This was not uploaded to YouTube. Not sure where you want to place this in the publishing pipeline....

**Comment by mebaumb** [comment]
This is on YouTube!
