### ISSUE TITLE
August 9 - 14 - Working with data and properties in React components

### ISSUE THREAD

**Issue by mebaumb** [microsoft/ReactorPlanning#272]
# Event Information
| Category | Details |
|-----------|---------|
| Reactor Topic | Coding, Languages and Frameworks |
| Workshop Topic | Working with data and properties in React components |
| Workshop Duration | 60 mins | 
| Title | Working with data and properties in React components |
| Description | The goal of React components is to create reusable blocks of code and UI. To support reusability, you can pass data into components through the use of properties. We will see how to add properties to a component, and work with complex data types such as arrays. In this workshop, you'll learn how to work with properties in a component, add logic to a JSX file, and use a map to work with lists of items. To attend this workshop, it is recommended that you have knowledge of HTML, CSS, JavaScript, Git, npm, and some experience with React. |
| Level | Beginner | 
| Content Link | https://docs.microsoft.com/learn/modules/react-work-with-components-and-data |

# Workshop(s) details
| Date |  Local Start Time |  Location |  Speaker | SharePoint ID | Platform |
|------|-------------------|-----------|----------|---------------|----------|
| August 10, 2021 | 4:00 PM PST | US/CA/AU | TBD | 13538 |----------|
| August 10, 2021 | 8:00 PM | Bangalore | TBD | 13539 |----------|
| August 11, 2021 | 7:00 PM | Sao Paulo | TBD | 13541 |----------|
| August 11, 2021 | 7:30 PM | Shanghai | TBD | 13542 |----------|
| August 11, 2021 | 12:00 PM | EMEA | TBD | 13540 |----------|

**Comment by mebaumb** [comment]
@meaghanlewis - this one's also great. i would swap two sentences the "We'll see how to add properties..." and the "In this workshop...":

The goal of React components is to create reusable blocks of code and UI. To support reusability, you can pass data into components through the use of properties. In this workshop, you'll learn how to work with properties in a component, add logic to a JSX file, and use a map to work with lists of items. We will see how to add properties to a component, and work with complex data types such as arrays. To attend this workshop, it is recommended that you have knowledge of HTML, CSS, JavaScript, Git, npm, and some experience with React.

**Comment by meaghanlewis** [comment]
@mebaumb sounds good to me to swap those sentences!
