### ISSUE TITLE
September 20 - 24 - Get started with Power Automate 

### ISSUE THREAD

**Issue by mebaumb** [microsoft/ReactorPlanning#278]
# Event Information
| Category | Details |
|-----------|---------|
| Reactor Topic | Coding, Languages and Frameworks |
| Workshop Topic | Get started with Power Automate  |
| Workshop Duration | 60 mins | 
| Title | Get started with Power Automate |
| Description | Power Automate is an online workflow service that automates actions across the most common apps and services. You can use Power Automate to automate workflows between your favorite applications and services, sync files, get notifications, collect data, and much more. In this workshop, you will: learn what Power Automate is and how it can be used, learn how to create a button flow to send yourself a reminder, and create flows to post tweets , send notifications, copies files, and more. It will open up your eyes to all the possibilities Power Automate can save you time in your day-to-day work. To attend this workshop, you should have a Microsoft account. |
| Level | Beginner |
| Content Link | https://docs.microsoft.com/learn/modules/get-started-flows |

# Workshop(s) details
| Date |  Local Start Time |  Location |  Speaker | SharePoint ID | Platform |
|------|-------------------|-----------|----------|---------------|----------|
| September 21, 2021 | 4:00 PM PST | US/CA/AU | TBD | 13568 |----------|
| September 21, 2021 | 8:00 PM | Bangaluru | TBD | 13569 |----------|
| September 22, 2021 | 7:00 PM | Sao Paulo | TBD | 13571 |----------|
| September 22, 2021 | 7:30 PM | Shanghai | TBD | 13572 |----------|
| September 22, 2021 | 12:00 PM | EMEA | TBD | 13570 |----------|

**Comment by mebaumb** [comment]
@meaghanlewis - Looks good to me! Does a OneDrive for business account cost money? Or is it free?

**Comment by meaghanlewis** [comment]
@mebaumb great question! I totally should've checked before because it looks like it costs money. 😓 
Let me see if the free option can be used instead.

**Comment by meaghanlewis** [comment]
It looks like there's a free alternative to use an Outlook account with the regular OneDrive.
