### ISSUE TITLE
Aug 19 - “Go” Further with the Go Programming Language

### ISSUE THREAD

**Issue by drguthals** [microsoft/ReactorPlanning#29]
# Event Information
| Category | Details |
|-----------|---------|
| Reactor Topic | Coding Languages and Frameworks |
| Monthly Topic (if applicable) | Powerful APIs and Power Platform |
| Weekly Topic (if applicable) | <Topic decided by RCT if relevant> |
| Stream Topic | <2-5 words describing the topic> |
| Stream Date | Aug 19, 2020 | 
| Stream Time | 9am PT | 
| Stream Duration | 60 min | 
| Title | “Go” Further with the Go Programming Language |
| Description | Go quickly became a hot language for low-level systems development, databases, and distributed systems, but the language has expanded well beyond systems development. Have you heard of Docker, Kubernetes, and CockroachDB? They’re all written in Go. You can even build full web apps with Go. In this session, we’ll briefly learn the history of Go and then dive into the language and its libraries for writing web services. Finally, we’ll build a REST API using Go, deploy it to the web, and test it.
We recommend you have a basic understanding of HTTP/REST and some experience programming in C, C++, Java, C#, or other C-like languages. If you plan to follow along, you’ll need an editor (such as VS Code) and Go installed on your machine (https://golang.org/dl).  |
| Speaker | Aaron Schlesinger |
| Moderator | TBD |
| Internal Event ID | 7851 |

Additional Resources:  
<Additional resources that can be linked from social media for promotion or added to the description of VOD>

# Event Checklist

## 10 Weeks Prior
- [X] Reactor Content Team (RCT) or Speaker opens a new issue for an upcoming stream filling in the Event Information table. Both RCT and Speaker are marked as assignees.
- [X] RCT and Speaker discuss details of the event in the comments of this issue. RCT adds a _confirmed-event_ label and _global-twitch-event_ tag to the issue and adds event to the __Global Live Streams__ project. Issue will appear in the __Upcoming Streams__ column
- [X] Speaker adds a _ready-for-marketing-edit_ label so the RCT can review title and description

## 8 Weeks Prior
- [X] RCT does a review of title and description and removes the _ready-for-marketing-edit_ label 
- [X] RCT moves the issue to the __Ready for SharePoint__ column
- [X] RCT informs the Reactor Marketing Team of the new event information
- [ ] RCT provides speaker with assets (e.g. slides, overlays) and the survey data for the event
- [X] RCT moves the issue to the __MONTH Streams Prep__ column (according to the month it will be streamed in)

## 2 Weeks Prior *(Done in /microsoft/Reactors)*
- [ ] Speaker opens a PR with the new content for the stream on the [customer-facing Reactor repository](https://github.com/microsoft/Reactors) and adds the _content-development_ and _global-twitch-event_ tag to the PR. 
- [ ] Speaker adds to the same PR a modification to the [Streaming README](https://github.com/microsoft/Reactors/tree/main/Online) to include their stream information.
- [ ] Speaker adds the RCT assigned to the issue as the reviewer when it is ready for review/merge
- [ ] RCT reviews, approves, and merges the changes

## 1 Week Prior
- [ ] Speaker and Moderator test setup for streaming (instructions coming soon)
- [ ] RCT checks in with the speaker and moves the issue to the __Ready to Stream__ column

## During and After Stream
- [ ] Speaker and Moderator run the stream
- [x] RCT submits recording to be uploaded to the Reactor YouTube and to be made available on LearnTV
- [x] RCT moves issue to the __Stream Complete__ column

**Comment by KimberlyBolton1** [comment]
Session recorded and uploaded to YouTube: https://youtu.be/jTs1kgxRMDs. Issue closed.
