### ISSUE TITLE
Aug 20 - Azure API Exploration

### ISSUE THREAD

**Issue by drguthals** [microsoft/ReactorPlanning#30]
# Event Information
| Category | Details |
|-----------|---------|
| Reactor Topic | Cloud Development |
| Monthly Topic (if applicable) | Powerful APIs and Power Platform |
| Weekly Topic (if applicable) | Azure APIs |
| Stream Topic | Sarah's going to explore various Azure APIs |
| Stream Date | Aug 20, 2020 | 
| Stream Time | 9am PT | 
| Stream Duration | 110 min | 
| Title | Azure API Exploration |
| Description | The world of Azure is vast, and the ways in which developers can integrate services and tools are even greater. That said, Azure APIs can help you create continuous integration, simplify authentication, and provide on-premises connectivity. In this session, we’ll explore various options as Sarah Guthals discovers, creates—and likely fails at—Azure APIs. |
| Speaker | Sarah Guthals, PhD and/or TBD |
| Moderator | <Name or GitHub alias> |
| Event ID | 7850 |

Additional Resources:  
<Additional resources that can be linked from social media for promotion or added to the description of VOD>

# Event Checklist

## 10 Weeks Prior
- [X] Reactor Content Team (RCT) or Speaker opens a new issue for an upcoming stream filling in the Event Information table. Both RCT and Speaker are marked as assignees.
- [X] RCT and Speaker discuss details of the event in the comments of this issue. RCT adds a _confirmed-event_ label and _global-twitch-event_ tag to the issue and adds event to the __Global Live Streams__ project. Issue will appear in the __Upcoming Streams__ column
- [X] Speaker adds a _ready-for-marketing-edit_ label so the RCT can review title and description

## 8 Weeks Prior
- [x] RCT does a review of title and description and removes the _ready-for-marketing-edit_ label 
- [x] RCT moves the issue to the __Ready for SharePoint__ column
- [x] RCT informs the Reactor Marketing Team of the new event information
- [ ] RCT provides speaker with assets (e.g. slides, overlays) and the survey data for the event
- [ ] RCT moves the issue to the __MONTH Streams Prep__ column (according to the month it will be streamed in)

## 2 Weeks Prior *(Done in /microsoft/Reactors)*
- [ ] Speaker opens a PR with the new content for the stream on the [customer-facing Reactor repository](https://github.com/microsoft/Reactors) and adds the _content-development_ and _global-twitch-event_ tag to the PR. 
- [ ] Speaker adds to the same PR a modification to the [Streaming README](https://github.com/microsoft/Reactors/tree/main/Online) to include their stream information.
- [ ] Speaker adds the RCT assigned to the issue as the reviewer when it is ready for review/merge
- [ ] RCT reviews, approves, and merges the changes

## 1 Week Prior
- [ ] Speaker and Moderator test setup for streaming (instructions coming soon)
- [ ] RCT checks in with the speaker and moves the issue to the __Ready to Stream__ column

## During and After Stream
- [ ] Speaker and Moderator run the stream
- [x] RCT submits recording to be uploaded to the Reactor YouTube and to be made available on LearnTV
- [x] RCT moves issue to the __Stream Complete__ column

**Comment by drguthals** [comment]
For reference: https://docs.microsoft.com/en-us/rest/api/azure/

**Comment by KimberlyBolton1** [comment]
Edited abstract and sent to content owner for review.

**Comment by KimberlyBolton1** [comment]
@sguthals
Would you take a look at the edit to this abstract? I added some content around customer value but don’t want to deviate from the focus of your talk—so please let me know if I’ve done that and help clarify what might work better. Thanks!

Azure API Exploration
The world of Azure is vast, and the ways in which developers can integrate services and tools are even greater. That said, Azure APIs can help you create continuous integration, simplify authentication, and provide on-premises connectivity. In this session, we’ll explore various options as Sarah Guthals discovers, creates—and likely fails at—Azure APIs.

**Comment by drguthals** [comment]
@KimberlyBolton1 This sounds good! Thank you!

**Comment by KimberlyBolton1** [comment]
@mbaumb
Abstract final and moved to Ready for Sharepoint

**Comment by mebaumb** [comment]
Uploaded into SharePoint (6/22)

**Comment by KimberlyBolton1** [comment]
Session recorded and uploaded to YouTube: https://youtu.be/AUhRYjUH2O0. Issue closed.
