### ISSUE TITLE
Aug 24 - Azure and Power BI: A Partnership Made in (Data Visualization) Heaven

### ISSUE THREAD

**Issue by drguthals** [microsoft/ReactorPlanning#32]
# Event Information
| Category | Details |
|-----------|---------|
| Reactor Topic | Data Science and Machine Learning  |
| Monthly Topic (if applicable) | Powerful APIs and Power Platform |
| Weekly Topic (if applicable) | Power Platform |
| Stream Topic | Sarah is going to connect up one of her Azure machine learning things to PowerBI |
| Stream Date | August 24, 2020 | 
| Stream Time | 4pm PT | 
| Stream Duration | 60 Min | 
| Title | Azure and Power BI: A Partnership Made in (Data Visualization) Heaven |
| Description | Data science discoveries, projects, and solutions are only as successful as the experts and instruments involved. Microsoft has a variety of tools and services to support each step along the way. In this stream, learn how Power BI and Azure can work together to help you solve data science issues and visualize potential solutions. |
| Speaker | Sarah Guthals, PhD and/or TBD |
| Moderator | <Name or GitHub alias> |
| Event ID | 7849 |

Additional Resources:  
<Additional resources that can be linked from social media for promotion or added to the description of VOD>

# Event Checklist

## 10 Weeks Prior
- [X] Reactor Content Team (RCT) or Speaker opens a new issue for an upcoming stream filling in the Event Information table. Both RCT and Speaker are marked as assignees.
- [X] RCT and Speaker discuss details of the event in the comments of this issue. RCT adds a _confirmed-event_ label and _global-twitch-event_ tag to the issue and adds event to the __Global Live Streams__ project. Issue will appear in the __Upcoming Streams__ column
- [X] Speaker adds a _ready-for-marketing-edit_ label so the RCT can review title and description

## 8 Weeks Prior
- [x] RCT does a review of title and description and removes the _ready-for-marketing-edit_ label 
- [x] RCT moves the issue to the __Ready for SharePoint__ column
- [x] RCT informs the Reactor Marketing Team of the new event information
- [ ] RCT provides speaker with assets (e.g. slides, overlays) and the survey data for the event
- [x] RCT moves the issue to the __MONTH Streams Prep__ column (according to the month it will be streamed in)

## 2 Weeks Prior *(Done in /microsoft/Reactors)*
- [ ] Speaker opens a PR with the new content for the stream on the [customer-facing Reactor repository](https://github.com/microsoft/Reactors) and adds the _content-development_ and _global-twitch-event_ tag to the PR. 
- [ ] Speaker adds to the same PR a modification to the [Streaming README](https://github.com/microsoft/Reactors/tree/main/Online) to include their stream information.
- [ ] Speaker adds the RCT assigned to the issue as the reviewer when it is ready for review/merge
- [ ] RCT reviews, approves, and merges the changes

## 1 Week Prior
- [ ] Speaker and Moderator test setup for streaming (instructions coming soon)
- [ ] RCT checks in with the speaker and moves the issue to the __Ready to Stream__ column

## During and After Stream
- [ ] Speaker and Moderator run the stream
- [x] RCT submits recording to be uploaded to the Reactor YouTube and to be made available on LearnTV
- [x] RCT moves issue to the __Stream Complete__ column

**Comment by drguthals** [comment]
For reference: https://docs.microsoft.com/en-us/power-bi/connect-data/service-azure-and-power-bi

**Comment by KimberlyBolton1** [comment]
@sguthals
Edited abstract for your review:
Azure and Power BI: A Partnership Made in (Data Visualization) Heaven
Data science discoveries, projects, and solutions are only as successful as the experts and instruments involved. Microsoft has a variety of tools and services to support each step along the way. In this stream, learn how Power BI and Azure can work together to help you solve data science issues and visualize potential solutions.

**Comment by drguthals** [comment]
@KimberlyBolton1 - Looks great! Thanks!

**Comment by KimberlyBolton1** [comment]
Abstract final and moved to Ready for SharePoint

**Comment by KimberlyBolton1** [comment]
@mebaumb ready for Sharepoint

**Comment by mebaumb** [comment]
Uploaded to SharePoint (6/22)

**Comment by drguthals** [comment]
## Power-BI Embedded (in the cloud so you dont have to buy it)
https://docs.microsoft.com/en-us/power-bi/developer/embedded/azure-pbie-what-is-power-bi-embedded

## Azure Functions
Azure Functions to read data and update analytics

## Azure SQL Warehouse
https://azure.microsoft.com/en-us/resources/videos/introduction-to-azure-sql-data-warehouse/#:~:text=Azure%20SQL%20Data%20Warehouse%20is,%2Das%2Dyou%20go%20environment.

https://azure.microsoft.com/en-us/services/synapse-analytics/

**Comment by drguthals** [comment]
https://docs.microsoft.com/en-us/power-bi/transform-model/service-machine-learning-integration

https://docs.microsoft.com/en-us/learn/paths/prepare-data-power-bi/

https://docs.microsoft.com/en-us/learn/modules/get-started-with-power-bi/

https://docs.microsoft.com/en-us/learn/modules/introduction-power-bi/

**Comment by KimberlyBolton1** [comment]
Session recorded and uploaded to YouTube: https://youtu.be/4-cJjPDYGeA. Issue closed.
