### ISSUE TITLE
Aug 25 - Azure Analytics Options

### ISSUE THREAD

**Issue by drguthals** [microsoft/ReactorPlanning#33]
# Event Information
| Category | Details |
|-----------|---------|
| Reactor Topic | Cloud Development |
| Monthly Topic (if applicable) | Powerful APIs and Power Platform |
| Weekly Topic (if applicable) | Power Platform |
| Stream Topic | Sarah is going to explore Azure Analytics |
| Stream Date | August 25, 2020 | 
| Stream Time | 4pm | 
| Stream Duration | 60 minutes | 
| Title | Azure Analytics Options |
| Description | From big data to millions of tiny IoT devices, data is useless if you cannot analyze it. Azure Analytics offers a wide array of tools that can operate many times faster than—and cost a fraction of—other cloud offerings. In this stream, we’ll introduce the analytic services available on Azure. |
| Speaker | Sarah Guthals, PhD and/or TBD |
| Moderator | <Name or GitHub alias> |
| SharePoint ID | 7854  |  

Additional Resources:  
<Additional resources that can be linked from social media for promotion or added to the description of VOD>

# Event Checklist

## 10 Weeks Prior
- [X] Reactor Content Team (RCT) or Speaker opens a new issue for an upcoming stream filling in the Event Information table. Both RCT and Speaker are marked as assignees.
- [X] RCT and Speaker discuss details of the event in the comments of this issue. RCT adds a _confirmed-event_ label and _global-twitch-event_ tag to the issue and adds event to the __Global Live Streams__ project. Issue will appear in the __Upcoming Streams__ column
- [X] Speaker adds a _ready-for-marketing-edit_ label so the RCT can review title and description

## 8 Weeks Prior
- [x] RCT does a review of title and description and removes the _ready-for-marketing-edit_ label 
- [x] RCT moves the issue to the __Ready for SharePoint__ column
- [x] RCT informs the Reactor Marketing Team of the new event information
- [x] RCT provides speaker with assets (e.g. slides, overlays) and the survey data for the event
- [x] RCT moves the issue to the __MONTH Streams Prep__ column (according to the month it will be streamed in)

## 2 Weeks Prior *(Done in /microsoft/Reactors)*
- [x] Speaker opens a PR with the new content for the stream on the [customer-facing Reactor repository](https://github.com/microsoft/Reactors) and adds the _content-development_ and _global-twitch-event_ tag to the PR. 
- [x] Speaker adds to the same PR a modification to the [Streaming README](https://github.com/microsoft/Reactors/tree/main/Online) to include their stream information.
- [x] Speaker adds the RCT assigned to the issue as the reviewer when it is ready for review/merge
- [x] RCT reviews, approves, and merges the changes

## 1 Week Prior
- [x] Speaker and Moderator test setup for streaming (instructions coming soon)
- [x] RCT checks in with the speaker and moves the issue to the __Ready to Stream__ column

## During and After Stream
- [ ] Speaker and Moderator run the stream
- [x] RCT submits recording to be uploaded to the Reactor YouTube and to be made available on LearnTV
- [x] RCT moves issue to the __Stream Complete__ column

**Comment by drguthals** [comment]
https://docs.microsoft.com/en-us/azure/?product=analytics

**Comment by drguthals** [comment]
@KimberlyBolton1 - just making sure you saw this one 😄

**Comment by KimberlyBolton1** [comment]
@sguthals 
Edited abstract for review:
Azure Analytics Options
From big data to millions of tiny IoT devices, data is useless if you cannot analyze it. Azure Analytics offers a wide array of tools that can operate many times faster than—and cost a fraction of—other cloud offerings. In this stream, we’ll introduce the analytic services available on Azure.

**Comment by drguthals** [comment]
## Power-BI Embedded (in the cloud so you dont have to buy it)
https://docs.microsoft.com/en-us/power-bi/developer/embedded/azure-pbie-what-is-power-bi-embedded

## Azure Functions
Azure Functions to read data and update analytics

## Azure SQL Warehouse
https://azure.microsoft.com/en-us/resources/videos/introduction-to-azure-sql-data-warehouse/#:~:text=Azure%20SQL%20Data%20Warehouse%20is,%2Das%2Dyou%20go%20environment.

https://azure.microsoft.com/en-us/services/synapse-analytics/

**Comment by drguthals** [comment]
@KimberlyBolton1 - 🚢 👍

**Comment by KimberlyBolton1** [comment]
@mebaumb
Abstract final and moved to Ready for Sharepoint

**Comment by mebaumb** [comment]
Uploaded to SharePoint (6/23)

**Comment by drguthals** [comment]
Stream Analytics:
https://docs.microsoft.com/en-us/learn/paths/implement-data-streaming-with-asa/

**Comment by KimberlyBolton1** [comment]
Session recorded and uploaded to YouTube: https://youtu.be/DrhlSqLWjaA. Issue closed.
