### ISSUE TITLE
Aug 27 - Code and Coffee: Azure and Power Platform

### ISSUE THREAD

**Issue by drguthals** [microsoft/ReactorPlanning#35]
# Event Information
| Category | Details |
|-----------|---------|
| Reactor Topic |  Cloud Development  |
| Monthly Topic (if applicable) | Powerful APIs and Power Platform |
| Weekly Topic (if applicable) | Power Platform |
| Stream Topic | Sarah is going to build a project with Azure and Power Platforms |
| Stream Date | August 27, 2020 | 
| Stream Time | 9am PT | 
| Stream Duration | 110 minutes | 
| Title | Code and Coffee: Azure and Power Platform |
| Description | Throughout this week, Sarah has been introducing various Azure and Power Platform (Power BI, PowerApps, and Power Automate) services. Join this longer stream to put your introductory knowledge to practice as we create an end-to-end project that utilizes both Azure and Power Platform. |
| Speaker | Sarah Guthals, PhD and/or TBD |
| Moderator | <Name or GitHub alias> |
| SharePoint ID | 7856 |  

Additional Resources:  
<Additional resources that can be linked from social media for promotion or added to the description of VOD>

# Event Checklist

## 10 Weeks Prior
- [X] Reactor Content Team (RCT) or Speaker opens a new issue for an upcoming stream filling in the Event Information table. Both RCT and Speaker are marked as assignees.
- [X] RCT and Speaker discuss details of the event in the comments of this issue. RCT adds a _confirmed-event_ label and _global-twitch-event_ tag to the issue and adds event to the __Global Live Streams__ project. Issue will appear in the __Upcoming Streams__ column
- [X] Speaker adds a _ready-for-marketing-edit_ label so the RCT can review title and description

## 8 Weeks Prior
- [x] RCT does a review of title and description and removes the _ready-for-marketing-edit_ label 
- [x] RCT moves the issue to the __Ready for SharePoint__ column
- [x] RCT informs the Reactor Marketing Team of the new event information
- [ ] RCT provides speaker with assets (e.g. slides, overlays) and the survey data for the event
- [ ] RCT moves the issue to the __MONTH Streams Prep__ column (according to the month it will be streamed in)

## 2 Weeks Prior *(Done in /microsoft/Reactors)*
- [ ] Speaker opens a PR with the new content for the stream on the [customer-facing Reactor repository](https://github.com/microsoft/Reactors) and adds the _content-development_ and _global-twitch-event_ tag to the PR. 
- [ ] Speaker adds to the same PR a modification to the [Streaming README](https://github.com/microsoft/Reactors/tree/main/Online) to include their stream information.
- [ ] Speaker adds the RCT assigned to the issue as the reviewer when it is ready for review/merge
- [ ] RCT reviews, approves, and merges the changes

## 1 Week Prior
- [ ] Speaker and Moderator test setup for streaming (instructions coming soon)
- [ ] RCT checks in with the speaker and moves the issue to the __Ready to Stream__ column

## During and After Stream
- [ ] Speaker and Moderator run the stream
- [ ] RCT submits recording to be uploaded to the Reactor YouTube and to be made available on LearnTV
- [ ] RCT moves issue to the __Stream Complete__ column

**Comment by drguthals** [comment]
https://docs.microsoft.com/en-us/power-platform/
https://docs.microsoft.com/en-us/samples/browse/?products=power-platform

**Comment by drguthals** [comment]
@KimberlyBolton1 - just making sure oy saw this one 😄

**Comment by KimberlyBolton1** [comment]
@sguthals
Edited abstract below. We've been using the term "code and coffee" sporadically for the Thursday sessions. I like the idea of creating a mini "brand" for this day, as it can help with user expectations and provide some predictability. Let me know if you disagree. :)
Code and Coffee: Azure and Power Platform 
Throughout this week, Sarah has been introducing various Azure and Power Platform (Power BI, PowerApps, and Power Automate) services. Join this longer stream to put your introductory knowledge to practice as we create an end-to-end project that utilizes both Azure and Power Platform.

**Comment by drguthals** [comment]
@KimberlyBolton1 👍 🚢

**Comment by KimberlyBolton1** [comment]
Abstract final and moved to Ready for Sharepoint.

**Comment by KimberlyBolton1** [comment]
@mebaumb

**Comment by mebaumb** [comment]
Cancelling this one per Sarah's message today (8/25) cancelled on Dynamics, Meetup and on the calendars.
