### ISSUE TITLE
Aug 24 - 28: Getting started with JavaScript

### ISSUE THREAD

**Issue by meaghanlewis** [microsoft/ReactorPlanning#36]
# Event Information
| Category | Details |
|-----------|---------|
| Reactor Topic | Coding, Languages, and Frameworks |
| Monthly Topic (if applicable) | API |
| Weekly Topic (if applicable) |  |
| Stream Date | Aug 24 - 28, 2020 | 
| Stream Duration | 90 min | 
| Title | Getting started with JavaScript |
| Description | If you want to start programming for the web, one language you’ll need to have in your toolbelt is JavaScript. JavaScript is the lingua franca of the web. With the use of JavaScript you can make your pages dynamic and interactive. In this 2 hour workshop you’ll see how to get started with JavaScript, walk through the core syntax and functionality. You’ll also gain experience with libraries and frameworks which can help make your life as a developer easier. |
| Content | https://github.com/microsoft/Reactors/tree/main/Web_Fundamentals_2/3_Javascript |

# Workshop details
| Date |  Local Start Time |  Location |  Speaker | SharePoint ID |
|----- |------------------|-----------|----------|--------------|
| Aug 24 |  4:00 PM GMT+4 | Abu Dhabi | Kyle Gabhart  | 7902 |
| Aug 24 |  6:00 PM  GMT+3 | Tel Aviv | Kyle Gabhart | 7903 |
| Aug 25 |  8:00 PM  GMT+10| Sydney | Maddie Shang | 7904 |
| Aug 25 |  6:30 PM GMT+5:30| Bangalore | Kyle Gabhart  | 7905 |
| Aug 26 |  3:30 PM GMT-3| Sao Paulo | Helder de Rocha | 7758 |
| Aug 26 |  7:30 PM GMT+8 | Shanghai | Ryan Chung | 7907 |
| Aug 26 | 6:00 PM GMT+1  | London | Kyle Gabhart  | 7908 |
| Aug 26 | 4:00 PM PDT | US/Canada | Kyle Gabhart  | 7909 |

# Event Checklist

## 10 Weeks Prior
- [X] Reactor Content Team (RCT) opens a new issue for an upcoming local workshop filling in the Event Information and Workshop details tables. RCT member who owns content (content owner) this week will be the assignee.
- [X] RCT and content owner discuss details of the event in the comments of this issue. RCT adds a _confirmed-event_ label and _local-digital-event_ tag to the issue and adds event to the __Local Digital Events__ project. Issue will appear in the __Upcoming Streams__ column
- [X] RCT adds a _ready-for-marketing-edit_ label so the RCT can review title and description

## 8 Weeks Prior
- [x] RCT does a review of title and description and removes the _ready-for-marketing-edit_ label 
- [x] RCT moves the issue to the __Ready for SharePoint__ column
- [x] RCT informs the Reactor Marketing Team of the new event information
- [x] RCT confirms the speaker
- [x] RCT provides speaker with assets (e.g. slides, overlays) and the survey data for the event
- [ ] RCT moves the issue to the __Content Preparation In Progress__ column

## 5 weeks Prior
- [ ] Content owner opens a PR with the new content for the workshop on the [customer-facing Reactor repository](https://github.com/microsoft/Reactors) and adds the _content-development_ and _local-digital-event_ tag to the PR. 
- [ ] Content owner adds to the same PR modification to the [Streaming README](https://github.com/microsoft/Reactors/tree/main/Online) 
- [ ] RCT reviews, approves, and merges the changes
- [ ] RCT shares content with the vendor/instructor
- [ ] RCT provides vendor/instructor with assets (e.g. slides, overlays) and the survey data for the event
- [ ] RCT ensures that instructors have received an invite to the workshops and that PM team works with instructors to get setup in the platform (e.g. Teams, Teams Live Event)

## 1 Week Prior
- [ ] Connect vendor/instructor with the PM(s) for the locations where this event has been marketed
- [ ] Check-in with vendor/instructor that they are prepared for the workshop
- [ ] RCT moves the issue to the __Ready to Stream__ column

## During and After Stream
- [ ] Instructor (and optional moderator) run the stream
- [ ] _(Optional)_RCT submits recording to be uploaded to the Reactor YouTube and to be made available on LearnTV
- [ ] RCT moves issue to the __Stream Complete__ column

**Comment by mebaumb** [comment]
Abu Dhabi, Tel Aviv, & Bangalore published (6/25)

**Comment by mebaumb** [comment]
Sydney, London/Stockholm, & US/Canada all published without speaker details

**Comment by mebaumb** [comment]
Sydney and US/Canada have speaker details added

**Comment by mebaumb** [comment]
Workshops have been run! Closing this issue!
