### ISSUE TITLE
Aug 31 - Exploring TypeScript

### ISSUE THREAD

**Issue by drguthals** [microsoft/ReactorPlanning#37]
# Event Information
| Category | Details |
|-----------|---------|
| Reactor Topic | Coding, Languages, and Frameworks |
| Monthly Topic (if applicable) | Skill-Up September |
| Weekly Topic (if applicable) | TypeScript |
| Stream Topic | Interview with someone from the TypeScript team |
| Stream Date | August 31, 2020 | 
| Stream Time | 4pm PT | 
| Stream Duration | 60 minutes | 
| Title | Let's Talk about TypeScript |
| Description | If you are an experienced JavaScript developer, you likely have a system setup which works for you. You've invested time into preparing your tooling, linting files, and workflows. Perhaps you are also becoming interested in TypeScript to better manage your growing codebase but have questions about where to start, what changes you'd need to make to your development cycle, and, frankly, whether the benefits outweigh the effort. Join this session as we ask a TypeScript program manager these very questions and more! We'll chat about the rationale behind TypeScript, the problems it looks to solve, and how it can make you a more efficient developer. We'll also discuss how to migrate a JavaScript project without throwing out your entire codebase and starting over. This session recommends an intermediate knowledge of JavaScript and 1-2 years of coding experience. No previous experience with TypeScript is required. |
| Speaker | Daniel Rosenwasser & Christopher Harrison |
| Moderator | <Name or GitHub alias> |
| SharePoint ID | 7955 |  

Additional Resources:  
<Additional resources that can be linked from social media for promotion or added to the description of VOD>

# Event Checklist

## 10 Weeks Prior
- [x] Reactor Content Team (RCT) or Speaker opens a new issue for an upcoming stream filling in the Event Information table. Both RCT and Speaker are marked as assignees.
- [x] RCT and Speaker discuss details of the event in the comments of this issue. RCT adds a _confirmed-event_ label and _global-twitch-event_ tag to the issue and adds event to the __Global Live Streams__ project. Issue will appear in the __Upcoming Streams__ column
- [x] Speaker adds a _ready-for-marketing-edit_ label so the RCT can review title and description

## 8 Weeks Prior
- [x] RCT does a review of title and description
- [x] RCT moves the issue to the __Ready for SharePoint__ column
- [x] RCT informs the Reactor Marketing Team of the new event information
- [ ] RCT provides speaker with assets (e.g. slides, overlays) and the survey data for the event
- [ ] RCT moves the issue to the __Stream Preparation In Progress__ column

## 2 Weeks Prior
- [ ] Speaker opens a PR with the new content for the stream, adds it to the same project chosen above, and adds the _content-development_ and _global-twitch-event_ tag to the PR. PR will appear in the __Stream Preparation In Progress__ column. 
- [ ] Speaker adds to the same PR a modification to the [Streaming README](https://github.com/microsoft/Reactors/tree/main/Online) 
- [ ] Speaker adds the RCT assigned to the issue as the reviewer when it is ready for review/merge
- [ ] RCT reviews, approves, and merges the changes and the PR moves to the __Stream Complete__ column

## 1 Week Prior
- [ ] Speaker and Moderator test setup for streaming (instructions coming soon)
- [ ] RCT checks in with the speaker and moves the issue to the __Ready to Stream__ column

## During and After Stream
- [ ] Speaker and Moderator run the stream
- [ ] RCT submits recording to be uploaded to the Reactor YouTube and to be made available on LearnTV
- [ ] RCT moves issue to the __Stream Complete__ column

**Comment by mebaumb** [comment]
Hey @KimberlyBolton1, this is ready for editing!

**Comment by KimberlyBolton1** [comment]
@geektrainer @DanielRosenwasser 
Edited abstract below. Please take a close look at the prerequisite recommendations at the bottom that I added to ensure accuracy.
Using TypeScript for Next-Level Web Dev
If you are an experienced JavaScript developer, you likely have a system setup which works for you. You've invested time into preparing your tooling, linting files, and workflows. Perhaps you are also becoming interested in TypeScript to better manage your growing codebase but have questions about where to start, what changes you'd need to make to your development cycle, and, frankly, whether the benefits outweigh the effort. Join this session as we ask a TypeScript PM these very questions and more! We'll chat about the rationale behind TypeScript, the problems it looks to solve, and how it can make you a more efficient developer. We'll also discuss how to migrate a JavaScript project without throwing out your entire codebase and starting over.
This session recommends an intermediate knowledge of JavaScript and 1-2 years of coding experience. No previous experience with TypeScript is required.

**Comment by KimberlyBolton1** [comment]
@geektrainer 
Title alternative:
Let's Talk about TypeScript

Would that work?

**Comment by GeekTrainer** [comment]
Sub program manager for PM (just to define our TLAs) and I think we're good

**Comment by KimberlyBolton1** [comment]
@mebaumb
Abstract final and moved to Ready for Sharepoint.

**Comment by mebaumb** [comment]
published in Sharepoint on 7/13

**Comment by mebaumb** [comment]
This is on Youtube!
