### ISSUE TITLE
Sep 1 - 	TypeScript in Action

### ISSUE THREAD

**Issue by drguthals** [microsoft/ReactorPlanning#38]
# Event Information
| Category | Details |
|-----------|---------|
| Reactor Topic | Coding, Languages, and Frameworks |
| Monthly Topic (if applicable) | Skill-Up September |
| Weekly Topic (if applicable) | TypeScript |
| Stream Topic | Gabby delivers a "conference" style session |
| Stream Date | September 1, 2020 | 
| Stream Time | 4pm PT | 
| Stream Duration | 60 minutes | 
| Title | TypeScript in Action |
| Description | <p>TypeScript can ease many JavaScript development woes. It can catch common mistakes before they become runtime errors, enable the IDE to provide better code completion and navigation, and allow you to focus on writing code without worrying about JavaScript's quirks. Join this session to watch TypeScript Program Manager Gabrielle Crevecoeur initiate a project, highlight TypeScript's syntax and functionality, and ultimately help you upskill from JavaScript into TypeScript.</p><p>This session recommends an intermediate knowledge of JavaScript and 1-2 years’ coding experience. No previous experience with TypeScript is needed.</p>|
| Speaker | Gabrielle Crevecoeur |
| Moderator | <Name or GitHub alias> |
| SharePoint ID | 7956 |  

Additional Resources:  
<Additional resources that can be linked from social media for promotion or added to the description of VOD>

# Event Checklist

## 10 Weeks Prior
- [x] Reactor Content Team (RCT) or Speaker opens a new issue for an upcoming stream filling in the Event Information table. Both RCT and Speaker are marked as assignees.
- [x] RCT and Speaker discuss details of the event in the comments of this issue. RCT adds a _confirmed-event_ label and _global-twitch-event_ tag to the issue and adds event to the __Global Live Streams__ project. Issue will appear in the __Upcoming Streams__ column
- [x] Speaker adds a _ready-for-marketing-edit_ label so the RCT can review title and description

## 8 Weeks Prior
- [x] RCT does a review of title and description
- [x] RCT moves the issue to the __Ready for SharePoint__ column
- [x] RCT informs the Reactor Marketing Team of the new event information
- [ ] RCT provides speaker with assets (e.g. slides, overlays) and the survey data for the event
- [ ] RCT moves the issue to the __Stream Preparation In Progress__ column

## 2 Weeks Prior
- [ ] Speaker opens a PR with the new content for the stream, adds it to the same project chosen above, and adds the _content-development_ and _global-twitch-event_ tag to the PR. PR will appear in the __Stream Preparation In Progress__ column. 
- [ ] Speaker adds to the same PR a modification to the [Streaming README](https://github.com/microsoft/Reactors/tree/main/Online) 
- [ ] Speaker adds the RCT assigned to the issue as the reviewer when it is ready for review/merge
- [ ] RCT reviews, approves, and merges the changes and the PR moves to the __Stream Complete__ column

## 1 Week Prior
- [ ] Speaker and Moderator test setup for streaming (instructions coming soon)
- [ ] RCT checks in with the speaker and moves the issue to the __Ready to Stream__ column

## During and After Stream
- [ ] Speaker and Moderator run the stream
- [ ] RCT submits recording to be uploaded to the Reactor YouTube and to be made available on LearnTV
- [ ] RCT moves issue to the __Stream Complete__ column

**Comment by mebaumb** [comment]
@KimberlyBolton1, Hey! This event is ready to be edited!

**Comment by KimberlyBolton1** [comment]
@gcrev93 
Edited abstract is below. Please take a close look at the recommendations at the end to ensure they are accurate. Let me know when approved:
TypeScript in Action
TypeScript can ease many JavaScript development woes. It can catch common mistakes before they become runtime errors, enable the IDE to provide better code completion and navigation, and allow you to focus on writing code without worrying about JavaScript's quirks. Join this session to watch a PM on the TypeScript team initiate a project, highlight TypeScript's syntax and functionality, and ultimately help you upskill from JavaScript into TypeScript.
This session recommends an intermediate knowledge of JavaScript and 1-2 years’ coding experience. No previous experience with TypeScript is needed.

**Comment by GeekTrainer** [comment]
Let's just update PM > program manager (my mistake) and we're good. Also, it's worth calling out Gabby because she's awesome!!!

**Comment by KimberlyBolton1** [comment]
@mebaumb
Finalized abstract and moved to Ready for Sharepoint.

**Comment by mebaumb** [comment]
Published in Sharepoint on 7/13
