### ISSUE TITLE
Sep 2 - Linux on Windows: The Best of Both Worlds for C++ Development

### ISSUE THREAD

**Issue by drguthals** [microsoft/ReactorPlanning#39]
# Event Information
| Category | Details |
|-----------|---------|
| Reactor Topic | Coding, languages, and frameworks |
| Monthly Topic (if applicable) | Skill Up September |
| Weekly Topic (if applicable) | TypeScript |
| Stream Topic | C/C++ on Windows |
| Stream Date | September 2, 2020 | 
| Stream Time | 9am PT | 
| Stream Duration | 60 minutes | 
| Title | Linux on Windows: The Best of Both Worlds for C++ Development  |
| Description | <p>Despite the popularity of high-level languages like Python, JavaScript, and C#, learning languages like C and C++ can be incredibly valuable for understanding how computers work! C/C++ are also popular in application, web, gaming, and operating system development. While it's common to develop with C/C++ on Linux, these days it's just as easy to get started writing C/C++ on your Windows machine.</p><p>In this session, you will understand the benefits of learning C/C++, why you might choose to develop on Linux vs. Windows, and how to write C/C++ in Windows using Windows Subsystem for Linux (WSL).</p><p>This session recommends a basic understanding of a programming language other than C/C++, familiarity with the Linux OS, and access to a Windows PC to install software.</p> |
| Speaker | Shana Matthews |
| Moderator | <Name or GitHub alias> |
| SharePoint ID | 7957 |  

Additional Resources:  
<Additional resources that can be linked from social media for promotion or added to the description of VOD>

# Event Checklist

## 10 Weeks Prior
- [x] Reactor Content Team (RCT) or Speaker opens a new issue for an upcoming stream filling in the Event Information table. Both RCT and Speaker are marked as assignees.
- [x] RCT and Speaker discuss details of the event in the comments of this issue. RCT adds a _confirmed-event_ label and _global-twitch-event_ tag to the issue and adds event to the __Global Live Streams__ project. Issue will appear in the __Upcoming Streams__ column
- [x] Speaker adds a _ready-for-marketing-edit_ label so the RCT can review title and description

## 8 Weeks Prior
- [x] RCT does a review of title and description
- [x] RCT moves the issue to the __Ready for SharePoint__ column
- [ ] RCT informs the Reactor Marketing Team of the new event information
- [ ] RCT provides speaker with assets (e.g. slides, overlays) and the survey data for the event
- [ ] RCT moves the issue to the __Stream Preparation In Progress__ column

## 2 Weeks Prior
- [ ] Speaker opens a PR with the new content for the stream, adds it to the same project chosen above, and adds the _content-development_ and _global-twitch-event_ tag to the PR. PR will appear in the __Stream Preparation In Progress__ column. 
- [ ] Speaker adds to the same PR a modification to the [Streaming README](https://github.com/microsoft/Reactors/tree/main/Online) 
- [ ] Speaker adds the RCT assigned to the issue as the reviewer when it is ready for review/merge
- [ ] RCT reviews, approves, and merges the changes and the PR moves to the __Stream Complete__ column

## 1 Week Prior
- [ ] Speaker and Moderator test setup for streaming (instructions coming soon)
- [ ] RCT checks in with the speaker and moves the issue to the __Ready to Stream__ column

## During and After Stream
- [ ] Speaker and Moderator run the stream
- [ ] RCT submits recording to be uploaded to the Reactor YouTube and to be made available on LearnTV
- [ ] RCT moves issue to the __Stream Complete__ column

**Comment by KimberlyBolton1** [comment]
Added my edited title/abstract to the issue (Shana sent me draft notes in email). 
@shanamatthews please review the abstract and let me know if approved. A few notes: I try to make the titles attention-grabbing while informative. For the abstract, I added some content based on research I did. If it somehow changes the focus of what you’re planning to present, do let me know so we can adjust and make it right. Thx!

**Comment by shanamatthews** [comment]
Thanks @KimberlyBolton1 ! Thanks for putting it together! I made a couple of edits to the abstract. 

I also wanted to ask about the "Stream Topic". Should we update that too?

Otherwise, this looks good to me!

**Comment by KimberlyBolton1** [comment]
@mebaumb Ok, abstract now final and moved to Ready for Sharepoint.

**Comment by mebaumb** [comment]
This has been published into Sharepoint (not dynamics 8/18)

**Comment by drguthals** [comment]
@shanamatthews  
http://aka.ms/Reactor/Survey - Code: 7957

Slide deck I use: 
https://microsoft-my.sharepoint.com/:p:/p/sguthals/EXUv677Xx9dFm8nSbFgLPsUBsIjj6AnsDUTbrCqLLGYUuQ?e=LjEfDD

Short link to your content: 
https://aka.ms/WSL-8

Twitch overlays:
https://microsoft-my.sharepoint.com/:f:/p/sguthals/EmJ1m61qx4RMsDwmkGSeRoABR8s3C1mp-oa2-xTtTFGjAA?e=Y2IPMz

OBS Scene:
https://microsoft-my.sharepoint.com/:u:/p/sguthals/ERtvzUZH9TxCmRtA4L36dn8B676HmxshzrMTZTZuxL-Baw?e=zKcGUx

**Comment by shanamatthews** [comment]
- [x] set resolution
- [x] set stream key (in email)
- [x] adjust camera/monitor to set up background
- [x] open starting soon scene
- [x] visit chat: https://www.twitch.tv/popout/microsoftdeveloper/chat?popout=

**Comment by mebaumb** [comment]
This is on Youtube! :)
