### ISSUE TITLE
Sep 3 - Code and Coffee: Build a Project with TypeScript

### ISSUE THREAD

**Issue by drguthals** [microsoft/ReactorPlanning#40]
# Event Information
| Category | Details |
|-----------|---------|
| Reactor Topic | AI Services - Coding, Languages, and Frameworks |
| Monthly Topic (if applicable) | Skill Up September |
| Weekly Topic (if applicable) | TypeScript |
| Stream Topic | Creating a React project in TypeScript |
| Stream Date | September 3, 2020 | 
| Stream Time | 9am PT | 
| Stream Duration | 110 minutes | 
| Title | Code and Coffee: Build a Project with TypeScript |
| Description | Are you a JavaScript developer interested in TypeScript but unsure how to start a project? Curious about the syntax and benefits TypeScript offers? Having trouble building an Express framework with a Mongoose library using TypeScript? Join Christopher Harrison as he takes you from start to finish, first setting up a TypeScript project, then creating the model and web application, and ultimately deploying it online. You’re sure to learn some tricks along the way during this project-based presentation. Some JavaScript experience is assumed, but experience with Express or Mongoose is not necessary. |
| Speaker | Christopher |
| Moderator | <Name or GitHub alias> |
| SharePoint ID | 7958 |  

Additional Resources:  
<Additional resources that can be linked from social media for promotion or added to the description of VOD>

# Event Checklist

## 10 Weeks Prior
- [x] Reactor Content Team (RCT) or Speaker opens a new issue for an upcoming stream filling in the Event Information table. Both RCT and Speaker are marked as assignees.
- [x] RCT and Speaker discuss details of the event in the comments of this issue. RCT adds a _confirmed-event_ label and _global-twitch-event_ tag to the issue and adds event to the __Global Live Streams__ project. Issue will appear in the __Upcoming Streams__ column
- [x] Speaker adds a _ready-for-marketing-edit_ label so the RCT can review title and description

## 8 Weeks Prior
- [x] RCT does a review of title and description and removes the _ready-for-marketing-edit_ label 
- [x] RCT moves the issue to the __Ready for SharePoint__ column
- [x] RCT informs the Reactor Marketing Team of the new event information
- [ ] RCT provides speaker with assets (e.g. slides, overlays) and the survey data for the event
- [x] RCT moves the issue to the __MONTH Streams Prep__ column (according to the month it will be streamed in)

## 2 Weeks Prior *(Done in /microsoft/Reactors)*
- [ ] Speaker opens a PR with the new content for the stream on the [customer-facing Reactor repository](https://github.com/microsoft/Reactors) and adds the _content-development_ and _global-twitch-event_ tag to the PR. 
- [ ] Speaker adds to the same PR a modification to the [Streaming README](https://github.com/microsoft/Reactors/tree/main/Online) to include their stream information.
- [ ] Speaker adds the RCT assigned to the issue as the reviewer when it is ready for review/merge
- [ ] RCT reviews, approves, and merges the changes

## 1 Week Prior
- [ ] Speaker and Moderator test setup for streaming (instructions coming soon)
- [ ] RCT checks in with the speaker and moves the issue to the __Ready to Stream__ column

## During and After Stream
- [ ] Speaker and Moderator run the stream
- [ ] RCT submits recording to be uploaded to the Reactor YouTube and to be made available on LearnTV
- [ ] RCT moves issue to the __Stream Complete__ column

**Comment by mebaumb** [comment]
@KimberlyBolton1 Hey there! This is also ready for review! :)

**Comment by KimberlyBolton1** [comment]
@geektrainer
  Hi Christopher, would you review this abstract for accuracy? I made a couple tweaks to the descriptions of the tools used based on my online research so do let me know if anything is amiss.
   Also, I like using the "Code and Coffee" theme for the Thursday sessions. I think it might create familiarity and (hopefully) a bigger draw. Open to your thoughts on that.

Code and Coffee: Build a Project with TypeScript
Are you a JavaScript developer interested in TypeScript but unsure how to start a project? Curious about the syntax and benefits TypeScript offers? Having trouble building an Express framework with a Mongoose library using TypeScript? Join Christopher Harrison as he takes you from start to finish, first setting up a TypeScript project, then creating the model and web application, and ultimately deploying it online. You’re sure to learn some tricks along the way during this project-based presentation.
Some JavaScript experience is assumed, but experience with Express or Mongoose is not necessary.

**Comment by GeekTrainer** [comment]
I'm a huge fan of the Code & Coffee theme :-)

And that's perfect!! 🚢

**Comment by KimberlyBolton1** [comment]
@mebaumb
Abstract final and moved to Ready for Sharepoint.

**Comment by mebaumb** [comment]
Event published 7/13

**Comment by mebaumb** [comment]
Event Cancelled 8/10
