### ISSUE TITLE
Aug 31 - Sep 4: TypeScript Fundamentals for Web Development

### ISSUE THREAD

**Issue by meaghanlewis** [microsoft/ReactorPlanning#41]
# Event Information
| Category | Details |
|-----------|---------|
| Reactor Topic | Coding, Languages, Frameworks |
| Monthly Topic (if applicable) | Skill Up September |
| Weekly Topic (if applicable) | TypeScript |
| Stream Date | Aug 31 - Sep 4, 2020 | 
| Stream Duration | 90 min | 
| Title | TypeScript Fundamentals for Web Development |
| Description | TypeScript is an open-source, object-oriented language that has become a versatile cross-platform tool for developing modern web applications.  Because TypeScript is a superset of JavaScript, it can be a natural transition for existing JavaScript developers. Come learn the ABCs of TypeScript and see how it can help overcome common issues in JavaScript development. This workshop recommends you have a basic knowledge of JavaScript. |
| Content | https://github.com/microsoft/Reactors/tree/main/Online/typescript101 |

# Workshop details
| Date |  Local Start Time |  Location |  Speaker | SharePoint ID |
|----- |------------------|-----------|----------|--------------|
| Aug 31 |  4:00 PM GMT+4 | Abu Dhabi | Devendra Rawat | 7910 |
| Aug 31 |  6:00 PM  GMT+3 | Tel Aviv | Devendra Rawat | 7911 |
| Sep 1 |  8:00 PM  GMT+10| Sydney | Maddie Shang | 7912 |
| Sep 1 |  6:30 PM GMT+5:30| Bangalore | Devendra Rawat | 7913 |
| Sep 2 |  3:30 PM GMT-3| Sao Paulo | Flavio Figueiredo | 7759 |
| Sep 2 |  7:30 PM GMT+8 | Shanghai | Ryan Chung | 7914 |
| Sep 2 | 6:00 PM GMT+1  | London | Brian Sletten | 7915 |
| Sep 2 | 4:00 PM PDT | US/Canada | Maddie Shang | 7916 |

# Event Checklist

## 10 Weeks Prior
- [X] Reactor Content Team (RCT) opens a new issue for an upcoming local workshop filling in the Event Information and Workshop details tables. RCT member who owns content (content owner) this week will be the assignee.
- [X] RCT and content owner discuss details of the event in the comments of this issue. RCT adds a _confirmed-event_ label and _local-digital-event_ tag to the issue and adds event to the __Local Digital Events__ project. Issue will appear in the __Upcoming Streams__ column
- [X] RCT adds a _ready-for-marketing-edit_ label so the RCT can review title and description

## 8 Weeks Prior
- [X] RCT does a review of title and description and removes the _ready-for-marketing-edit_ label 
- [X] RCT moves the issue to the __Ready for SharePoint__ column
- [X] RCT informs the Reactor Marketing Team of the new event information
- [ ] RCT confirms the speaker
- [ ] RCT provides speaker with assets (e.g. slides, overlays) and the survey data for the event
- [ ] RCT moves the issue to the __Content Preparation In Progress__ column

## 5 weeks Prior
- [ ] Content owner opens a PR with the new content for the workshop on the [customer-facing Reactor repository](https://github.com/microsoft/Reactors) and adds the _content-development_ and _local-digital-event_ tag to the PR. 
- [ ] Content owner adds to the same PR modification to the [Streaming README](https://github.com/microsoft/Reactors/tree/main/Online) 
- [ ] RCT reviews, approves, and merges the changes
- [ ] RCT shares content with the vendor/instructor
- [ ] RCT provides vendor/instructor with assets (e.g. slides, overlays) and the survey data for the event
- [ ] RCT ensures that instructors have received an invite to the workshops and that PM team works with instructors to get setup in the platform (e.g. Teams, Teams Live Event)

## 1 Week Prior
- [ ] Connect vendor/instructor with the PM(s) for the locations where this event has been marketed
- [ ] Check-in with vendor/instructor that they are prepared for the workshop
- [ ] RCT moves the issue to the __Ready to Stream__ column

## During and After Stream
- [ ] Instructor (and optional moderator) run the stream
- [ ] _(Optional)_RCT submits recording to be uploaded to the Reactor YouTube and to be made available on LearnTV
- [ ] RCT moves issue to the __Stream Complete__ column

**Comment by mebaumb** [comment]
Bangalore, Abu Dhabi and Tel Aviv Published (6/25)

**Comment by mebaumb** [comment]
US/Canada and Sydney are both published!

**Comment by mebaumb** [comment]
All events are published for this week.
