### ISSUE TITLE
Sep 7 - Interview with a Rust Dev

### ISSUE THREAD

**Issue by meaghanlewis** [microsoft/ReactorPlanning#42]
# Event Information
| Category | Details |
|-----------|---------|
| Reactor Topic | Coding, Languages, Frameworks |
| Monthly Topic (if applicable) | Skill Up September |
| Weekly Topic (if applicable) | Rust |
| Stream Topic |  |
| Stream Date | Sep 7, 2020 | 
| Stream Time | 4PM PT | 
| Stream Duration | 60 minutes | 
| Title | Interview with a Rust Developer |
| Description |  If you have been curious about the Rust programming language, or if you are simply looking for a memory-safe, fast, general-purpose way to program your next project, Rust may be a great option for you. In this session, Meaghan Lewis chats with a Rust developer to discuss the benefits of using Rust and how it is being used at Microsoft today. Bring your questions, comments, and get ready to learn from the Rust pros. |
| Speaker | @meaghanlewis + Arlie Davis |
| Moderator | TBD |
| SharePoint ID | 7959 |  

Additional Resources:  
<Additional resources that can be linked from social media for promotion or added to the description of VOD>

# Event Checklist

## 10 Weeks Prior
- [X] Reactor Content Team (RCT) or Speaker opens a new issue for an upcoming stream filling in the Event Information table. Both RCT and Speaker are marked as assignees.
- [X] RCT and Speaker discuss details of the event in the comments of this issue. RCT adds a _confirmed-event_ label and _global-twitch-event_ tag to the issue and adds event to the __Global Live Streams__ project. Issue will appear in the __Upcoming Streams__ column
- [X] Speaker adds a _ready-for-marketing-edit_ label so the RCT can review title and description

## 8 Weeks Prior
- [x] RCT does a review of title and description and removes the _ready-for-marketing-edit_ label 
- [x] RCT moves the issue to the __Ready for SharePoint__ column
- [x] RCT informs the Reactor Marketing Team of the new event information
- [ ] RCT provides speaker with assets (e.g. slides, overlays) and the survey data for the event
- [ ] RCT moves the issue to the __MONTH Streams Prep__ column (according to the month it will be streamed in)

## 2 Weeks Prior *(Done in /microsoft/Reactors)*
- [ ] Speaker opens a PR with the new content for the stream on the [customer-facing Reactor repository](https://github.com/microsoft/Reactors) and adds the _content-development_ and _global-twitch-event_ tag to the PR. 
- [ ] Speaker adds to the same PR a modification to the [Streaming README](https://github.com/microsoft/Reactors/tree/main/Online) to include their stream information.
- [ ] Speaker adds the RCT assigned to the issue as the reviewer when it is ready for review/merge
- [ ] RCT reviews, approves, and merges the changes

## 1 Week Prior
- [ ] Speaker and Moderator test setup for streaming (instructions coming soon)
- [ ] RCT checks in with the speaker and moves the issue to the __Ready to Stream__ column

## During and After Stream
- [ ] Speaker and Moderator run the stream
- [ ] RCT submits recording to be uploaded to the Reactor YouTube and to be made available on LearnTV
- [ ] RCT moves issue to the __Stream Complete__ column

**Comment by KimberlyBolton1** [comment]
@meaghanlewis 
Edited abstract below. I couldn't find Arlie in GitHub so feel free to share with him as you review.
Interview with a Rust Developer
If you have been curious about the Rust programming language, or if you are simply looking for a memory-safe, fast, general-purpose way to program your next project, Rust may be a great option for you. In this session, Meaghan Lewis chats with a Rust developer to discuss the benefits of using Rust and how it is being used at Microsoft today. Bring your questions, comments, and get ready to learn from the Rust pros.

**Comment by meaghanlewis** [comment]
Thank you!

**Comment by KimberlyBolton1** [comment]
@meaghanlewis 
Approved then? :)

**Comment by meaghanlewis** [comment]
Approved ✅

**Comment by KimberlyBolton1** [comment]
@mabaumb
Abstract final and moved to Ready for Sharepoint.

**Comment by mebaumb** [comment]
Uploaded into SharePoint (6/23)

**Comment by meaghanlewis** [comment]
@mebaumb this stream will be cancelled since Monday, Sep 7th is Labor Day in the US. I'll go ahead and update the status of this issue. Could you please confirm the cancellation internally with the team?

**Comment by mebaumb** [comment]
this has been cancelled with the PM team!
