### ISSUE TITLE
Sep 8 - Get to Know Rust: Fun, Fast, and Efficient Programming

### ISSUE THREAD

**Issue by meaghanlewis** [microsoft/ReactorPlanning#43]
# Event Information
| Category | Details |
|-----------|---------|
| Reactor Topic | Coding, Languages, Frameworks |
| Monthly Topic (if applicable) | Skill Up September |
| Weekly Topic (if applicable) | Rust |
| Stream Topic |  |
| Stream Date | Sep 8, 2020 | 
| Stream Time | 4PM PT | 
| Stream Duration | 60 minutes | 
| Title | Get to Know Rust: Fun, Fast, Efficient Programming |
| Description |Rust is a programming language that empowers developers to build reliable and efficient software. It is fun to write, easy to read, and high performing. If you have been curious about the Rust programming language, or if you are simply looking for a memory-safe, fast, general-purpose way to program your next project, Rust may be a great option for you. Join Program Manager Meaghan Lewis and Software Engineer Arlie Davis to discuss the benefits of Rust and how it is being used at Microsoft today. |
| Speaker | @meaghanlewis & Arlie |
| Moderator | <Name or GitHub alias> |
| SharePoint ID | 7960 |  

Additional Resources:  
<Additional resources that can be linked from social media for promotion or added to the description of VOD>

# Event Checklist

## 10 Weeks Prior
- [X] Reactor Content Team (RCT) or Speaker opens a new issue for an upcoming stream filling in the Event Information table. Both RCT and Speaker are marked as assignees.
- [X] RCT and Speaker discuss details of the event in the comments of this issue. RCT adds a _confirmed-event_ label and _global-twitch-event_ tag to the issue and adds event to the __Global Live Streams__ project. Issue will appear in the __Upcoming Streams__ column
- [X] Speaker adds a _ready-for-marketing-edit_ label so the RCT can review title and description

## 8 Weeks Prior
- [x] RCT does a review of title and description and removes the _ready-for-marketing-edit_ label 
- [x] RCT moves the issue to the __Ready for SharePoint__ column
- [x] RCT informs the Reactor Marketing Team of the new event information
- [ ] RCT provides speaker with assets (e.g. slides, overlays) and the survey data for the event
- [ ] RCT moves the issue to the __MONTH Streams Prep__ column (according to the month it will be streamed in)

## 2 Weeks Prior *(Done in /microsoft/Reactors)*
- [ ] Speaker opens a PR with the new content for the stream on the [customer-facing Reactor repository](https://github.com/microsoft/Reactors) and adds the _content-development_ and _global-twitch-event_ tag to the PR. 
- [ ] Speaker adds to the same PR a modification to the [Streaming README](https://github.com/microsoft/Reactors/tree/main/Online) to include their stream information.
- [ ] Speaker adds the RCT assigned to the issue as the reviewer when it is ready for review/merge
- [ ] RCT reviews, approves, and merges the changes

## 1 Week Prior
- [ ] Speaker and Moderator test setup for streaming (instructions coming soon)
- [ ] RCT checks in with the speaker and moves the issue to the __Ready to Stream__ column

## During and After Stream
- [ ] Speaker and Moderator run the stream
- [ ] RCT submits recording to be uploaded to the Reactor YouTube and to be made available on LearnTV
- [ ] RCT moves issue to the __Stream Complete__ column

**Comment by KimberlyBolton1** [comment]
@meaghanlewis 
Please review the slightly edited abstract below:

Get to Know Rust: Fun, Fast, Efficient Programming
Rust is a programming language that empowers developers to build reliable and efficient software. It is fun to write, easy to read, and high performing. In this session, we’ll explore Rust programming language fundamentals and uncover common programming concepts and syntax. We will then put Rust into action as we build a simple command-line program.

**Comment by meaghanlewis** [comment]
Thank you!

**Comment by KimberlyBolton1** [comment]
@meaghanlewis 
Approved then? :)

**Comment by meaghanlewis** [comment]
Yep.

**Comment by KimberlyBolton1** [comment]
@mabaumb
Abstract final and move to Ready for Sharepoint.

**Comment by mebaumb** [comment]
Uploaded into SharePoint (6/23)

**Comment by meaghanlewis** [comment]
@KimberlyBolton1 here is the revised abstract for this stream:

Rust is a programming language that empowers developers to build reliable and efficient software. It is fun to write, easy to read, and high performing. If you have been curious about the Rust programming language, or if you are simply looking for a memory-safe, fast, general-purpose way to program your next project, Rust may be a great option for you. 

Join Program Manager, Meaghan Lewis, and Software Engineer, Arlie Davis, to discuss the benefits of using Rust and how it is being used at Microsoft today. We’ll then explore some fundamentals of Rust concepts and syntax through a simple command-line application.

Please feel free to edit and update the description up top. 😄

**Comment by KimberlyBolton1** [comment]
@meaghanlewis @mebaumb 
Looks good. Just did some minor grammatical edits. Moved to Ready for Sharepoint.

**Comment by KimberlyBolton1** [comment]
quick fix to paragraph issue in description.

**Comment by mebaumb** [comment]
This change has been communicated to the team.

**Comment by mebaumb** [comment]
Event has been published on youtube! Closing Issue!
