### ISSUE TITLE
Sep 9 - Fear Not the Big Bad Borrow Checker

### ISSUE THREAD

**Issue by meaghanlewis** [microsoft/ReactorPlanning#44]
# Event Information
| Category | Details |
|-----------|---------|
| Reactor Topic | Coding, Languages, Frameworks |
| Monthly Topic (if applicable) | Skill up |
| Weekly Topic (if applicable) | Rust |
| Stream Topic | <2-5 words describing the topic> |
| Stream Date | Sep 9, 2020 | 
| Stream Time | 9AM PT | 
| Stream Duration | 60 min | 
| Title | Fear Not the Big Bad Borrow Checker |
| Description | Rust developers often have a love/hate relationship with the borrow checker feature. While it is often described as Rust’s “secret sauce”, it can also be a challenging feature to understand and master. In this stream, we'll turn the borrow checker from foe to friend by diving deep into how it works and how you can more easily work with it.
This session recommends a basic understanding of and experience with the Rust programming language. |
| Speaker | @rylev  |
| Moderator | @meaghanlewis |
| SharePoint ID | 7961 |  

Additional Resources:  
<Additional resources that can be linked from social media for promotion or added to the description of VOD>

# Event Checklist

## 10 Weeks Prior
- [x] Reactor Content Team (RCT) or Speaker opens a new issue for an upcoming stream filling in the Event Information table. Both RCT and Speaker are marked as assignees.
- [x] RCT and Speaker discuss details of the event in the comments of this issue. RCT adds a _confirmed-event_ label and either _global-twitch-event_ or _local-teams-event_ tag to the issue and adds event to the __Global Live Streams__ project or the __Local Live Streams__ project. Issue will appear in the __Upcoming Streams__ column

## 8 Weeks Prior
- [x] RCT does a review of title and description
- [x] RCT moves the issue to the __Ready for SharePoint__ column
- [x] RCT informs the Reactor Marketing Team of the new event information
- [ ] RCT provides speaker with assets (e.g. slides, overlays) and the survey data for the event
- [x] RCT moves the issue to the __Stream Preparation In Progress__ column

## 2 Weeks Prior
- [ ] Speaker opens a PR with the new content for the stream, adds it to the same project chosen above, and adds the _content-development_ and either _global-twitch-event_ or _local-teams-event_ tag to the PR. PR will appear in the __Stream Preparation In Progress__ column. 
- [ ] Speaker adds to the same PR a modification to the [Streaming README](https://github.com/microsoft/Reactors/tree/master/Online) 
- [ ] Speaker adds the RCT assigned to the issue as the reviewer when it is ready for review/merge
- [ ] RCT reviews, approves, and merges the changes and the PR moves to the __Stream Complete__ column

## 1 Week Prior
- [ ] Speaker and Moderator test setup for streaming (instructions coming soon)
- [ ] RCT checks in with the speaker and moves the issue to the __Ready to Stream__ column

## During and After Stream
- [ ] Speaker and Moderator run the stream
- [ ] RCT submits recording to be uploaded to the Reactor YouTube and to be made available on LearnTV
- [ ] RCT moves issue to the __Stream Complete__ column

**Comment by drguthals** [comment]
@Meaghanlewis - I noticed that someone has signed up for this day in the spreadsheet: 

`9-Sep | 9-10am | Re-Designing APIs with Empathy | Learning from design schools from Japan to Europe, I will explain how to write APIs that have empathy at its core, putting the user first when it comes to designing them. | Alvaro Videla`

**Comment by meaghanlewis** [comment]
Thanks for the heads up @sguthals. I'll reach out to Alvaro and ask them to reschedule their session for another day.

**Comment by mebaumb** [comment]
Hey @meaghanlewis, I wanted to send a friendly reminder about this stream! Is it ready to have Kimberly review?

**Comment by meaghanlewis** [comment]
Hey @mebaumb yes this is ready for a review from @KimberlyBolton1.

@rylev heads up that I just added your handle in here as the speaker and so that you have visibility into this stream's details too.

**Comment by KimberlyBolton1** [comment]
@rylev 
Please review and approve the abstract edit:
Rust Tips & Tricks
Do your Rust programming skills need some shining up? Attend this stream to learn the insider hacks that will make developing with Rust more efficient and fun.

**Comment by KimberlyBolton1** [comment]
No response from content owner. Pinged @rylev in email.

**Comment by rylev** [comment]
@KimberlyBolton1 - sorry for the delay! Maybe we make this specifically about Rust's borrow checker since that is the thing that trips up beginners the most. So how about the following
> Learning Rust but still not fully sure how to overcome the borrow checker? In this stream, we'll turn the borrow checker from enemy to friend as we dive deep into Rust's most challenging feature. 

I'd expect people coming to the stream to have played with Rust before and probably written a few basic programs in it, but they're still struggling to overcome the initial learning curve.

**Comment by KimberlyBolton1** [comment]
@rylev
How's this edit then:

Fear Not the Big Bad Borrow Checker
Rust developers often have a love/hate relationship with the borrow checker feature. While it is often described as Rust’s “secret sauce”, it can also be a challenging feature to understand and master. In this stream, we'll turn the borrow checker from foe to friend by diving deep into how it works and how you can more easily work with it.
This session recommends a basic understanding of and experience with the Rust programming language.

**Comment by rylev** [comment]
Looks great!! ❤️❤️🎉🎉

**Comment by KimberlyBolton1** [comment]
@mebaumb
Abstract final and moved to Ready for Sharepoint.

**Comment by mebaumb** [comment]
Event was published on Sharepoint! (7/13)

**Comment by mebaumb** [comment]
Video has been published on youtube. Closing issue!
