### ISSUE TITLE
Sep 10 - Even more Rust

### ISSUE THREAD

**Issue by meaghanlewis** [microsoft/ReactorPlanning#45]
# Event Information
| Category | Details |
|-----------|---------|
| Reactor Topic | Coding, Languages, Frameworks |
| Monthly Topic (if applicable) | Skill Up September |
| Weekly Topic (if applicable) | Rust |
| Stream Topic |  |
| Stream Date | Sep 10, 2020 | 
| Stream Time | 9AM PT | 
| Stream Duration | 110 minutes | 
| Title | Code and Coffee: Build a Rust App |
| Description | You may know the basics of Rust: that it is a memory-safe, fast, general-purpose programming language. In this session, we will dust off our programming skills and take a deeper dive into coding with Rust as we build and test a Rust app using VS Code. If you would like to follow along, please make sure to install VS Code (https://code.visualstudio.com/Download), Rust and the "rustup" VS Code extension (https://rustup.rs). |
| Speaker | Ryan Levick |
| Moderator | @meaghanlewis |
| SharePoint ID | 7962 |  

Additional Resources:  
<Additional resources that can be linked from social media for promotion or added to the description of VOD>

# Event Checklist

## 10 Weeks Prior
- [X] Reactor Content Team (RCT) or Speaker opens a new issue for an upcoming stream filling in the Event Information table. Both RCT and Speaker are marked as assignees.
- [X] RCT and Speaker discuss details of the event in the comments of this issue. RCT adds a _confirmed-event_ label and _global-twitch-event_ tag to the issue and adds event to the __Global Live Streams__ project. Issue will appear in the __Upcoming Streams__ column
- [X] Speaker adds a _ready-for-marketing-edit_ label so the RCT can review title and description

## 8 Weeks Prior
- [x] RCT does a review of title and description and removes the _ready-for-marketing-edit_ label 
- [x] RCT moves the issue to the __Ready for SharePoint__ column
- [ ] RCT informs the Reactor Marketing Team of the new event information
- [ ] RCT provides speaker with assets (e.g. slides, overlays) and the survey data for the event
- [ ] RCT moves the issue to the __MONTH Streams Prep__ column (according to the month it will be streamed in)

## 2 Weeks Prior *(Done in /microsoft/Reactors)*
- [ ] Speaker opens a PR with the new content for the stream on the [customer-facing Reactor repository](https://github.com/microsoft/Reactors) and adds the _content-development_ and _global-twitch-event_ tag to the PR. 
- [ ] Speaker adds to the same PR a modification to the [Streaming README](https://github.com/microsoft/Reactors/tree/main/Online) to include their stream information.
- [ ] Speaker adds the RCT assigned to the issue as the reviewer when it is ready for review/merge
- [ ] RCT reviews, approves, and merges the changes

## 1 Week Prior
- [ ] Speaker and Moderator test setup for streaming (instructions coming soon)
- [ ] RCT checks in with the speaker and moves the issue to the __Ready to Stream__ column

## During and After Stream
- [ ] Speaker and Moderator run the stream
- [ ] RCT submits recording to be uploaded to the Reactor YouTube and to be made available on LearnTV
- [ ] RCT moves issue to the __Stream Complete__ column

**Comment by KimberlyBolton1** [comment]
@rylev 
Edited abstract for your review. Please add any additional tools or knowledge you would like your audience to have to get the most out of your session.

Code and Coffee: Build a Rust App
You may know the basics of Rust: that it is a memory-safe, fast, general-purpose programming language. In this session, we will dust off our programming skills and take a deeper dive into coding with Rust as we build and test a Rust app using VS Code. If you would like to follow along, please make sure you have VS Code installed.

**Comment by meaghanlewis** [comment]
@KimberlyBolton1 this abstrct looks good to me. ✅

**Comment by KimberlyBolton1** [comment]
@mebaumb
Abstract final and moved to Ready for Sharepoint.

**Comment by mebaumb** [comment]
Event Published on (6/25)

**Comment by rylev** [comment]
Sorry I'm late to this. Perhaps we should add that people will want to install Rust and the rust-analyzer VS Code extension as well. The last line of the description could read: 

"If you would like to follow along, please make sure to install VS Code and the "rust-analyzer" VS Code extension as well as Rust following the instructions on https://rustup.rs."

**Comment by KimberlyBolton1** [comment]
Added to description per late-arriving feedback from content owner.

**Comment by meaghanlewis** [comment]
Thanks @rylev! Apologies for not waiting to get your feedback here.

**Comment by mebaumb** [comment]
Event Cancelled 8/10
