### ISSUE TITLE
Sep 14 - Azure DevOps

### ISSUE THREAD

**Issue by drguthals** [microsoft/ReactorPlanning#47]
# Event Information
| Category | Details |
|-----------|---------|
| Reactor Topic | DevOps and Dev Tools |
| Monthly Topic (if applicable) | Skill Up September |
| Weekly Topic (if applicable) | DevOps |
| Stream Topic | Exploring different DevOps options from Azure |
| Stream Date | September 14, 2020 | 
| Stream Time | 4pm PT | 
| Stream Duration | 60 minutes | 
| Title | Azure Pipelines, and Boards, and Monitors—Oh My!|
| Description | With Azure, you have access to a variety of DevOps services that help you plan smarter, collaborate better, and ship faster. Among the most popular are Azure Pipelines, Azure Boards, and Azure Monitor. During this session, you will dig into these tools and learn how you can customize them to create your own personal workflows. Be brave, have heart, and get your brain ready because it's time follow the yellow brick road to better DevOps!|
| Speaker | @sguthals  |
| Moderator | <Name or GitHub alias> |
| SharePoint ID | 7857 |  

Additional Resources:  
<Additional resources that can be linked from social media for promotion or added to the description of VOD>

# Event Checklist

## 10 Weeks Prior
- [x] Reactor Content Team (RCT) or Speaker opens a new issue for an upcoming stream filling in the Event Information table. Both RCT and Speaker are marked as assignees.
- [x] RCT and Speaker discuss details of the event in the comments of this issue. RCT adds a _confirmed-event_ label and _global-twitch-event_ tag to the issue and adds event to the __Global Live Streams__ project. Issue will appear in the __Upcoming Streams__ column
- [x] Speaker adds a _ready-for-marketing-edit_ label so the RCT can review title and description

## 8 Weeks Prior
- [x] RCT does a review of title and description and removes the _ready-for-marketing-edit_ label 
- [x] RCT moves the issue to the __Ready for SharePoint__ column
- [x] RCT informs the Reactor Marketing Team of the new event information
- [ ] RCT provides speaker with assets (e.g. slides, overlays) and the survey data for the event
- [x] RCT moves the issue to the __MONTH Streams Prep__ column (according to the month it will be streamed in)

## 2 Weeks Prior *(Done in /microsoft/Reactors)*
- [ ] Speaker opens a PR with the new content for the stream on the [customer-facing Reactor repository](https://github.com/microsoft/Reactors) and adds the _content-development_ and _global-twitch-event_ tag to the PR. 
- [ ] Speaker adds to the same PR a modification to the [Streaming README](https://github.com/microsoft/Reactors/tree/main/Online) to include their stream information.
- [ ] Speaker adds the RCT assigned to the issue as the reviewer when it is ready for review/merge
- [ ] RCT reviews, approves, and merges the changes

## 1 Week Prior
- [ ] Speaker and Moderator test setup for streaming (instructions coming soon)
- [ ] RCT checks in with the speaker and moves the issue to the __Ready to Stream__ column

## During and After Stream
- [ ] Speaker and Moderator run the stream
- [ ] RCT submits recording to be uploaded to the Reactor YouTube and to be made available on LearnTV
- [ ] RCT moves issue to the __Stream Complete__ column

**Comment by drguthals** [comment]
I think it would be a good idea to talk about Azure DevOps tools and services:
https://azure.microsoft.com/en-us/solutions/devops/?2000709=&OCID=AID2000709_SEM_XqjyCAAAAE3ddTAk:20200623023617:s&msclkid=deea50c4fe3517c142190e354eeb5259&ef_id=XqjyCAAAAE3ddTAk:20200623023617:s#tools

**Comment by drguthals** [comment]
@KimberlyBolton1 - ready for edit!

**Comment by KimberlyBolton1** [comment]
@sguthals I love your title! I decided to riff off your theme, let me know your thoughts:

Azure Pipelines, and Boards, and Monitors—Oh My!
With Azure, you have access to a variety of DevOps services that help you plan smarter, collaborate better, and ship faster. Among the most popular are Azure Pipelines, Azure Boards, and Azure Monitor. During this session, a “Wizard of Azure” will dig into these tools and show how you can customize them to create your own personal workflows. It’s time you followed the yellow brick road to better DevOps!

**Comment by drguthals** [comment]
I worry a little about the "Wizard of Azure" only because it will probably be me and I'm still new :P maybe..."explorer of Azure" or something?

**Comment by KimberlyBolton1** [comment]
@sguthals Perhaps you prefer "Auntie Em" or "Toto"? :) JK--how about this then:

Azure Pipelines, and Boards, and Monitors—Oh My!
With Azure, you have access to a variety of DevOps services that help you plan smarter, collaborate better, and ship faster. Among the most popular are Azure Pipelines, Azure Boards, and Azure Monitor. During this session, you will dig into these tools and learn how you can customize them to create your own personal workflows. Be brave, have heart, and get your brain ready because it's time follow the yellow brick road to better DevOps!

**Comment by drguthals** [comment]
@KimberlyBolton1 
Love it! 

🚢

**Comment by KimberlyBolton1** [comment]
@mebaumb abstract final and moved to Ready for Sharepoint.

**Comment by mebaumb** [comment]
Event published on SharePoint, added to CH9 calendar, and stream reminder email sent. (7/20)

**Comment by mebaumb** [comment]
Event is cancelled
