### ISSUE TITLE
Sep 15 - GitHub and the Power of Innersourcing

### ISSUE THREAD

**Issue by drguthals** [microsoft/ReactorPlanning#48]
# Event Information
| Category | Details |
|-----------|---------|
| Reactor Topic | DevOps and Dev Tools |
| Monthly Topic (if applicable) | Skill Up September |
| Weekly Topic (if applicable) | DevOps |
| Stream Topic | I think we will talk about the services/tools that GitHub offers to innersource and the importance/benefits of innersourcing. |
| Stream Date | September 15, 2020 | 
| Stream Time | 4pm PT | 
| Stream Duration | 60 minutes | 
| Title | How to Use GitHub for Better Project Collaboration|
| Description | GitHub has long served as one of the most popular collaboration tools for developers. Even so, developing software in collaboration with others can get complicated and confusing. In this session, you will learn some interesting, perhaps lesser-known, GutHub features (like InnerSourcing) and how they can integrate with Azure DevOps tools. Join Sarah Guthals, co-author of <i>GitHub For Dummies</i>, to explore the GitHub toolset and begin leveraging it for your own development and collaboration needs. |
| Speaker | @sguthals  |
| Moderator | <Name or GitHub alias> |
| SharePoint ID | 7858 |  

Additional Resources:  
<Additional resources that can be linked from social media for promotion or added to the description of VOD>

# Event Checklist

## 10 Weeks Prior
- [x] Reactor Content Team (RCT) or Speaker opens a new issue for an upcoming stream filling in the Event Information table. Both RCT and Speaker are marked as assignees.
- [x] RCT and Speaker discuss details of the event in the comments of this issue. RCT adds a _confirmed-event_ label and _global-twitch-event_ tag to the issue and adds event to the __Global Live Streams__ project. Issue will appear in the __Upcoming Streams__ column
- [x] Speaker adds a _ready-for-marketing-edit_ label so the RCT can review title and description

## 8 Weeks Prior
- [x] RCT does a review of title and description and removes the _ready-for-marketing-edit_ label 
- [x] RCT moves the issue to the __Ready for SharePoint__ column
- [x] RCT informs the Reactor Marketing Team of the new event information
- [ ] RCT provides speaker with assets (e.g. slides, overlays) and the survey data for the event
- [x] RCT moves the issue to the __MONTH Streams Prep__ column (according to the month it will be streamed in)

## 2 Weeks Prior *(Done in /microsoft/Reactors)*
- [ ] Speaker opens a PR with the new content for the stream on the [customer-facing Reactor repository](https://github.com/microsoft/Reactors) and adds the _content-development_ and _global-twitch-event_ tag to the PR. 
- [ ] Speaker adds to the same PR a modification to the [Streaming README](https://github.com/microsoft/Reactors/tree/main/Online) to include their stream information.
- [ ] Speaker adds the RCT assigned to the issue as the reviewer when it is ready for review/merge
- [ ] RCT reviews, approves, and merges the changes

## 1 Week Prior
- [ ] Speaker and Moderator test setup for streaming (instructions coming soon)
- [ ] RCT checks in with the speaker and moves the issue to the __Ready to Stream__ column

## During and After Stream
- [ ] Speaker and Moderator run the stream
- [ ] RCT submits recording to be uploaded to the Reactor YouTube and to be made available on LearnTV
- [ ] RCT moves issue to the __Stream Complete__ column

**Comment by drguthals** [comment]
Resources: 
https://azure.microsoft.com/en-us/solutions/devops/?2000709=&OCID=AID2000709_SEM_XqjyCAAAAE3ddTAk:20200623023617:s&msclkid=deea50c4fe3517c142190e354eeb5259&ef_id=XqjyCAAAAE3ddTAk:20200623023617:s#tools

https://resources.github.com/whitepapers/introduction-to-innersource/

Integrating Azure and GitHub

**Comment by drguthals** [comment]
@KimberlyBolton1 - Also ready for edits here.

**Comment by KimberlyBolton1** [comment]
Hey @sguthals, on this one I wasn't entirely sure if the focus was on a variety of GitHub features or just those that are collaboration-specific. I tried to bridge the gap in my edit, but take a look and let me know if I went off base. Also, I wasn't sure which of these 2 titles was more apt (collaboration-specific or a broader stance). Your thoughts?

Option A: How to Use GitHub for Better Project Collaboration
Option B: Harnessing the Power of GitHub 
GitHub has long served as one of the most popular collaboration tools for developers. Even so, developing software in collaboration with others can get complicated and confusing.  In this session, you will learn some interesting, perhaps lesser-known, GutHub features (like InnerSourcing) and how they can integrate with Azure DevOps tools. Join Sarah Guthals, co-author of <i>GitHub For Dummies</i>, to explore the GitHub toolset and begin leveraging it for your own development and collaboration needs.

**Comment by drguthals** [comment]
@KimberlyBolton1 - LGTM!

**Comment by KimberlyBolton1** [comment]
@sguthals  do you have a title preference of the two above?

**Comment by drguthals** [comment]
Sorry, didn't realize there was an option....my brain skipped over B!!

I think I like A: How to Use GitHub for Better Project Collaboration

@KimberlyBolton1 - thanks!

**Comment by KimberlyBolton1** [comment]
Great! @mebaumb abstract final and moved to Ready for Sharepoint.

**Comment by mebaumb** [comment]
Event published on SharePoint/meetup, added to ch9 calendar, stream reminder sent, and moved to correct stream column.

**Comment by drguthals** [comment]
@mebaumb - if the Sept 17 one gets moved to sept 15 9-11am then I would like to cancel this one.

**Comment by mebaumb** [comment]
This event was cancelled!
