### ISSUE TITLE
Sep 16 - Azure Sentinel: Your Enterprise Security Protector

### ISSUE THREAD

**Issue by drguthals** [microsoft/ReactorPlanning#49]
# Event Information
| Category | Details |
|-----------|---------|
| Reactor Topic | DevOps and Dev Tools |
| Monthly Topic (if applicable) | Skill Up September |
| Weekly Topic (if applicable) | DevOps |
| Stream Topic | <2-5 words describing the topic> |
| Stream Date | September 16, 2020 | 
| Stream Time | 4 pm PT | 
| Stream Duration | 60 minutes | 
| Title | Azure Sentinel: Your Enterprise Security Protector|
| Description | Azure Sentinel is a cloud-based security information and event manager (SIEM) platform that uses built-in AI to help collect data and then detect, investigate, and respond to security threats found within. In this session, Cloud Advocate Phoummala Schmitt and Senior Program Manager Sarah Young describe its capabilities and then dive into some real-world applications of Azure Sentinel. Come learn how this powerful service can be your go-to for intelligent security analytics. This session requires no previous Azure experience. |
| Speaker | Phoummala Schmitt |
| Moderator | <Name or GitHub alias> |
| SharePoint ID | 7848 |  

Additional Resources:  
<Additional resources that can be linked from social media for promotion or added to the description of VOD>

# Event Checklist

## 10 Weeks Prior
- [x] Reactor Content Team (RCT) or Speaker opens a new issue for an upcoming stream filling in the Event Information table. Both RCT and Speaker are marked as assignees.
- [x] RCT and Speaker discuss details of the event in the comments of this issue. RCT adds a _confirmed-event_ label and _global-twitch-event_ tag to the issue and adds event to the __Global Live Streams__ project. Issue will appear in the __Upcoming Streams__ column
- [x] Speaker adds a _ready-for-marketing-edit_ label so the RCT can review title and description

## 8 Weeks Prior
- [x] RCT does a review of title and description and removes the _ready-for-marketing-edit_ label 
- [x] RCT moves the issue to the __Ready for SharePoint__ column
- [x] RCT informs the Reactor Marketing Team of the new event information
- [ ] RCT provides speaker with assets (e.g. slides, overlays) and the survey data for the event
- [x] RCT moves the issue to the __MONTH Streams Prep__ column (according to the month it will be streamed in)

## 2 Weeks Prior *(Done in /microsoft/Reactors)*
- [ ] Speaker opens a PR with the new content for the stream on the [customer-facing Reactor repository](https://github.com/microsoft/Reactors) and adds the _content-development_ and _global-twitch-event_ tag to the PR. 
- [ ] Speaker adds to the same PR a modification to the [Streaming README](https://github.com/microsoft/Reactors/tree/main/Online) to include their stream information.
- [ ] Speaker adds the RCT assigned to the issue as the reviewer when it is ready for review/merge
- [ ] RCT reviews, approves, and merges the changes

## 1 Week Prior
- [ ] Speaker and Moderator test setup for streaming (instructions coming soon)
- [ ] RCT checks in with the speaker and moves the issue to the __Ready to Stream__ column

## During and After Stream
- [ ] Speaker and Moderator run the stream
- [ ] RCT submits recording to be uploaded to the Reactor YouTube and to be made available on LearnTV
- [ ] RCT moves issue to the __Stream Complete__ column

**Comment by drguthals** [comment]
@exchangegoddess 👋 

Are you still interested in giving this talk on Twitch? We have a few weeks to figure it out, but I wanted to let you know this is where we will be tracking the event 😄 

We will have to have the title/description in by July 10th to ensure proper marketing time. Let me know if you have any questions!

**Comment by drguthals** [comment]
I was thinking that on Monday (#47) I might talk about some basic Azure DevOps tools and on Tuesday (#48) I might talk about GitHub tools and the power of innersourcing. Then on Thursday (#50) I was thinking of maybe setting up a project from scratch that shows off the features from the first 3 days of the week to bring it to a close.

**Comment by mebaumb** [comment]
Updated the time per the convo with Phoummala and Sarah

**Comment by mebaumb** [comment]
@KimberlyBolton1 this is ready for marketing review!

**Comment by KimberlyBolton1** [comment]
@exchangegoddess Please review the edited abstract for your upcoming Twitch session. If all looks good, ping me back as such. Thanks!

Azure Sentinel: Your Enterprise Security Protector
Azure Sentinel is a cloud-based security information and event manager (SIEM) platform that uses built-in AI to help collect data and then detect, investigate, and respond to security threats found within. In this session, Cloud Advocate Phoummala Schmitt and Senior Program Manager Sarah Young describe its capabilities and then dive into some real-world applications of Azure Sentinel. Come learn how this powerful service can be your go-to for intelligent security analytics. This session requires no previous Azure experience.

**Comment by KimberlyBolton1** [comment]
@mebaumb abstract approved (over Teams with content owner) and final. Moved to Ready for Sharepoint.

**Comment by mebaumb** [comment]
Event published on Sharepoint/meetup, added to stream column and stream reminder sent (7/20)
