### ISSUE TITLE
July 13 - Developer's Introduction to Data Science

### ISSUE THREAD

**Issue by drguthals** [microsoft/ReactorPlanning#5]
# Event Information
| Category | Details |
|-----------|---------|
| Reactor Topic | Data Science and Machine Learning |
| Monthly Topic (if applicable) | Connecting with Our World Through Data |
| Weekly Topic (if applicable) | Data Science |
| Stream Topic | This is to promote the video series on dev intro to DS |
| Stream Date | July 13, 2020 | 
| Stream Time | 4pm PT | 
| Stream Duration | 60 min | 
| Title | Developer's Introduction to Data Science |
| Description | Join the conversation as we discuss the importance of data science in every developer's journey. Whether you're interested in learning and engaging in data science directly or want to understand where data science plays a role in a given product, you'll get to listen to and participate in an important and interesting discussion. |
| Speaker | Sarah Guthals and Francesca Lazzeri |
| Moderator | TBD |

Additional Resources:  
<Additional resources that can be linked from social media for promotion or added to the description of VOD>

# Event Checklist

## 10 Weeks Prior
- [X] Reactor Content Team (RCT) or Speaker opens a new issue for an upcoming stream filling in the Event Information table. Both RCT and Speaker are marked as assignees.
- [X] RCT and Speaker discuss details of the event in the comments of this issue. RCT adds a _confirmed-event_ label and _global-twitch-event_ tag to the issue and adds event to the __Global Live Streams__ project. Issue will appear in the __Upcoming Streams__ column
- [X] Speaker adds a _ready-for-marketing-edit_ label so the RCT can review title and description

## 8 Weeks Prior
- [X] RCT does a review of title and description and removes the _ready-for-marketing-edit_ label 
- [X] RCT moves the issue to the __Ready for SharePoint__ column
- [X] RCT informs the Reactor Marketing Team of the new event information
- [ ] RCT provides speaker with assets (e.g. slides, overlays) and the survey data for the event
- [x] RCT moves the issue to the __Stream Preparation In Progress__ column

## 2 Weeks Prior *(Done in /microsoft/Reactors)*
- [x] Speaker opens a PR with the new content for the stream on the [customer-facing Reactor repository](https://github.com/microsoft/Reactors) and adds the _content-development_ and _global-twitch-event_ tag to the PR. 
- [x] Speaker adds to the same PR a modification to the [Streaming README](https://github.com/microsoft/Reactors/tree/main/Online) to include their stream information.
- [x] Speaker adds the RCT assigned to the issue as the reviewer when it is ready for review/merge
- [x] RCT reviews, approves, and merges the changes

## 1 Week Prior
- [x] Speaker and Moderator test setup for streaming (instructions coming soon)
- [x] RCT checks in with the speaker and moves the issue to the __Ready to Stream__ column

## During and After Stream
- [x] Speaker and Moderator run the stream
- [x] RCT submits recording to be uploaded to the Reactor YouTube and to be made available on LearnTV
- [x] RCT moves issue to the __Stream Complete__ column

**Comment by drguthals** [comment]
👋 @francescalazzeri

Here are notes from what we walked about today:
| Minutes | Topic | Reference Material |
|----------|-------|----------------------|
| 5 | Intros and "We made a video series!" | N/A |
| 20 Minutes | Why did we make the series, importance of Data Science | Videos 2, 3  |
| 20 Minutes | What is machine learning, which algorithm should I choose, and what is automl | Videos 4, 5, 6 |
| 15 Minutes | Questions and talk about the upcoming streams | Future Streams for the next two weeks |

**Comment by drguthals** [comment]
@KimberlyBolton1 -> This stream is done 🙌 
I can't remember -> Who downloads the video from Twitch? Is that me?

**Comment by KimberlyBolton1** [comment]
@sguthals it's been @meaghanlewis. She kindly does it by Thursday each week.

**Comment by drguthals** [comment]
@meaghanlewis - are you able to do this each week or is this something we want week-owners to do? My bandwidth isn't great, but I'm happy to kick things off each day during mine if you're not expecting to do it for all of us 😄

**Comment by meaghanlewis** [comment]
@sguthals it's something I'm okay with doing each week!

**Comment by meaghanlewis** [comment]
However @KimberlyBolton1 we could probably get you access to Twitch and you could be able to download the recordings too.

**Comment by KimberlyBolton1** [comment]
@sguthals @meaghanlewis I'm happy to do this myself if you can give me permissions. :thumbsup:

**Comment by KimberlyBolton1** [comment]
@sguthals Session recorded and uploaded to YouTube https://www.youtube.com/watch?v=wLjWoVarg54. Issue closed.
