### ISSUE TITLE
Sep 15 - Kubernetes for DevOps: It Doesn’t Need to Be Greek to You

### ISSUE THREAD

**Issue by drguthals** [microsoft/ReactorPlanning#50]
# Event Information
| Category | Details |
|-----------|---------|
| Reactor Topic | DevOps and Dev Tools |
| Monthly Topic (if applicable) | Skill Up September |
| Weekly Topic (if applicable) | DevOps |
| Stream Topic |  |
| Stream Date | September 15, 2020 | 
| Stream Time | 9am | 
| Stream Duration | 110 minutes | 
| Title | Kubernetes for DevOps: It Doesn’t Need to Be Greek to You |
| Description | <p>Developers today often build applications using containers—packages of microservices that include dependencies and configurations. As applications become more complex, multiple containers are often needed per deployment. To manage this complexity, Kubernetes (the Greek word for helmsmen of a ship or pilot) provides APIs that control how and when those containers run. Kubernetes—also called “K8s” or “K-eights”—is open source, scalable, and can port containers from local machines to the cloud.</p> <p>In this session, you will learn how to create continuous integration and continuous deployment (CI/CD) pipelines for Kubernetes. The demo includes how to create pipelines and push docker containers into a registry before deploying to a Kubernetes cluster. You will also learn how to use Terraform, another open source tool, in release pipelines to provision the infrastructure in the cloud.</p><p>This session recommends a basic knowledge of DevOps. This session will use the following tools: Azure DevOps Services, Azure Kubernetes Service, GitHub Actions, Terraform, and Visual Studio Code. </p> |
| Speaker | Maybe Houssem Dellai  |
| Moderator | <Name or GitHub alias> |
| SharePoint ID | 7859 |  

Additional Resources:  
<Additional resources that can be linked from social media for promotion or added to the description of VOD>

# Event Checklist

## 10 Weeks Prior
- [x] Reactor Content Team (RCT) or Speaker opens a new issue for an upcoming stream filling in the Event Information table. Both RCT and Speaker are marked as assignees.
- [ ] RCT and Speaker discuss details of the event in the comments of this issue. RCT adds a _confirmed-event_ label and _global-twitch-event_ tag to the issue and adds event to the __Global Live Streams__ project. Issue will appear in the __Upcoming Streams__ column
- [ ] Speaker adds a _ready-for-marketing-edit_ label so the RCT can review title and description

## 8 Weeks Prior
- [x] RCT does a review of title and description and removes the _ready-for-marketing-edit_ label 
- [x] RCT moves the issue to the __Ready for SharePoint__ column
- [ ] RCT informs the Reactor Marketing Team of the new event information
- [ ] RCT provides speaker with assets (e.g. slides, overlays) and the survey data for the event
- [ ] RCT moves the issue to the __MONTH Streams Prep__ column (according to the month it will be streamed in)

## 2 Weeks Prior *(Done in /microsoft/Reactors)*
- [ ] Speaker opens a PR with the new content for the stream on the [customer-facing Reactor repository](https://github.com/microsoft/Reactors) and adds the _content-development_ and _global-twitch-event_ tag to the PR. 
- [ ] Speaker adds to the same PR a modification to the [Streaming README](https://github.com/microsoft/Reactors/tree/main/Online) to include their stream information.
- [ ] Speaker adds the RCT assigned to the issue as the reviewer when it is ready for review/merge
- [ ] RCT reviews, approves, and merges the changes

## 1 Week Prior
- [ ] Speaker and Moderator test setup for streaming (instructions coming soon)
- [ ] RCT checks in with the speaker and moves the issue to the __Ready to Stream__ column

## During and After Stream
- [ ] Speaker and Moderator run the stream
- [ ] RCT submits recording to be uploaded to the Reactor YouTube and to be made available on LearnTV
- [ ] RCT moves issue to the __Stream Complete__ column

**Comment by drguthals** [comment]
Maybe a repeat of this one: https://www.youtube.com/watch?v=lUsyPkDPlns

**Comment by drguthals** [comment]
I've emailed Houssem

**Comment by drguthals** [comment]
@KimberlyBolton1 and @mebaumb I would like Houssem to do this one, I've reached out to see if he is interested/available so I will let you know. If he isn't, the title and description will change.

This is the same title/description as the previous talk he gave.

**Comment by mebaumb** [comment]
@KimberlyBolton1 This is ready for a marketing edit!

**Comment by KimberlyBolton1** [comment]
@sguthals Edited abstract for your review. Per feedback from marketing, they are asking for more robust abstracts containing more leadup to the topic and explicit tool and knowledge needed. :).
Kubernetes for DevOps: It Doesn’t Need to Be Greek to You
Developers today often build applications using containers—packages of microservices that include dependencies and configurations. As applications become more complex, multiple containers are often needed per deployment. To manage this complexity, Kubernetes (the Greek word for helmsmen of a ship or pilot) provides APIs that control how and when those containers run. Kubernetes—also called “K8s” or “K-eights”—is open source, scalable, and can port containers from local machines to the cloud.

In this session, you will learn how to create continuous integration and continuous deployment (CI/CD) pipelines for Kubernetes. The demo includes how to create pipelines and push docker containers into a registry before deploying to a Kubernetes cluster. You will also learn how to use Terraform, another open source tool, in release pipelines to provision the infrastructure in the cloud. 

This session recommends a basic knowledge of DevOps. This session will use the following tools: Azure DevOps Services, Azure Kubernetes Service, GitHub Actions, Terraform, and Visual Studio Code.

**Comment by drguthals** [comment]
Yes this looks good!

**Comment by KimberlyBolton1** [comment]
@mebaumb abstract final and moved to Ready for SharePoint.

**Comment by drguthals** [comment]
@mebaumb -> This might be getting moved to 9-11am on Tuesday Sept 15th instead - I will let you know ASAP before you get it in Sharepoint
