### ISSUE TITLE
Sep 14 - 18: DevOps Tools of the Trade

### ISSUE THREAD

**Issue by meaghanlewis** [microsoft/ReactorPlanning#51]
# Event Information
| Category | Details |
|-----------|---------|
| Reactor Topic | DevOps and DevTools |
| Monthly Topic (if applicable) | Skill Up September |
| Weekly Topic (if applicable) | DevOps |
| Stream Date | Sep 14 - 18, 2020 | 
| Stream Duration | 90 min | 
| Title | DevOps Tools of the Trade |
| Description | <p>From cloning a GitHub repo to setting up an Azure Pipeline, DevOps tools are a critical aspect to developing scalable, professional software. By using the proper services, you can plan smarter, collaborate better, and ship faster. In this workshop, get an introduction to an array of key DevOps tools and documentation resources that will prepare you for your next large project.</p> <p>Prerequisites: Prior to attending this workshop, download Visual Studio Code (https://code.visualstudio.com/Download) and create accounts for  GitHub (https://github.com/join), Azure (https://azure.microsoft.com/free), and Azure DevOps (https://azure.microsoft.com/services/devops/).</p>
 |
| Ref material |  https://www.azuredevopslabs.com/labs/vstsextend/github-azurepipelines |

Additional Resources:  
<Additional resources that can be linked from social media for promotion or added to the description of VOD>
https://docs.microsoft.com/learn/paths/build-applications-with-azure-devops/
# Workshop details
| Date |  Local Start Time |  Location |  Speaker | SharePoint ID |
|----- |------------------|-----------|----------|--------------|
| Sep 14 |  4:00 PM GMT+4 | Abu Dhabi | Aditya Kalia  | 7925 |
| Sep 14 |  5:00 PM  GMT+3 | Tel Aviv | Aditya Kalia  | 7926 |
| Sep 15 |  8:00 PM  GMT+10| Sydney | | 7927 |
| Sep 15 |  6:30 PM GMT+5:30| Bangalore | Aditya Kalia | 7928 |
| Sep 16 |  3:30 PM GMT-3| Sao Paulo | Rafel Dos Santos | 7929 |
| Sep 16 |  7:30 PM GMT+8 | Shanghai | | 7930 |
| Sep 16 | 6:00 PM GMT+1  | London | | 7931 |
| Sep 16 | 4:00 PM PDT | US/Canada | Allen Sanders | 7932 |

# Event Checklist

## 10 Weeks Prior
- [X] Reactor Content Team (RCT) opens a new issue for an upcoming local workshop filling in the Event Information and Workshop details tables. RCT member who owns content (content owner) this week will be the assignee.
- [ ] RCT and content owner discuss details of the event in the comments of this issue. RCT adds a _confirmed-event_ label and _local-digital-event_ tag to the issue and adds event to the __Local Digital Events__ project. Issue will appear in the __Upcoming Streams__ column
- [ ] RCT adds a _ready-for-marketing-edit_ label so the RCT can review title and description

## 8 Weeks Prior
- [x] RCT does a review of title and description and removes the _ready-for-marketing-edit_ label 
- [x] RCT moves the issue to the __Ready for SharePoint__ column
- [ ] RCT informs the Reactor Marketing Team of the new event information
- [ ] RCT confirms the speaker
- [ ] RCT provides speaker with assets (e.g. slides, overlays) and the survey data for the event
- [ ] RCT moves the issue to the __Content Preparation In Progress__ column

## 5 weeks Prior
- [ ] Content owner opens a PR with the new content for the workshop on the [customer-facing Reactor repository](https://github.com/microsoft/Reactors) and adds the _content-development_ and _local-digital-event_ tag to the PR. 
- [ ] Content owner adds to the same PR modification to the [Streaming README](https://github.com/microsoft/Reactors/tree/main/Online) 
- [ ] RCT reviews, approves, and merges the changes
- [ ] RCT shares content with the vendor/instructor
- [ ] RCT provides vendor/instructor with assets (e.g. slides, overlays) and the survey data for the event
- [ ] RCT ensures that instructors have received an invite to the workshops and that PM team works with instructors to get setup in the platform (e.g. Teams, Teams Live Event)

## 1 Week Prior
- [ ] Connect vendor/instructor with the PM(s) for the locations where this event has been marketed
- [ ] Check-in with vendor/instructor that they are prepared for the workshop
- [ ] RCT moves the issue to the __Ready to Stream__ column

## During and After Stream
- [ ] Instructor (and optional moderator) run the stream
- [ ] _(Optional)_RCT submits recording to be uploaded to the Reactor YouTube and to be made available on LearnTV
- [ ] RCT moves issue to the __Stream Complete__ column

**Comment by meaghanlewis** [comment]
Hey @sguthals. I just assigned you to this issue so that you can start thinking about developing content for this week's local streams. As a reminder, the ask is to create **60 min worth of introductory level content** that our external instructors will teach. 

This content can include a PowerPoint deck, code, Markdown file with exercises, a Learn module, or really anyting else that you think will be digestible for instructors and interesting to learners.  This will be our first time trying this out so let me know what questions you might have!

Please have your content prepared by: **August 10**.

**Comment by drguthals** [comment]
Sounds good! I will start thinking about this. Thank you!

**Comment by drguthals** [comment]
@meaghanlewis - does this sound ok for a title/description?

I haven't been in on these so I want to make sure that they are aligned 😄

**Comment by meaghanlewis** [comment]
Yes, this sounds great for a title/description! It focuses on the tools that are needed for collaborative dev projects and then highlights the significant ones that will be demonstrated during the workshop.

Earlier in the week DI had asked for more information about this topic that we could share with potential instructors so let me pass this along. 😄

**Comment by drguthals** [comment]
@KimberlyBolton1 - This is ready for an edit pass!

**Comment by KimberlyBolton1** [comment]
@sguthals @meaghanlewis Here's the edited abstract for your review:

DevOps Tools of the Trade 
From cloning a GitHub repo to setting up an Azure Pipeline, DevOps tools are a critical aspect to developing scalable, professional software. By using the proper services, you can plan smarter, collaborate better, and ship faster. In this workshop, get an introduction to an array of key DevOps tools and documentation resources that will prepare you for your next large project.

**Comment by drguthals** [comment]
@KimberlyBolton1 - LGTM! (Looks Good To Me).

Thanks!

**Comment by KimberlyBolton1** [comment]
@mebaumb abstract final and moved to Ready for Sharepoint

**Comment by mebaumb** [comment]
Everything has been updated in Sharepoint, waiting for speaker details before publishing. (7/22)

**Comment by mebaumb** [comment]
Sent Sao Paulo title description to Caio for translation (7/23)

**Comment by mebaumb** [comment]
Abu Dhabi, Tel Aviv, and Bangalore are all published (7/28)

**Comment by meaghanlewis** [comment]
👋 Hey @sguthals, just wanted to see how this content was coming along. Happy to review any PR's for this when it is available.

**Comment by mebaumb** [comment]
Need to Publish Sao Paulo & US/Canada - Dynamics down

**Comment by drguthals** [comment]
👋 
I would have the vendors be looking at this:
https://www.azuredevopslabs.com/labs/vstsextend/github-azurepipelines/#exercise-1-setting-up-automated-cicd-pipelines-with-azure-pipelines

and then walk the attendees through these steps. I would recommend they can share this out afterwards for our English-speaking locations (it is not localized) but I would recommend that this is what they walk them through! 😄

**Comment by drguthals** [comment]
This should be the follow on learning path! 
https://docs.microsoft.com/en-us/learn/paths/build-applications-with-azure-devops/

😄

**Comment by meaghanlewis** [comment]
Thanks @sguthals!

Could we modify the description to say that VS Code, a GitHub account,an Azure account, and Azure DevOps account are pre-requisites to following along in this workshop? Let me know if that would be okay @KimberlyBolton1 @mebaumb

**Comment by KimberlyBolton1** [comment]
@meaghanlewis @sguthals 
Yes, definitely. I've appended the pre reqs to the end of the abstract in the issue above.

**Comment by drguthals** [comment]
@meaghanlewis
- Just checking - do you need anything else from me for this? Otherwise I might remove myself as an assignee to clear up what I'm doing :)

**Comment by meaghanlewis** [comment]
@sguthals no, shouldn't need anything else from you unless any questions come up from instructors. Feel free to remove yourself as an assignee!

**Comment by mebaumb** [comment]
Workshops happened, numbers have been shared with DI closing streams.
