### ISSUE TITLE
Sep 23 - Take the Boring out of Forms with Vue and Azure Static Web Apps

### ISSUE THREAD

**Issue by drguthals** [microsoft/ReactorPlanning#54]
# Event Information
| Category | Details |
|-----------|---------|
| Reactor Topic | Cloud Development |
| Monthly Topic (if applicable) | Skill Up September |
| Weekly Topic (if applicable) | <Topic decided by RCT if relevant> |
| Stream Topic | <2-5 words describing the topic> |
| Stream Date | September 23, 2020 | 
| Stream Time | 9:00 am PST | 
| Stream Duration | 60 mins | 
| Title |Take the Boring out of Forms with Vue and Azure Static Web Apps|
| Description |99% of the applications written consist of a form on top of a database. But you never see those kinds of apps in demos for new technology. Why? Because people think they are boring! In truth, they are a quick, easy way to create forms. In this stream, we'll build a data entry form using the Vue framework, store the data in a Cosmos DB, and deploy it to Azure Static Web Apps.|
| Speaker | Burke Holland |
| Moderator | TBD |
| SharePoint ID | 7872 |  

Additional Resources:  
<Additional resources that can be linked from social media for promotion or added to the description of VOD>

# Event Checklist

## 10 Weeks Prior
- [X] Reactor Content Team (RCT) or Speaker opens a new issue for an upcoming stream filling in the Event Information table. Both RCT and Speaker are marked as assignees.
- [X] RCT and Speaker discuss details of the event in the comments of this issue. RCT adds a _confirmed-event_ label and _global-twitch-event_ tag to the issue and adds event to the __Global Live Streams__ project. Issue will appear in the __Upcoming Streams__ column
- [X] Speaker adds a _ready-for-marketing-edit_ label so the RCT can review title and description

## 8 Weeks Prior
- [ ] RCT does a review of title and description and removes the _ready-for-marketing-edit_ label 
- [ ] RCT moves the issue to the __Ready for SharePoint__ column
- [ ] RCT informs the Reactor Marketing Team of the new event information
- [ ] RCT provides speaker with assets (e.g. slides, overlays) and the survey data for the event
- [ ] RCT moves the issue to the __MONTH Streams Prep__ column (according to the month it will be streamed in)

## 2 Weeks Prior *(Done in /microsoft/Reactors)*
- [ ] Speaker opens a PR with the new content for the stream on the [customer-facing Reactor repository](https://github.com/microsoft/Reactors) and adds the _content-development_ and _global-twitch-event_ tag to the PR. 
- [ ] Speaker adds to the same PR a modification to the [Streaming README](https://github.com/microsoft/Reactors/tree/main/Online) to include their stream information.
- [ ] Speaker adds the RCT assigned to the issue as the reviewer when it is ready for review/merge
- [ ] RCT reviews, approves, and merges the changes

## 1 Week Prior
- [ ] Speaker and Moderator test setup for streaming (instructions coming soon)
- [ ] RCT checks in with the speaker and moves the issue to the __Ready to Stream__ column

## During and After Stream
- [ ] Speaker and Moderator run the stream
- [ ] RCT submits recording to be uploaded to the Reactor YouTube and to be made available on LearnTV
- [ ] RCT moves issue to the __Stream Complete__ column

**Comment by mebaumb** [comment]
Somehow this didn't get cancelled when we cancelled all the streams this week. 

Cancelling/closing now.

**Comment by drguthals** [comment]
This was for a CA - did we cancel all CA events as well?

**Comment by GeekTrainer** [comment]
My understanding from Golnaz is MicrosoftDeveloper is dark during Ignite

**Comment by mebaumb** [comment]
I reached out to Burke to get it rescheduled.

**Comment by drguthals** [comment]
Oh that's right :) Sorry!
