### ISSUE TITLE
Sep 28 - How to become a blockchain developer

### ISSUE THREAD

**Issue by drguthals** [microsoft/ReactorPlanning#57]
# Event Information
| Category | Details |
|-----------|---------|
| Reactor Topic | Emerging Technologies  |
| Monthly Topic (if applicable) | Skill Up September |
| Weekly Topic (if applicable) | Blockchain |
| Stream Date | September 28, 2020 | 
| Stream Time | 4pm PT | 
| Stream Duration | 60 minutes | 
| Title | How to Become a Blockchain Developer |
| Description | You’ve heard that blockchain is one of the most exciting emerging technologies today and maybe you’d like to have a bigger role in its effect on the world. Join Microsoft Senior Program Manager Meaghan Lewis and Yorke Rhodes, Director of Digital Transformation and founding blockchain team member at Microsoft, as they look at a day in the life of a blockchain developer. Learn what blockchain developers do and which skills they need to succeed. You’ll explore the different types of blockchain work available and the industries where you can make the biggest impact. Bring your curiosity and your questions! |
| Speaker | @meaghanlewis + @yorkerhodes3 |
| Moderator | TBD |
| SharePoint ID | 7966 |  

Additional Resources:  
<Additional resources that can be linked from social media for promotion or added to the description of VOD>

# Event Checklist

## 10 Weeks Prior
- [x] Reactor Content Team (RCT) or Speaker opens a new issue for an upcoming stream filling in the Event Information table. Both RCT and Speaker are marked as assignees.
- [x] RCT and Speaker discuss details of the event in the comments of this issue. RCT adds a _confirmed-event_ label and _global-twitch-event_ tag to the issue and adds event to the __Global Live Streams__ project. Issue will appear in the __Upcoming Streams__ column
- [x] Speaker adds a _ready-for-marketing-edit_ label so the RCT can review title and description

## 8 Weeks Prior
- [x] RCT does a review of title and description
- [x] RCT moves the issue to the __Ready for SharePoint__ column
- [x] RCT informs the Reactor Marketing Team of the new event information
- [x] RCT provides speaker with assets (e.g. slides, overlays) and the survey data for the event
- [x] RCT moves the issue to the __Stream Preparation In Progress__ column

## 2 Weeks Prior *(Done in /microsoft/Reactors)*
- [x] Speaker opens a PR with the new content for the stream on the [customer-facing Reactor repository](https://github.com/microsoft/Reactors) and adds the _content-development_ and _global-twitch-event_ tag to the PR. 
- [x] Speaker adds to the same PR a modification to the [Streaming README](https://github.com/microsoft/Reactors/tree/main/Online) to include their stream information.
- [x] Speaker adds the RCT assigned to the issue as the reviewer when it is ready for review/merge
- [x] RCT reviews, approves, and merges the changes

## 1 Week Prior
- [x] Speaker and Moderator test setup for streaming (instructions coming soon)
- [x] RCT checks in with the speaker and moves the issue to the __Ready to Stream__ column

## During and After Stream
- [x] Speaker and Moderator run the stream
- [ ] RCT submits recording to be uploaded to the Reactor YouTube and to be made available on LearnTV
- [ ] RCT moves issue to the __Stream Complete__ column

**Comment by meaghanlewis** [comment]
@caleteeter would you also be interested in being interviewed for this stream? Or perhaps can recommend anyone else that would be interested? 

The title/description will be updated slightly later on, but the main idea here is to chat with a blockchain software engineer about their experiences and skills.

**Comment by caleteeter** [comment]
@meaghanlewis sure, happy to do it.  I also wanted to loop @yorkerhodes3 in on this to contribute in terms of the interview and/or sessions.  He has been a founding member of the blockchain team here at Microsoft.  He mentioned he would be game for this as well.

**Comment by meaghanlewis** [comment]
Thanks @caleteeter!

@yorkerhodes3 would be great to interview you for this if you're game! Let me know.

**Comment by meaghanlewis** [comment]
Connected with @yorkerhodes3 offline and he agreed to co-present with me. 😄

**Comment by KimberlyBolton1** [comment]
@meaghanlewis The edited abstract is below:

How to Become a Blockchain Developer
You’ve heard that blockchain is one of the most exciting emerging technologies today and maybe you’d like to have a bigger role in its effect on the world. Join Microsoft Senior Program Manager Meaghan Lewis and Yorke Rhodes, Director of Digital Transformation and founding blockchain team member at Microsoft, as they look at a day in the life of a blockchain developer. Learn what blockchain developers do and which skills they need to succeed. You’ll explore the different types of blockchain work available and the industries where you can make the biggest impact. Bring your curiosity and your questions!

**Comment by meaghanlewis** [comment]
Your edit looks fantastic @KimberlyBolton1 😄

**Comment by KimberlyBolton1** [comment]
Awesome! @mebaumb Abstract is final and move to Ready for Sharepoint.

**Comment by mebaumb** [comment]
This has been published in SharePoint (7/14)

**Comment by meaghanlewis** [comment]
@mebaumb could you please send out a cal invite reminder for this stream for Yorke and I for 3:45-5pm? Thanks!

**Comment by mebaumb** [comment]
Sent! I am so sorry that I missed doing that somehow!

**Comment by mebaumb** [comment]
This is on Youtube, closing issue!
