### ISSUE TITLE
Sep 29 - Streamline Smart Contract Development with OpenZeppelin

### ISSUE THREAD

**Issue by drguthals** [microsoft/ReactorPlanning#58]
# Event Information
| Category | Details |
|-----------|---------|
| Reactor Topic | Emerging Technologies  |
| Monthly Topic (if applicable) | Skill Up September |
| Weekly Topic (if applicable) | Blockchain |
| Stream Date | September 29, 2020 | 
| Stream Time | 4pm PT | 
| Stream Duration | 60 minutes | 
| Title | Streamline Smart Contract Development with OpenZeppelin |
| Description | OpenZeppelin is a popular open-source platform to help write, deploy, and manage decentralized applications. In this session, you will learn how to integrate the OpenZeppelin toolset with your blockchain applications for more efficient smart contract development. This session recommends a basic understanding of blockchain technology.|
| Speaker | @meaghanlewis |
| Moderator | TBD |
| SharePoint ID | 7967 |  

Additional Resources:  
<Additional resources that can be linked from social media for promotion or added to the description of VOD>

# Event Checklist

## 10 Weeks Prior
- [x] Reactor Content Team (RCT) or Speaker opens a new issue for an upcoming stream filling in the Event Information table. Both RCT and Speaker are marked as assignees.
- [x] RCT and Speaker discuss details of the event in the comments of this issue. RCT adds a _confirmed-event_ label and _global-twitch-event_ tag to the issue and adds event to the __Global Live Streams__ project. Issue will appear in the __Upcoming Streams__ column
- [x] Speaker adds a _ready-for-marketing-edit_ label so the RCT can review title and description

## 8 Weeks Prior
- [x] RCT does a review of title and description
- [x] RCT moves the issue to the __Ready for SharePoint__ column
- [ ] RCT informs the Reactor Marketing Team of the new event information
- [ ] RCT provides speaker with assets (e.g. slides, overlays) and the survey data for the event
- [ ] RCT moves the issue to the __Stream Preparation In Progress__ column

## 2 Weeks Prior *(Done in /microsoft/Reactors)*
- [ ] Speaker opens a PR with the new content for the stream on the [customer-facing Reactor repository](https://github.com/microsoft/Reactors) and adds the _content-development_ and _global-twitch-event_ tag to the PR. 
- [ ] Speaker adds to the same PR a modification to the [Streaming README](https://github.com/microsoft/Reactors/tree/main/Online) to include their stream information.
- [ ] Speaker adds the RCT assigned to the issue as the reviewer when it is ready for review/merge
- [ ] RCT reviews, approves, and merges the changes

## 1 Week Prior
- [ ] Speaker and Moderator test setup for streaming (instructions coming soon)
- [ ] RCT checks in with the speaker and moves the issue to the __Ready to Stream__ column

## During and After Stream
- [ ] Speaker and Moderator run the stream
- [ ] RCT submits recording to be uploaded to the Reactor YouTube and to be made available on LearnTV
- [ ] RCT moves issue to the __Stream Complete__ column

**Comment by KimberlyBolton1** [comment]
Hi @meaghanlewis, check out the edit and let me know if it works for you.

Streamline Smart Contract Development with OpenZeppelin
OpenZeppelin is a popular open-source platform to help write, deploy, and manage decentralized applications. In this session, you will learn how to integrate the OpenZeppelin toolset with your blockchain applications for more efficient smart contract development.
This session recommends a basic understanding of blockchain technology.

**Comment by meaghanlewis** [comment]
@KimberlyBolton1 that looks great, thank you!

**Comment by KimberlyBolton1** [comment]
@mebaumb Abstract is final and moved to Ready for Sharepoint.

**Comment by mebaumb** [comment]
Entered in Sharepoint (7/13)

**Comment by mebaumb** [comment]
This is on Youtube, closing issue!
