### ISSUE TITLE
Sep 30 - Let’s Get Sensitive: Designing APIs with Empathy

### ISSUE THREAD

**Issue by drguthals** [microsoft/ReactorPlanning#59]
# Event Information
| Category | Details |
|-----------|---------|
| Reactor Topic | Coding, Languages, and Frameworks |
| Monthly Topic (if applicable) | Skill Up September |
| Weekly Topic (if applicable) | Blockchain |
| Stream Topic | <2-5 words describing the topic> |
| Stream Date | September 30, 2020 | 
| Stream Time | 9am PT | 
| Stream Duration | 60 minutes | 
| Title | Let’s Get Sensitive: Designing APIs with Empathy |
| Description | In this session, Microsoft Cloud Advocate Alvaro Videla discusses what we can learn from the field of design to create more empathetic APIs. Using design concepts from around the world, this session will investigate the work of designers like Kenya Hara, Viktor Papanek, and Christopher Alexander to learn how to put users’ needs first when creating APIs. Whether you are implementing an object-oriented API for your next project or creating a REST API for your website, this session will teach you what questions to ask to ensure your designs take into consideration the needs of your users for better usability and value.
This session does not require any previous programming experience. This session recommends a basic level of programming experience (any language). |
| Speaker | @videlalvaro  |
| Moderator | TBD |
| SharePoint ID | 7968 |  

Additional Resources:  
<Additional resources that can be linked from social media for promotion or added to the description of VOD>

# Event Checklist

## 10 Weeks Prior
- [x] Reactor Content Team (RCT) or Speaker opens a new issue for an upcoming stream filling in the Event Information table. Both RCT and Speaker are marked as assignees.
- [x] RCT and Speaker discuss details of the event in the comments of this issue. RCT adds a _confirmed-event_ label and _global-twitch-event_ tag to the issue and adds event to the __Global Live Streams__ project. Issue will appear in the __Upcoming Streams__ column
- [x] Speaker adds a _ready-for-marketing-edit_ label so the RCT can review title and description

## 8 Weeks Prior
- [x] RCT does a review of title and description
- [x] RCT moves the issue to the __Ready for SharePoint__ column
- [x] RCT informs the Reactor Marketing Team of the new event information
- [ ] RCT provides speaker with assets (e.g. slides, overlays) and the survey data for the event
- [x] RCT moves the issue to the __Stream Preparation In Progress__ column

## 2 Weeks Prior *(Done in /microsoft/Reactors)*
- [ ] Speaker opens a PR with the new content for the stream on the [customer-facing Reactor repository](https://github.com/microsoft/Reactors) and adds the _content-development_ and _global-twitch-event_ tag to the PR. 
- [ ] Speaker adds to the same PR a modification to the [Streaming README](https://github.com/microsoft/Reactors/tree/main/Online) to include their stream information.
- [ ] Speaker adds the RCT assigned to the issue as the reviewer when it is ready for review/merge
- [ ] RCT reviews, approves, and merges the changes

## 1 Week Prior
- [ ] Speaker and Moderator test setup for streaming (instructions coming soon)
- [ ] RCT checks in with the speaker and moves the issue to the __Ready to Stream__ column

## During and After Stream
- [ ] Speaker and Moderator run the stream
- [ ] RCT submits recording to be uploaded to the Reactor YouTube and to be made available on LearnTV
- [ ] RCT moves issue to the __Stream Complete__ column

**Comment by videlalvaro** [comment]
Hi @meaghanlewis , how can I sign up for this date instead?

**Comment by meaghanlewis** [comment]
👋  @videlalvaro you can enter in your title, description, and speaker handle to the table above and then you're set. The team and I will make sure you have everything you need after that and as we approach the stream date.

Oh, and you can also change the issue title itself from TBD to your title.

**Comment by videlalvaro** [comment]
I just emailed @meaghanlewis with my talk details since I don't know how to edit the table above

**Comment by meaghanlewis** [comment]
Hey @videlalvaro just updated the talk details above. I'm now going to let our technical editor, Kimberly, to review the details.

👋  @KimberlyBolton1 this is ready for you to review.

**Comment by KimberlyBolton1** [comment]
@videlalvaro 
Please review the edited abstract below. If possible, could you provide a couple examples of areas of "empathetic" design for the abstract (ie safety risks, aesthetic value)? Also please review the last sentence to ensure I've chosen the correct level of previous experience required to attend.

Let’s Get Sensitive: Designing APIs with Empathy
In this session, Microsoft Cloud Advocate Alvaro Videla discusses what we can learn from the field of design to create more empathetic APIs. Using design concepts from around the world, this session will investigate the work of designers like Kenya Hara, Viktor Papanek, and Christopher Alexander to learn how to put users’ needs first when creating APIs. Whether you are implementing an object-oriented API for your next project or creating a REST API for your website, this session will teach you what questions to ask to ensure your designs take into consideration the needs of your users for better usability and value.
This session does not require any previous programming experience.

**Comment by meaghanlewis** [comment]
@KimberlyBolton1, @videlalvaro let me know he's going to be on holiday so he might not see this comment for a couple weeks.

**Comment by KimberlyBolton1** [comment]
Per exchange with @meaghanlewis, we'll use the edited version above but not worry about addressing my included questions.
@mebaumb Abstract is final and moved to Ready for Sharepoint.

**Comment by videlalvaro** [comment]
Hey I’m away and I don’t have access to MS stuff. In any case it does requires programming experience to be able to relate the examples to past experience. Examples aren’t programming language specific.

**Comment by KimberlyBolton1** [comment]
Per email from content owner, added a recommendation for basic level of experience to the abstract.

**Comment by mebaumb** [comment]
This has been published on Sharepoint! (7/13)

**Comment by videlalvaro** [comment]
I've had a surgery planned for the end of August so I'm afraid I'll have to cancel. I hope you understand.

**Comment by meaghanlewis** [comment]
Thanks for letting us know @videlalvaro, hope your surgery goes well.

@mebaumb can you please make sure this event gets cancelled in Sharepoint?

**Comment by mebaumb** [comment]
This has been sent to PMs for Cancellation on 7/28
