### ISSUE TITLE
July 14 - Coding Optional: Using Azure Machine Learning Designer

### ISSUE THREAD

**Issue by drguthals** [microsoft/ReactorPlanning#6]
# Event Information
| Category | Details |
|-----------|---------|
| Reactor Topic | Data Science and Machine Learning |
| Monthly Topic (if applicable) | Connecting with Our World Through Data |
| Weekly Topic (if applicable) | Data Science |
| Stream Topic | <2-5 words describing the topic> |
| Stream Date | July 14, 2020 | 
| Stream Time | 4pm PT | 
| Stream Duration | 60 Min | 
| Title | Coding Optional: Using Azure Machine Learning Designer |
| Description | You don’t need to be a coding whiz to use the power of machine learning, thanks to Azure Machine Learning designer. Join this session to create a machine learning pipeline using drag-and-drop and other low-code methods. |
| Speaker | Cassie Breviu |
| Moderator | <Name or GitHub alias> |

Additional Resources:  
<Additional resources that can be linked from social media for promotion or added to the description of VOD>

# Event Checklist

## 10 Weeks Prior
- [X] Reactor Content Team (RCT) or Speaker opens a new issue for an upcoming stream filling in the Event Information table. Both RCT and Speaker are marked as assignees.
- [X] RCT and Speaker discuss details of the event in the comments of this issue. RCT adds a _confirmed-event_ label and _global-twitch-event_ tag to the issue and adds event to the __Global Live Streams__ project. Issue will appear in the __Upcoming Streams__ column
- [X] Speaker adds a _ready-for-marketing-edit_ label so the RCT can review title and description

## 8 Weeks Prior
- [X] RCT does a review of title and description and removes the _ready-for-marketing-edit_ label 
- [X] RCT moves the issue to the __Ready for SharePoint__ column
- [X] RCT informs the Reactor Marketing Team of the new event information
- [ ] RCT provides speaker with assets (e.g. slides, overlays) and the survey data for the event
- [x] RCT moves the issue to the __Stream Preparation In Progress__ column

## 2 Weeks Prior *(Done in /microsoft/Reactors)*
- [ ] Speaker opens a PR with the new content for the stream on the [customer-facing Reactor repository](https://github.com/microsoft/Reactors) and adds the _content-development_ and _global-twitch-event_ tag to the PR. 
- [ ] Speaker adds to the same PR a modification to the [Streaming README](https://github.com/microsoft/Reactors/tree/main/Online) to include their stream information.
- [ ] Speaker adds the RCT assigned to the issue as the reviewer when it is ready for review/merge
- [ ] RCT reviews, approves, and merges the changes

## 1 Week Prior
- [ ] Speaker and Moderator test setup for streaming (instructions coming soon)
- [ ] RCT checks in with the speaker and moves the issue to the __Ready to Stream__ column

## During and After Stream
- [ ] Speaker and Moderator run the stream
- [x] RCT submits recording to be uploaded to the Reactor YouTube and to be made available on LearnTV
- [x] RCT moves issue to the __Stream Complete__ column

**Comment by drguthals** [comment]
👋 @cassieview 

We're just about two weeks away from your Reactor Live Stream on Twitch!

I wanted to make sure of a couple of things:
- [ ] I owe you the survey link for Reactor Surveys, I'm tracking that down and will get it to you. 
- [ ] Do you have any content that you want the audience to have access to before, during, or after your stream? If so:
  - [ ] When do you expect it to be ready?
  - [ ] Where does it live? (If you need a place for it to live, you can add it to the [Online folder on the Reactors repo](https://github.com/microsoft/Reactors/tree/main/Online) by just opening a PR and adding it in there. If it's useful to add your own subfolder, please feel free to do that.) 
  - [ ] Whether you are hosting it on your own repo or in the Reactors repo, could you please add a link to it from the [README in the Online folder on the Reactors repo](https://github.com/microsoft/Reactors/blob/main/Online/README.md)
  - [ ] You can add me (@sguthals) as a reviewer on any PRs to the Reactors repo
- [ ] Do you have a moderator for your stream? 

Please let me know if you have any questions or concerns! And let me know how I can help you be successful! ❤️

**Comment by drguthals** [comment]
@cassieview- Have you streamed to the Microsoft Developer Twitch channel yet? If not, be sure to reach out to @clarkio to get the stream key and such 😄

**Comment by cassiebreviu** [comment]
@sguthals I have not! I will send him an email! Thanks!

**Comment by drguthals** [comment]
Hi @cassieview - here is the slide template: https://slidedecks.blob.core.windows.net/reactorslides/Twitch%20Stream%20Template.potx

Also, do you need help with OBS/Twitch at all and did you get the key?

Finally, your survey link is:
https://aka.ms/Reactor/Survey

and code is:
7793

Do you have any questions prior to your stream?

**Comment by cassiebreviu** [comment]
Hi @sguthals,
I did get a key. I wasnt planning on using any slides, just demos, docs and talk! I noticed that some of the other streams have what seems to be a standard scene for the stream. Should I use that or just my normal scene that I use on my channel? If I should use it where do I find it?

**Comment by drguthals** [comment]
@cassieview 

Awesome! IF you could just make sure to show the survey link+code somewhere (slide or otherwise), but yeah, using slides is definitely not necessary :)

We don't have a Reactor theme yet, so if you want to use the [MicrosoftDeveloper overlays, you can use those](https://microsoft.sharepoint.com/:u:/t/LiveCoders/EfgMe5CX4WdJgjmEgxBmuUIBFOes5PsHjCgwkw5yaF3JTg?e=VpjsTW) or you can use your own 😄

**Comment by cassiebreviu** [comment]
I will use the ms dev overlays. Thanks!

**Comment by drguthals** [comment]
Oh, and @Cassieview ->
Anything to add here: https://github.com/microsoft/Reactors/blob/main/Online/README.md

Resources that viewers can find if they want to try things out on their own? It can be a link to your own repos/blogs or Learn modules, or anything 😄

**Comment by KimberlyBolton1** [comment]
@sguthals @cassieview  Session recorded and uploaded to YouTube https://www.youtube.com/watch?v=k1uaBkmTFvg. issue closed.
