### ISSUE TITLE
July 15 - Get More Instagram Likes with Machine Learning

### ISSUE THREAD

**Issue by drguthals** [microsoft/ReactorPlanning#7]
# Event Information
| Category | Details |
|-----------|---------|
| Reactor Topic | Data Science/Machine Learning |
| Monthly Topic (if applicable) | Connecting with Our World Through Data |
| Weekly Topic (if applicable) | Data Science |
| Stream Topic | <2-5 words describing the topic> |
| Stream Date | July 15, 2020 | 
| Stream Time | 9am PT | 
| Stream Duration | 60 Min | 
| Title | Get More Instagram Likes with Machine Learning |
| Description | Machine learning allows us to understand—and influence— the world around us. In this session, see how you can apply simple machine learning models to understand what makes people “like” Instagram posts. Using Azure Cognitive Services, we will extract features from photographs, and then train a linear regression model to determine what affects “likability”.
This session uses Visual Studio Code, Visual Studio Codespaces, and Jupyter Notebooks. |
| Speaker | Dmitry Soshnikov |
| Moderator | <Name or GitHub alias> |

Additional Resources:  
<Additional resources that can be linked from social media for promotion or added to the description of VOD>

# Event Checklist

## 10 Weeks Prior
- [X] Reactor Content Team (RCT) or Speaker opens a new issue for an upcoming stream filling in the Event Information table. Both RCT and Speaker are marked as assignees.
- [X] RCT and Speaker discuss details of the event in the comments of this issue. RCT adds a _confirmed-event_ label and _global-twitch-event_ tag to the issue and adds event to the __Global Live Streams__ project. Issue will appear in the __Upcoming Streams__ column
- [X] Speaker adds a _ready-for-marketing-edit_ label so the RCT can review title and description

## 8 Weeks Prior
- [X] RCT does a review of title and description and removes the _ready-for-marketing-edit_ label 
- [X] RCT moves the issue to the __Ready for SharePoint__ column
- [X] RCT informs the Reactor Marketing Team of the new event information
- [ ] RCT provides speaker with assets (e.g. slides, overlays) and the survey data for the event
- [x] RCT moves the issue to the __Stream Preparation In Progress__ column

## 2 Weeks Prior *(Done in /microsoft/Reactors)*
- [ ] Speaker opens a PR with the new content for the stream on the [customer-facing Reactor repository](https://github.com/microsoft/Reactors) and adds the _content-development_ and _global-twitch-event_ tag to the PR. 
- [ ] Speaker adds to the same PR a modification to the [Streaming README](https://github.com/microsoft/Reactors/tree/main/Online) to include their stream information.
- [ ] Speaker adds the RCT assigned to the issue as the reviewer when it is ready for review/merge
- [ ] RCT reviews, approves, and merges the changes

## 1 Week Prior
- [ ] Speaker and Moderator test setup for streaming (instructions coming soon)
- [ ] RCT checks in with the speaker and moves the issue to the __Ready to Stream__ column

## During and After Stream
- [ ] Speaker and Moderator run the stream
- [x] RCT submits recording to be uploaded to the Reactor YouTube and to be made available on LearnTV
- [x] RCT moves issue to the __Stream Complete__ column

**Comment by drguthals** [comment]
👋 @shwars

We're just about two weeks away from your Reactor Live Stream on Twitch!

I wanted to make sure of a couple of things:
- [x] I owe you the survey link for Reactor Surveys, I'm tracking that down and will get it to you. 
- [ ] Do you have any content that you want the audience to have access to before, during, or after your stream? If so:
  - [ ] When do you expect it to be ready?
  - [ ] Where does it live? (If you need a place for it to live, you can add it to the [Online folder on the Reactors repo](https://github.com/microsoft/Reactors/tree/main/Online) by just opening a PR and adding it in there. If it's useful to add your own subfolder, please feel free to do that.) 
  - [ ] Whether you are hosting it on your own repo or in the Reactors repo, could you please add a link to it from the [README in the Online folder on the Reactors repo](https://github.com/microsoft/Reactors/blob/main/Online/README.md)
  - [ ] You can add me (@sguthals) as a reviewer on any PRs to the Reactors repo
- [ ] Do you have a moderator for your stream? 

Please let me know if you have any questions or concerns! And let me know how I can help you be successful! ❤️

**Comment by shwars** [comment]
👋 @sguthals 

I think I will put all materials in my own repo under http://github.com/CloudAdvocacy organization (which I have created specifically to store all demos), to speed up possible last-minute revisions. I expect to have the materials ready by the middle of next week (June 8th). I will do the PR to add the link to Reactors repo.

I do not have a moderator at this point, how/where would you advise to look for one?

**Comment by drguthals** [comment]
👋 @shwars

Sounds good! 

For a moderator, typically we look for folks who will know enough about what we're talking about to answer simple questions, but they don't necessarily have to be an expert. The moderators tend to be in the chat and they:
- Greet viewers
- Put links into the chat at the beginning (like where to find your content if they want to follow along)
- Put links into the chat at the end (like the survey and where to find the on-demand videos)
- Answer simple questions throughout

This could be another CA, or someone else on a product team. 

If you don't have a moderator, one thing you could do is just ensure you have the time to stop and look at the chat throughout your stream and have all of the links ready. 😄

**Comment by drguthals** [comment]
@shwars  - Have you streamed to the Microsoft Developer Twitch channel yet? If not, be sure to reach out to @clarkio to get the stream key and such 😄

**Comment by drguthals** [comment]
Hi @shwars- here is the slide template: https://slidedecks.blob.core.windows.net/reactorslides/Twitch%20Stream%20Template.potx

Also, do you need help with OBS/Twitch at all and did you get the key?

Finally, your survey link is:
https://aka.ms/Reactor/Survey

and code is:
7796

Do you have any questions prior to your stream?

**Comment by shwars** [comment]
Hi @sguthals, thank you! I have the streaming key. Can I use the standard "Microsoft Developer" scene layout/design, or there is something specific for the reactor? Whom should I call for help in case something goes wrong at the time of the event? The survey link I should advertise during talk and include into slides, right?

**Comment by drguthals** [comment]
👋 @shwars

Yes, you can use the Microsoft Developer design for now. We are building a Reactor one but it isn't ready yet. 

If you're having problems the day of probably @clarkio is your best bet if it has to do with the Twitch channel, since I don't have admin access. 

Yes please, to advertise the survey link during the talk and include on the slides 😄

**Comment by drguthals** [comment]
Oh, and @shwars->
Anything to add here: https://github.com/microsoft/Reactors/blob/main/Online/README.md

Resources that viewers can find if they want to try things out on their own? It can be a link to your own repos/blogs or Learn modules, or anything 😄

**Comment by shwars** [comment]
@sguthals I have sent the PR to readme.md, waiting for approval

**Comment by drguthals** [comment]
Merged! Thank you!
--

*Sarah Guthals, PhD*
sarah@guthals.com
guthals.com/sarah

**Comment by KimberlyBolton1** [comment]
@shwars Session recorded and uploaded to YouTube https://www.youtube.com/watch?v=YXKKcgUD7xk. Closing issue.
