### ISSUE TITLE
July 20 - Interview with an Expert: Azure Machine Learning

### ISSUE THREAD

**Issue by drguthals** [microsoft/ReactorPlanning#9]
# Event Information
| Category | Details |
|-----------|---------|
| Reactor Topic | Data Science/Machine Learning |
| Monthly Topic (if applicable) | Connecting with Our World Through Data |
| Weekly Topic (if applicable) | Machine Learning |
| Stream Topic | <2-5 words describing the topic> |
| Stream Date | July 20, 2020 | 
| Stream Time | 4pm PT | 
| Stream Duration | 60 Min | 
| Title | Interview with an Expert: Azure Machine Learning		 |
| Description | During this one-hour session, a Microsoft machine learning scientist interviews folks who build the Azure Machine Learning service and its features. We go directly to the source to learn the features and decisions that created Azure Machine Learning. Bring your own questions to ask and get ready to get the inside scoop!  |
| Speaker | Francesca Lazzeri, Stephanie Lindsey, and Mehrnoosh Sameki |
| Moderator | <Name or GitHub alias> |
| Event ID | 7798 |
Additional Resources:  
<Additional resources that can be linked from social media for promotion or added to the description of VOD>

# Event Checklist

## 10 Weeks Prior
- [X] Reactor Content Team (RCT) or Speaker opens a new issue for an upcoming stream filling in the Event Information table. Both RCT and Speaker are marked as assignees.
- [X] RCT and Speaker discuss details of the event in the comments of this issue. RCT adds a _confirmed-event_ label and _global-twitch-event_ tag to the issue and adds event to the __Global Live Streams__ project. Issue will appear in the __Upcoming Streams__ column
- [X] Speaker adds a _ready-for-marketing-edit_ label so the RCT can review title and description

## 8 Weeks Prior
- [X] RCT does a review of title and description and removes the _ready-for-marketing-edit_ label 
- [X] RCT moves the issue to the __Ready for SharePoint__ column
- [X] RCT informs the Reactor Marketing Team of the new event information
- [ ] RCT provides speaker with assets (e.g. slides, overlays) and the survey data for the event
- [x] RCT moves the issue to the __Stream Preparation In Progress__ column

## 2 Weeks Prior *(Done in /microsoft/Reactors)*
- [ ] Speaker opens a PR with the new content for the stream on the [customer-facing Reactor repository](https://github.com/microsoft/Reactors) and adds the _content-development_ and _global-twitch-event_ tag to the PR. 
- [ ] Speaker adds to the same PR a modification to the [Streaming README](https://github.com/microsoft/Reactors/tree/main/Online) to include their stream information.
- [ ] Speaker adds the RCT assigned to the issue as the reviewer when it is ready for review/merge
- [ ] RCT reviews, approves, and merges the changes

## 1 Week Prior
- [ ] Speaker and Moderator test setup for streaming (instructions coming soon)
- [ ] RCT checks in with the speaker and moves the issue to the __Ready to Stream__ column

## During and After Stream
- [ ] Speaker and Moderator run the stream
- [x] RCT submits recording to be uploaded to the Reactor YouTube and to be made available on LearnTV
- [x] RCT moves issue to the __Stream Complete__ column

**Comment by drguthals** [comment]
@FrancescaLazzeri - Were you able to confirm that either Stephanie or Mehrnoosh would be able to stream with you?

Once you have, I can setup a call to help you get setup technically 😄

**Comment by drguthals** [comment]
👋 @FrancescaLazzeri - Just checking to make sure this stream is ready 😄 

I did figure out how to get multiple people on the screen at the same time. Preliminary instructions are here:
https://github.com/microsoft/ReactorPlanning/blob/main/docs/obs-with-multiple-speakers.md

Can you try setting that up and I will help you through it afterwards? 

I can also help you setup OBS.

**Comment by drguthals** [comment]
👋 @FrancescaLazzeri

We're just about 2 weeks away from your stream!

I wanted to make sure of a couple of things:
- [ ] I owe you the survey link for Reactor Surveys, I'm tracking that down and will get it to you. 
- [ ] Do you have any content that you want the audience to have access to before, during, or after your stream? If so:
  - [ ] When do you expect it to be ready?
  - [ ] Where does it live? (If you need a place for it to live, you can add it to the [Online folder on the Reactors repo](https://github.com/microsoft/Reactors/tree/main/online-event-resources) by just opening a PR and adding it in there. If it's useful to add your own subfolder, please feel free to do that.) 
  - [ ] Whether you are hosting it on your own repo or in the Reactors repo, could you please add a link to it from the [README in the Online folder on the Reactors repo](https://github.com/microsoft/Reactors/blob/main/online-event-resources/july-event-resources.md)
  - [ ] You can add me (@sguthals) as a reviewer on any PRs to the Reactors repo
- [ ] Do you have a moderator for your stream? 

Please let me know if you have any questions or concerns! And let me know how I can help you be successful! ❤️

**Comment by KimberlyBolton1** [comment]
Session complete and on YouTube: 

https://youtu.be/vR7N4aUXmaQ
Closing issue.
